/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.resources.solanatokenbalances;

import com.coinbase.cdp.core.CdpClientApiException;
import com.coinbase.cdp.core.CdpClientException;
import com.coinbase.cdp.core.CdpClientHttpResponse;
import com.coinbase.cdp.core.ClientOptions;
import com.coinbase.cdp.core.EndpointMetadata;
import com.coinbase.cdp.core.ObjectMappers;
import com.coinbase.cdp.core.QueryStringMapper;
import com.coinbase.cdp.core.RequestOptions;
import com.coinbase.cdp.errors.BadGatewayError;
import com.coinbase.cdp.errors.BadRequestError;
import com.coinbase.cdp.errors.InternalServerError;
import com.coinbase.cdp.errors.NotFoundError;
import com.coinbase.cdp.errors.ServiceUnavailableError;
import com.coinbase.cdp.resources.solanatokenbalances.requests.ListSolanaTokenBalancesRequest;
import com.coinbase.cdp.resources.solanatokenbalances.types.ListSolanaTokenBalancesResponse;
import com.coinbase.cdp.types.Error;
import com.coinbase.cdp.types.ListSolanaTokenBalancesNetwork;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Collections;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncWithRawResponseSolanaTokenBalancesClient {
  protected final ClientOptions clientOptions;

  AsyncWithRawResponseSolanaTokenBalancesClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Lists the token balances of a Solana address on a given network. The balances include SPL tokens and the native SOL token. The response is paginated, and by default, returns 20 balances per page.
   * <p><strong>Note:</strong> This endpoint is still under development and does not yet provide strong availability or freshness guarantees. Freshness and availability of new token balances will improve over the coming weeks.</p>
   */
  public CompletableFuture<CdpClientHttpResponse<ListSolanaTokenBalancesResponse>> listSolanaTokenBalances(
      ListSolanaTokenBalancesNetwork network, String address) {
    return listSolanaTokenBalances(network,address,ListSolanaTokenBalancesRequest.builder().build());
  }

  /**
   * Lists the token balances of a Solana address on a given network. The balances include SPL tokens and the native SOL token. The response is paginated, and by default, returns 20 balances per page.
   * <p><strong>Note:</strong> This endpoint is still under development and does not yet provide strong availability or freshness guarantees. Freshness and availability of new token balances will improve over the coming weeks.</p>
   */
  public CompletableFuture<CdpClientHttpResponse<ListSolanaTokenBalancesResponse>> listSolanaTokenBalances(
      ListSolanaTokenBalancesNetwork network, String address, RequestOptions requestOptions) {
    return listSolanaTokenBalances(network,address,ListSolanaTokenBalancesRequest.builder().build(),requestOptions);
  }

  /**
   * Lists the token balances of a Solana address on a given network. The balances include SPL tokens and the native SOL token. The response is paginated, and by default, returns 20 balances per page.
   * <p><strong>Note:</strong> This endpoint is still under development and does not yet provide strong availability or freshness guarantees. Freshness and availability of new token balances will improve over the coming weeks.</p>
   */
  public CompletableFuture<CdpClientHttpResponse<ListSolanaTokenBalancesResponse>> listSolanaTokenBalances(
      ListSolanaTokenBalancesNetwork network, String address,
      ListSolanaTokenBalancesRequest request) {
    return listSolanaTokenBalances(network,address,request,null);
  }

  /**
   * Lists the token balances of a Solana address on a given network. The balances include SPL tokens and the native SOL token. The response is paginated, and by default, returns 20 balances per page.
   * <p><strong>Note:</strong> This endpoint is still under development and does not yet provide strong availability or freshness guarantees. Freshness and availability of new token balances will improve over the coming weeks.</p>
   */
  public CompletableFuture<CdpClientHttpResponse<ListSolanaTokenBalancesResponse>> listSolanaTokenBalances(
      ListSolanaTokenBalancesNetwork network, String address,
      ListSolanaTokenBalancesRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("v2/solana/token-balances")
      .addPathSegment(network.toString())
      .addPathSegment(address);if (request.getPageSize().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "pageSize", request.getPageSize().get(), false);
      }
      if (request.getPageToken().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "pageToken", request.getPageToken().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .tag(EndpointMetadata.class, new EndpointMetadata(Collections.emptyList(), Collections.emptyList()))
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<CdpClientHttpResponse<ListSolanaTokenBalancesResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new CdpClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListSolanaTokenBalancesResponse.class), response));
              return;
            }
            try {
              switch (response.code()) {
                case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response));
                return;
                case 404:future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response));
                return;
                case 500:future.completeExceptionally(new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response));
                return;
                case 502:future.completeExceptionally(new BadGatewayError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response));
                return;
                case 503:future.completeExceptionally(new ServiceUnavailableError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new CdpClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (JsonProcessingException e) {
            future.completeExceptionally(new CdpClientException("Failed to decode HTTP response", e));
          }
          catch (IOException e) {
            future.completeExceptionally(new CdpClientException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new CdpClientException("Network error executing HTTP request", e));
        }
      });
      return future;
    }
  }
