/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A webhook event type identifier following dot-separated format: &#x60;&lt;domain&gt;.&lt;entity&gt;.&lt;verb&gt;&#x60; (e.g., \&quot;onchain.activity.detected\&quot;). 
 */
public enum EventType {
  
  ONCHAIN_ACTIVITY_DETECTED("onchain.activity.detected"),
  
  WALLET_ACTIVITY_DETECTED("wallet.activity.detected"),
  
  WALLET_ACTIVITY_MULTI("wallet.activity.multi"),
  
  WALLET_TRANSACTION_CREATED("wallet.transaction.created"),
  
  WALLET_TRANSACTION_SIGNED("wallet.transaction.signed"),
  
  WALLET_TRANSACTION_BROADCAST("wallet.transaction.broadcast"),
  
  WALLET_TRANSACTION_REPLACED("wallet.transaction.replaced"),
  
  WALLET_TRANSACTION_PENDING("wallet.transaction.pending"),
  
  WALLET_TRANSACTION_CONFIRMED("wallet.transaction.confirmed"),
  
  WALLET_TRANSACTION_FAILED("wallet.transaction.failed"),
  
  WALLET_DELEGATION_CREATED("wallet.delegation.created"),
  
  WALLET_DELEGATION_REVOKED("wallet.delegation.revoked"),
  
  WALLET_TYPED_DATA_SIGNED("wallet.typed_data.signed"),
  
  WALLET_MESSAGE_SIGNED("wallet.message.signed"),
  
  WALLET_HASH_SIGNED("wallet.hash.signed"),
  
  PAYMENTS_TRANSFERS_QUOTED("payments.transfers.quoted"),
  
  PAYMENTS_TRANSFERS_PROCESSING("payments.transfers.processing"),
  
  PAYMENTS_TRANSFERS_COMPLETED("payments.transfers.completed"),
  
  PAYMENTS_TRANSFERS_FAILED("payments.transfers.failed"),
  
  PAYMENTS_TRANSFERS_EXPIRED("payments.transfers.expired"),
  
  PAYMENTS_TRANSFERS_TRAVEL_RULE_INCOMPLETE("payments.transfers.travel_rule_incomplete"),
  
  PAYMENTS_TRANSFERS_TRAVEL_RULE_COMPLETED("payments.transfers.travel_rule_completed"),
  
  ONRAMP_TRANSACTION_CREATED("onramp.transaction.created"),
  
  ONRAMP_TRANSACTION_UPDATED("onramp.transaction.updated"),
  
  ONRAMP_TRANSACTION_SUCCESS("onramp.transaction.success"),
  
  ONRAMP_TRANSACTION_FAILED("onramp.transaction.failed"),
  
  OFFRAMP_TRANSACTION_CREATED("offramp.transaction.created"),
  
  OFFRAMP_TRANSACTION_UPDATED("offramp.transaction.updated"),
  
  OFFRAMP_TRANSACTION_SUCCESS("offramp.transaction.success"),
  
  OFFRAMP_TRANSACTION_FAILED("offramp.transaction.failed"),
  
  ACCEPTANCE_PAYMENT_SESSION_CREATED("acceptance.payment_session.created"),
  
  ACCEPTANCE_PAYMENT_SESSION_CANCELED("acceptance.payment_session.canceled"),
  
  ACCEPTANCE_PAYMENT_SESSION_AUTHORIZATION_PENDING("acceptance.payment_session.authorization_pending"),
  
  ACCEPTANCE_PAYMENT_SESSION_AUTHORIZATION_SUCCEEDED("acceptance.payment_session.authorization_succeeded"),
  
  ACCEPTANCE_PAYMENT_SESSION_AUTHORIZATION_FAILED("acceptance.payment_session.authorization_failed"),
  
  ACCEPTANCE_PAYMENT_SESSION_CAPTURE_PENDING("acceptance.payment_session.capture_pending"),
  
  ACCEPTANCE_PAYMENT_SESSION_CAPTURE_SUCCEEDED("acceptance.payment_session.capture_succeeded"),
  
  ACCEPTANCE_PAYMENT_SESSION_CAPTURE_FAILED("acceptance.payment_session.capture_failed"),
  
  ACCEPTANCE_PAYMENT_SESSION_REFUND_PENDING("acceptance.payment_session.refund_pending"),
  
  ACCEPTANCE_PAYMENT_SESSION_REFUND_SUCCEEDED("acceptance.payment_session.refund_succeeded"),
  
  ACCEPTANCE_PAYMENT_SESSION_REFUND_FAILED("acceptance.payment_session.refund_failed"),
  
  ACCEPTANCE_PAYMENT_SESSION_VOID_PENDING("acceptance.payment_session.void_pending"),
  
  ACCEPTANCE_PAYMENT_SESSION_VOID_SUCCEEDED("acceptance.payment_session.void_succeeded"),
  
  ACCEPTANCE_PAYMENT_SESSION_VOID_FAILED("acceptance.payment_session.void_failed"),
  
  ACCEPTANCE_DISBURSEMENT_PENDING("acceptance.disbursement.pending"),
  
  ACCEPTANCE_DISBURSEMENT_SUCCEEDED("acceptance.disbursement.succeeded"),
  
  ACCEPTANCE_DISBURSEMENT_FAILED("acceptance.disbursement.failed"),
  
  CUSTOMERS_CAPABILITY_CHANGED("customers.capability.changed"),
  
  CUSTOMERS_CUSTOMER_DELETED("customers.customer.deleted");

  private String value;

  EventType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static EventType fromValue(String value) {
    for (EventType b : EventType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format("%s=%s", prefix, this.toString());
  }

}

