/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The status of verification: - &#x60;unrequested&#x60;: The limit upgrade has not been submitted. - &#x60;resubmit&#x60;: One or more identity fields must be resubmitted. - &#x60;pending&#x60;: The submitted identity fields are pending review. - &#x60;active&#x60;: The limit upgrade is active. - &#x60;inactive&#x60;: The limit upgrade was rejected and cannot be resubmitted. 
 */
public enum OnrampLimitUpgradeStatus {
  
  UNREQUESTED("unrequested"),
  
  RESUBMIT("resubmit"),
  
  PENDING("pending"),
  
  ACTIVE("active"),
  
  INACTIVE("inactive");

  private String value;

  OnrampLimitUpgradeStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static OnrampLimitUpgradeStatus fromValue(String value) {
    for (OnrampLimitUpgradeStatus b : OnrampLimitUpgradeStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format("%s=%s", prefix, this.toString());
  }

}

