/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.Transfer;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * PaymentsTransfersTravelRuleCompletedEvent
 */
@JsonPropertyOrder({
  PaymentsTransfersTravelRuleCompletedEvent.JSON_PROPERTY_EVENT_I_D,
  PaymentsTransfersTravelRuleCompletedEvent.JSON_PROPERTY_EVENT_TYPE,
  PaymentsTransfersTravelRuleCompletedEvent.JSON_PROPERTY_TIMESTAMP,
  PaymentsTransfersTravelRuleCompletedEvent.JSON_PROPERTY_DATA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class PaymentsTransfersTravelRuleCompletedEvent {
  public static final String JSON_PROPERTY_EVENT_I_D = "eventID";
  @jakarta.annotation.Nonnull
  private UUID eventID;

  /**
   * The type of webhook event.
   */
  public enum EventTypeEnum {
    PAYMENTS_TRANSFERS_TRAVEL_RULE_COMPLETED(String.valueOf("payments.transfers.travel_rule_completed"));

    private String value;

    EventTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EventTypeEnum fromValue(String value) {
      for (EventTypeEnum b : EventTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
  @jakarta.annotation.Nonnull
  private EventTypeEnum eventType;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @jakarta.annotation.Nonnull
  private OffsetDateTime timestamp;

  public static final String JSON_PROPERTY_DATA = "data";
  @jakarta.annotation.Nonnull
  private Transfer data;

  public PaymentsTransfersTravelRuleCompletedEvent() { 
  }

  public PaymentsTransfersTravelRuleCompletedEvent eventID(@jakarta.annotation.Nonnull UUID eventID) {
    this.eventID = eventID;
    return this;
  }

  /**
   * Unique identifier for this webhook event. Use this for idempotency.
   * @return eventID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EVENT_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getEventID() {
    return eventID;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEventID(@jakarta.annotation.Nonnull UUID eventID) {
    this.eventID = eventID;
  }


  public PaymentsTransfersTravelRuleCompletedEvent eventType(@jakarta.annotation.Nonnull EventTypeEnum eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * The type of webhook event.
   * @return eventType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public EventTypeEnum getEventType() {
    return eventType;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEventType(@jakarta.annotation.Nonnull EventTypeEnum eventType) {
    this.eventType = eventType;
  }


  public PaymentsTransfersTravelRuleCompletedEvent timestamp(@jakarta.annotation.Nonnull OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * The UTC ISO 8601 timestamp at which the underlying state change occurred, not the time at which this webhook was delivered.
   * @return timestamp
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimestamp(@jakarta.annotation.Nonnull OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public PaymentsTransfersTravelRuleCompletedEvent data(@jakarta.annotation.Nonnull Transfer data) {
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Transfer getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setData(@jakarta.annotation.Nonnull Transfer data) {
    this.data = data;
  }


  /**
   * Return true if this PaymentsTransfersTravelRuleCompletedEvent object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentsTransfersTravelRuleCompletedEvent paymentsTransfersTravelRuleCompletedEvent = (PaymentsTransfersTravelRuleCompletedEvent) o;
    return Objects.equals(this.eventID, paymentsTransfersTravelRuleCompletedEvent.eventID) &&
        Objects.equals(this.eventType, paymentsTransfersTravelRuleCompletedEvent.eventType) &&
        Objects.equals(this.timestamp, paymentsTransfersTravelRuleCompletedEvent.timestamp) &&
        Objects.equals(this.data, paymentsTransfersTravelRuleCompletedEvent.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventID, eventType, timestamp, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentsTransfersTravelRuleCompletedEvent {\n");
    sb.append("    eventID: ").append(toIndentedString(eventID)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `eventID` to the URL query string
    if (getEventID() != null) {
      joiner.add(String.format("%seventID%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getEventID()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `eventType` to the URL query string
    if (getEventType() != null) {
      joiner.add(String.format("%seventType%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getEventType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `timestamp` to the URL query string
    if (getTimestamp() != null) {
      joiner.add(String.format("%stimestamp%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTimestamp()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `data` to the URL query string
    if (getData() != null) {
      joiner.add(getData().toUrlQueryString(prefix + "data" + suffix));
    }

    return joiner.toString();
  }

    public static class Builder {

    private PaymentsTransfersTravelRuleCompletedEvent instance;

    public Builder() {
      this(new PaymentsTransfersTravelRuleCompletedEvent());
    }

    protected Builder(PaymentsTransfersTravelRuleCompletedEvent instance) {
      this.instance = instance;
    }

    public PaymentsTransfersTravelRuleCompletedEvent.Builder eventID(UUID eventID) {
      this.instance.eventID = eventID;
      return this;
    }
    public PaymentsTransfersTravelRuleCompletedEvent.Builder eventType(EventTypeEnum eventType) {
      this.instance.eventType = eventType;
      return this;
    }
    public PaymentsTransfersTravelRuleCompletedEvent.Builder timestamp(OffsetDateTime timestamp) {
      this.instance.timestamp = timestamp;
      return this;
    }
    public PaymentsTransfersTravelRuleCompletedEvent.Builder data(Transfer data) {
      this.instance.data = data;
      return this;
    }


    /**
    * returns a built PaymentsTransfersTravelRuleCompletedEvent instance.
    *
    * The builder is not reusable.
    */
    public PaymentsTransfersTravelRuleCompletedEvent build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static PaymentsTransfersTravelRuleCompletedEvent.Builder builder() {
    return new PaymentsTransfersTravelRuleCompletedEvent.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public PaymentsTransfersTravelRuleCompletedEvent.Builder toBuilder() {
    return new PaymentsTransfersTravelRuleCompletedEvent.Builder()
      .eventID(getEventID())
      .eventType(getEventType())
      .timestamp(getTimestamp())
      .data(getData());
  }

}

