/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.SepaDetails;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * A SEPA (Single Euro Payments Area) payment method linked to your entity.
 */
@JsonPropertyOrder({
  SepaPaymentMethod.JSON_PROPERTY_PAYMENT_METHOD_ID,
  SepaPaymentMethod.JSON_PROPERTY_ACTIVE,
  SepaPaymentMethod.JSON_PROPERTY_CREATED_AT,
  SepaPaymentMethod.JSON_PROPERTY_UPDATED_AT,
  SepaPaymentMethod.JSON_PROPERTY_PAYMENT_RAIL,
  SepaPaymentMethod.JSON_PROPERTY_SEPA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class SepaPaymentMethod {
  public static final String JSON_PROPERTY_PAYMENT_METHOD_ID = "paymentMethodId";
  @jakarta.annotation.Nonnull
  private String paymentMethodId;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  @jakarta.annotation.Nonnull
  private Boolean active;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime updatedAt;

  /**
   * The payment rail for this payment method.
   */
  public enum PaymentRailEnum {
    SEPA(String.valueOf("sepa"));

    private String value;

    PaymentRailEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PaymentRailEnum fromValue(String value) {
      for (PaymentRailEnum b : PaymentRailEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PAYMENT_RAIL = "paymentRail";
  @jakarta.annotation.Nonnull
  private PaymentRailEnum paymentRail;

  public static final String JSON_PROPERTY_SEPA = "sepa";
  @jakarta.annotation.Nonnull
  private SepaDetails sepa;

  public SepaPaymentMethod() { 
  }

  public SepaPaymentMethod paymentMethodId(@jakarta.annotation.Nonnull String paymentMethodId) {
    this.paymentMethodId = paymentMethodId;
    return this;
  }

  /**
   * The ID of the Payment Method, which is a UUID prefixed by the string &#x60;paymentMethod_&#x60;.
   * @return paymentMethodId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPaymentMethodId() {
    return paymentMethodId;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentMethodId(@jakarta.annotation.Nonnull String paymentMethodId) {
    this.paymentMethodId = paymentMethodId;
  }


  public SepaPaymentMethod active(@jakarta.annotation.Nonnull Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Whether the payment method is active and can be used in transfers. A payment method may be inactive due to verification requirements or entity-level restrictions.
   * @return active
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getActive() {
    return active;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setActive(@jakarta.annotation.Nonnull Boolean active) {
    this.active = active;
  }


  public SepaPaymentMethod createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * The timestamp when the payment method was created.
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public SepaPaymentMethod updatedAt(@jakarta.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * The timestamp when the payment method was last updated.
   * @return updatedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(@jakarta.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public SepaPaymentMethod paymentRail(@jakarta.annotation.Nonnull PaymentRailEnum paymentRail) {
    this.paymentRail = paymentRail;
    return this;
  }

  /**
   * The payment rail for this payment method.
   * @return paymentRail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAYMENT_RAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PaymentRailEnum getPaymentRail() {
    return paymentRail;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_RAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentRail(@jakarta.annotation.Nonnull PaymentRailEnum paymentRail) {
    this.paymentRail = paymentRail;
  }


  public SepaPaymentMethod sepa(@jakarta.annotation.Nonnull SepaDetails sepa) {
    this.sepa = sepa;
    return this;
  }

  /**
   * SEPA (Single Euro Payments Area) details.
   * @return sepa
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SEPA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public SepaDetails getSepa() {
    return sepa;
  }


  @JsonProperty(JSON_PROPERTY_SEPA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSepa(@jakarta.annotation.Nonnull SepaDetails sepa) {
    this.sepa = sepa;
  }


  /**
   * Return true if this SepaPaymentMethod object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SepaPaymentMethod sepaPaymentMethod = (SepaPaymentMethod) o;
    return Objects.equals(this.paymentMethodId, sepaPaymentMethod.paymentMethodId) &&
        Objects.equals(this.active, sepaPaymentMethod.active) &&
        Objects.equals(this.createdAt, sepaPaymentMethod.createdAt) &&
        Objects.equals(this.updatedAt, sepaPaymentMethod.updatedAt) &&
        Objects.equals(this.paymentRail, sepaPaymentMethod.paymentRail) &&
        Objects.equals(this.sepa, sepaPaymentMethod.sepa);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentMethodId, active, createdAt, updatedAt, paymentRail, sepa);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SepaPaymentMethod {\n");
    sb.append("    paymentMethodId: ").append(toIndentedString(paymentMethodId)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    paymentRail: ").append(toIndentedString(paymentRail)).append("\n");
    sb.append("    sepa: ").append(toIndentedString(sepa)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `paymentMethodId` to the URL query string
    if (getPaymentMethodId() != null) {
      joiner.add(String.format("%spaymentMethodId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPaymentMethodId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `active` to the URL query string
    if (getActive() != null) {
      joiner.add(String.format("%sactive%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getActive()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format("%screatedAt%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCreatedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `updatedAt` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format("%supdatedAt%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getUpdatedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `paymentRail` to the URL query string
    if (getPaymentRail() != null) {
      joiner.add(String.format("%spaymentRail%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPaymentRail()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `sepa` to the URL query string
    if (getSepa() != null) {
      joiner.add(getSepa().toUrlQueryString(prefix + "sepa" + suffix));
    }

    return joiner.toString();
  }

    public static class Builder {

    private SepaPaymentMethod instance;

    public Builder() {
      this(new SepaPaymentMethod());
    }

    protected Builder(SepaPaymentMethod instance) {
      this.instance = instance;
    }

    public SepaPaymentMethod.Builder paymentMethodId(String paymentMethodId) {
      this.instance.paymentMethodId = paymentMethodId;
      return this;
    }
    public SepaPaymentMethod.Builder active(Boolean active) {
      this.instance.active = active;
      return this;
    }
    public SepaPaymentMethod.Builder createdAt(OffsetDateTime createdAt) {
      this.instance.createdAt = createdAt;
      return this;
    }
    public SepaPaymentMethod.Builder updatedAt(OffsetDateTime updatedAt) {
      this.instance.updatedAt = updatedAt;
      return this;
    }
    public SepaPaymentMethod.Builder paymentRail(PaymentRailEnum paymentRail) {
      this.instance.paymentRail = paymentRail;
      return this;
    }
    public SepaPaymentMethod.Builder sepa(SepaDetails sepa) {
      this.instance.sepa = sepa;
      return this;
    }


    /**
    * returns a built SepaPaymentMethod instance.
    *
    * The builder is not reusable.
    */
    public SepaPaymentMethod build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SepaPaymentMethod.Builder builder() {
    return new SepaPaymentMethod.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SepaPaymentMethod.Builder toBuilder() {
    return new SepaPaymentMethod.Builder()
      .paymentMethodId(getPaymentMethodId())
      .active(getActive())
      .createdAt(getCreatedAt())
      .updatedAt(getUpdatedAt())
      .paymentRail(getPaymentRail())
      .sepa(getSepa());
  }

}

