/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.PhysicalAddress;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * Beneficiary (receiver) party.
 */
@JsonPropertyOrder({
  TravelRuleBeneficiary.JSON_PROPERTY_FINANCIAL_INSTITUTION,
  TravelRuleBeneficiary.JSON_PROPERTY_NAME,
  TravelRuleBeneficiary.JSON_PROPERTY_ADDRESS,
  TravelRuleBeneficiary.JSON_PROPERTY_WALLET_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class TravelRuleBeneficiary {
  public static final String JSON_PROPERTY_FINANCIAL_INSTITUTION = "financialInstitution";
  @jakarta.annotation.Nullable
  private String financialInstitution;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @jakarta.annotation.Nullable
  private PhysicalAddress address;

  /**
   * The type of the beneficiary&#39;s wallet.
   */
  public enum WalletTypeEnum {
    CUSTODIAL(String.valueOf("custodial")),
    
    SELF_CUSTODY(String.valueOf("self_custody"));

    private String value;

    WalletTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static WalletTypeEnum fromValue(String value) {
      for (WalletTypeEnum b : WalletTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_WALLET_TYPE = "walletType";
  @jakarta.annotation.Nullable
  private WalletTypeEnum walletType;

  public TravelRuleBeneficiary() { 
  }

  public TravelRuleBeneficiary financialInstitution(@jakarta.annotation.Nullable String financialInstitution) {
    this.financialInstitution = financialInstitution;
    return this;
  }

  /**
   * Name of the financial institution.
   * @return financialInstitution
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINANCIAL_INSTITUTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFinancialInstitution() {
    return financialInstitution;
  }


  @JsonProperty(JSON_PROPERTY_FINANCIAL_INSTITUTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinancialInstitution(@jakarta.annotation.Nullable String financialInstitution) {
    this.financialInstitution = financialInstitution;
  }


  public TravelRuleBeneficiary name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Full name of the party.
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public TravelRuleBeneficiary address(@jakarta.annotation.Nullable PhysicalAddress address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PhysicalAddress getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(@jakarta.annotation.Nullable PhysicalAddress address) {
    this.address = address;
  }


  public TravelRuleBeneficiary walletType(@jakarta.annotation.Nullable WalletTypeEnum walletType) {
    this.walletType = walletType;
    return this;
  }

  /**
   * The type of the beneficiary&#39;s wallet.
   * @return walletType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WALLET_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public WalletTypeEnum getWalletType() {
    return walletType;
  }


  @JsonProperty(JSON_PROPERTY_WALLET_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWalletType(@jakarta.annotation.Nullable WalletTypeEnum walletType) {
    this.walletType = walletType;
  }


  /**
   * Return true if this TravelRuleBeneficiary object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TravelRuleBeneficiary travelRuleBeneficiary = (TravelRuleBeneficiary) o;
    return Objects.equals(this.financialInstitution, travelRuleBeneficiary.financialInstitution) &&
        Objects.equals(this.name, travelRuleBeneficiary.name) &&
        Objects.equals(this.address, travelRuleBeneficiary.address) &&
        Objects.equals(this.walletType, travelRuleBeneficiary.walletType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(financialInstitution, name, address, walletType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TravelRuleBeneficiary {\n");
    sb.append("    financialInstitution: ").append(toIndentedString(financialInstitution)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    walletType: ").append(toIndentedString(walletType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `financialInstitution` to the URL query string
    if (getFinancialInstitution() != null) {
      joiner.add(String.format("%sfinancialInstitution%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFinancialInstitution()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `address` to the URL query string
    if (getAddress() != null) {
      joiner.add(getAddress().toUrlQueryString(prefix + "address" + suffix));
    }

    // add `walletType` to the URL query string
    if (getWalletType() != null) {
      joiner.add(String.format("%swalletType%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getWalletType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }

    public static class Builder {

    private TravelRuleBeneficiary instance;

    public Builder() {
      this(new TravelRuleBeneficiary());
    }

    protected Builder(TravelRuleBeneficiary instance) {
      this.instance = instance;
    }

    public TravelRuleBeneficiary.Builder financialInstitution(String financialInstitution) {
      this.instance.financialInstitution = financialInstitution;
      return this;
    }
    public TravelRuleBeneficiary.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public TravelRuleBeneficiary.Builder address(PhysicalAddress address) {
      this.instance.address = address;
      return this;
    }
    public TravelRuleBeneficiary.Builder walletType(WalletTypeEnum walletType) {
      this.instance.walletType = walletType;
      return this;
    }


    /**
    * returns a built TravelRuleBeneficiary instance.
    *
    * The builder is not reusable.
    */
    public TravelRuleBeneficiary build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static TravelRuleBeneficiary.Builder builder() {
    return new TravelRuleBeneficiary.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public TravelRuleBeneficiary.Builder toBuilder() {
    return new TravelRuleBeneficiary.Builder()
      .financialInstitution(getFinancialInstitution())
      .name(getName())
      .address(getAddress())
      .walletType(getWalletType());
  }

}

