/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.Network;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * UserWalletDelegatedSigningSolana4
 */
@JsonPropertyOrder({
  UserWalletDelegatedSigningSolana4.JSON_PROPERTY_TRANSACTION_SIGNATURE,
  UserWalletDelegatedSigningSolana4.JSON_PROPERTY_NETWORK,
  UserWalletDelegatedSigningSolana4.JSON_PROPERTY_FAILED_AT,
  UserWalletDelegatedSigningSolana4.JSON_PROPERTY_USER_ID,
  UserWalletDelegatedSigningSolana4.JSON_PROPERTY_DELEGATION_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class UserWalletDelegatedSigningSolana4 {
  public static final String JSON_PROPERTY_TRANSACTION_SIGNATURE = "transaction_signature";
  @jakarta.annotation.Nonnull
  private String transactionSignature;

  public static final String JSON_PROPERTY_NETWORK = "network";
  @jakarta.annotation.Nonnull
  private Network network;

  public static final String JSON_PROPERTY_FAILED_AT = "failed_at";
  @jakarta.annotation.Nonnull
  private OffsetDateTime failedAt;

  public static final String JSON_PROPERTY_USER_ID = "user_id";
  @jakarta.annotation.Nonnull
  private String userId;

  public static final String JSON_PROPERTY_DELEGATION_ID = "delegation_id";
  @jakarta.annotation.Nonnull
  private String delegationId;

  public UserWalletDelegatedSigningSolana4() { 
  }

  public UserWalletDelegatedSigningSolana4 transactionSignature(@jakarta.annotation.Nonnull String transactionSignature) {
    this.transactionSignature = transactionSignature;
    return this;
  }

  /**
   * The Solana transaction signature.
   * @return transactionSignature
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTransactionSignature() {
    return transactionSignature;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionSignature(@jakarta.annotation.Nonnull String transactionSignature) {
    this.transactionSignature = transactionSignature;
  }


  public UserWalletDelegatedSigningSolana4 network(@jakarta.annotation.Nonnull Network network) {
    this.network = network;
    return this;
  }

  /**
   * The blockchain network identifier.
   * @return network
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Network getNetwork() {
    return network;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNetwork(@jakarta.annotation.Nonnull Network network) {
    this.network = network;
  }


  public UserWalletDelegatedSigningSolana4 failedAt(@jakarta.annotation.Nonnull OffsetDateTime failedAt) {
    this.failedAt = failedAt;
    return this;
  }

  /**
   * When the transaction failed (ISO 8601 format).
   * @return failedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FAILED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getFailedAt() {
    return failedAt;
  }


  @JsonProperty(JSON_PROPERTY_FAILED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFailedAt(@jakarta.annotation.Nonnull OffsetDateTime failedAt) {
    this.failedAt = failedAt;
  }


  public UserWalletDelegatedSigningSolana4 userId(@jakarta.annotation.Nonnull String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * The user ID that owns the User Wallet.
   * @return userId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserId(@jakarta.annotation.Nonnull String userId) {
    this.userId = userId;
  }


  public UserWalletDelegatedSigningSolana4 delegationId(@jakarta.annotation.Nonnull String delegationId) {
    this.delegationId = delegationId;
    return this;
  }

  /**
   * The delegation grant ID used to authorize the action.
   * @return delegationId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DELEGATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDelegationId() {
    return delegationId;
  }


  @JsonProperty(JSON_PROPERTY_DELEGATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDelegationId(@jakarta.annotation.Nonnull String delegationId) {
    this.delegationId = delegationId;
  }


  /**
   * Return true if this User_Wallet__Delegated_Signing__Solana__4 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserWalletDelegatedSigningSolana4 userWalletDelegatedSigningSolana4 = (UserWalletDelegatedSigningSolana4) o;
    return Objects.equals(this.transactionSignature, userWalletDelegatedSigningSolana4.transactionSignature) &&
        Objects.equals(this.network, userWalletDelegatedSigningSolana4.network) &&
        Objects.equals(this.failedAt, userWalletDelegatedSigningSolana4.failedAt) &&
        Objects.equals(this.userId, userWalletDelegatedSigningSolana4.userId) &&
        Objects.equals(this.delegationId, userWalletDelegatedSigningSolana4.delegationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionSignature, network, failedAt, userId, delegationId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserWalletDelegatedSigningSolana4 {\n");
    sb.append("    transactionSignature: ").append(toIndentedString(transactionSignature)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    failedAt: ").append(toIndentedString(failedAt)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    delegationId: ").append(toIndentedString(delegationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `transaction_signature` to the URL query string
    if (getTransactionSignature() != null) {
      joiner.add(String.format("%stransaction_signature%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTransactionSignature()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `network` to the URL query string
    if (getNetwork() != null) {
      joiner.add(String.format("%snetwork%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getNetwork()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `failed_at` to the URL query string
    if (getFailedAt() != null) {
      joiner.add(String.format("%sfailed_at%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFailedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `user_id` to the URL query string
    if (getUserId() != null) {
      joiner.add(String.format("%suser_id%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getUserId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `delegation_id` to the URL query string
    if (getDelegationId() != null) {
      joiner.add(String.format("%sdelegation_id%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDelegationId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }

    public static class Builder {

    private UserWalletDelegatedSigningSolana4 instance;

    public Builder() {
      this(new UserWalletDelegatedSigningSolana4());
    }

    protected Builder(UserWalletDelegatedSigningSolana4 instance) {
      this.instance = instance;
    }

    public UserWalletDelegatedSigningSolana4.Builder transactionSignature(String transactionSignature) {
      this.instance.transactionSignature = transactionSignature;
      return this;
    }
    public UserWalletDelegatedSigningSolana4.Builder network(Network network) {
      this.instance.network = network;
      return this;
    }
    public UserWalletDelegatedSigningSolana4.Builder failedAt(OffsetDateTime failedAt) {
      this.instance.failedAt = failedAt;
      return this;
    }
    public UserWalletDelegatedSigningSolana4.Builder userId(String userId) {
      this.instance.userId = userId;
      return this;
    }
    public UserWalletDelegatedSigningSolana4.Builder delegationId(String delegationId) {
      this.instance.delegationId = delegationId;
      return this;
    }


    /**
    * returns a built UserWalletDelegatedSigningSolana4 instance.
    *
    * The builder is not reusable.
    */
    public UserWalletDelegatedSigningSolana4 build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static UserWalletDelegatedSigningSolana4.Builder builder() {
    return new UserWalletDelegatedSigningSolana4.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public UserWalletDelegatedSigningSolana4.Builder toBuilder() {
    return new UserWalletDelegatedSigningSolana4.Builder()
      .transactionSignature(getTransactionSignature())
      .network(getNetwork())
      .failedAt(getFailedAt())
      .userId(getUserId())
      .delegationId(getDelegationId());
  }

}

