/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * UserWalletDelegatedSigningSolana1
 */
@JsonPropertyOrder({
  UserWalletDelegatedSigningSolana1.JSON_PROPERTY_ADDRESS,
  UserWalletDelegatedSigningSolana1.JSON_PROPERTY_SIGNED_AT,
  UserWalletDelegatedSigningSolana1.JSON_PROPERTY_USER_ID,
  UserWalletDelegatedSigningSolana1.JSON_PROPERTY_DELEGATION_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class UserWalletDelegatedSigningSolana1 {
  public static final String JSON_PROPERTY_ADDRESS = "address";
  @jakarta.annotation.Nonnull
  private String address;

  public static final String JSON_PROPERTY_SIGNED_AT = "signed_at";
  @jakarta.annotation.Nonnull
  private OffsetDateTime signedAt;

  public static final String JSON_PROPERTY_USER_ID = "user_id";
  @jakarta.annotation.Nonnull
  private String userId;

  public static final String JSON_PROPERTY_DELEGATION_ID = "delegation_id";
  @jakarta.annotation.Nonnull
  private String delegationId;

  public UserWalletDelegatedSigningSolana1() { 
  }

  public UserWalletDelegatedSigningSolana1 address(@jakarta.annotation.Nonnull String address) {
    this.address = address;
    return this;
  }

  /**
   * The Solana wallet address that performed the signing.
   * @return address
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddress(@jakarta.annotation.Nonnull String address) {
    this.address = address;
  }


  public UserWalletDelegatedSigningSolana1 signedAt(@jakarta.annotation.Nonnull OffsetDateTime signedAt) {
    this.signedAt = signedAt;
    return this;
  }

  /**
   * When the signing occurred (ISO 8601 format).
   * @return signedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getSignedAt() {
    return signedAt;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignedAt(@jakarta.annotation.Nonnull OffsetDateTime signedAt) {
    this.signedAt = signedAt;
  }


  public UserWalletDelegatedSigningSolana1 userId(@jakarta.annotation.Nonnull String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * The user ID that owns the User Wallet.
   * @return userId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserId(@jakarta.annotation.Nonnull String userId) {
    this.userId = userId;
  }


  public UserWalletDelegatedSigningSolana1 delegationId(@jakarta.annotation.Nonnull String delegationId) {
    this.delegationId = delegationId;
    return this;
  }

  /**
   * The delegation grant ID used to authorize the action.
   * @return delegationId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DELEGATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDelegationId() {
    return delegationId;
  }


  @JsonProperty(JSON_PROPERTY_DELEGATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDelegationId(@jakarta.annotation.Nonnull String delegationId) {
    this.delegationId = delegationId;
  }


  /**
   * Return true if this User_Wallet__Delegated_Signing__Solana__1 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserWalletDelegatedSigningSolana1 userWalletDelegatedSigningSolana1 = (UserWalletDelegatedSigningSolana1) o;
    return Objects.equals(this.address, userWalletDelegatedSigningSolana1.address) &&
        Objects.equals(this.signedAt, userWalletDelegatedSigningSolana1.signedAt) &&
        Objects.equals(this.userId, userWalletDelegatedSigningSolana1.userId) &&
        Objects.equals(this.delegationId, userWalletDelegatedSigningSolana1.delegationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, signedAt, userId, delegationId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserWalletDelegatedSigningSolana1 {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    signedAt: ").append(toIndentedString(signedAt)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    delegationId: ").append(toIndentedString(delegationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `address` to the URL query string
    if (getAddress() != null) {
      joiner.add(String.format("%saddress%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAddress()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `signed_at` to the URL query string
    if (getSignedAt() != null) {
      joiner.add(String.format("%ssigned_at%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSignedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `user_id` to the URL query string
    if (getUserId() != null) {
      joiner.add(String.format("%suser_id%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getUserId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `delegation_id` to the URL query string
    if (getDelegationId() != null) {
      joiner.add(String.format("%sdelegation_id%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDelegationId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }

    public static class Builder {

    private UserWalletDelegatedSigningSolana1 instance;

    public Builder() {
      this(new UserWalletDelegatedSigningSolana1());
    }

    protected Builder(UserWalletDelegatedSigningSolana1 instance) {
      this.instance = instance;
    }

    public UserWalletDelegatedSigningSolana1.Builder address(String address) {
      this.instance.address = address;
      return this;
    }
    public UserWalletDelegatedSigningSolana1.Builder signedAt(OffsetDateTime signedAt) {
      this.instance.signedAt = signedAt;
      return this;
    }
    public UserWalletDelegatedSigningSolana1.Builder userId(String userId) {
      this.instance.userId = userId;
      return this;
    }
    public UserWalletDelegatedSigningSolana1.Builder delegationId(String delegationId) {
      this.instance.delegationId = delegationId;
      return this;
    }


    /**
    * returns a built UserWalletDelegatedSigningSolana1 instance.
    *
    * The builder is not reusable.
    */
    public UserWalletDelegatedSigningSolana1 build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static UserWalletDelegatedSigningSolana1.Builder builder() {
    return new UserWalletDelegatedSigningSolana1.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public UserWalletDelegatedSigningSolana1.Builder toBuilder() {
    return new UserWalletDelegatedSigningSolana1.Builder()
      .address(getAddress())
      .signedAt(getSignedAt())
      .userId(getUserId())
      .delegationId(getDelegationId());
  }

}

