/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * Tax attestation for IRS Form W-9, used for US persons. Carries the W-9-specific backup withholding certification alongside the fields common to every form (&#x60;edeliveryConsent&#x60;, &#x60;acceptedAt&#x60;). 
 */
@JsonPropertyOrder({
  UsW9Attestation.JSON_PROPERTY_FORM,
  UsW9Attestation.JSON_PROPERTY_EDELIVERY_CONSENT,
  UsW9Attestation.JSON_PROPERTY_ACCEPTED_AT,
  UsW9Attestation.JSON_PROPERTY_IS_EXEMPT_BACKUP_WITHHOLDING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class UsW9Attestation {
  /**
   * The tax form being attested to, as listed in &#x60;Customer.requirements.taxAttestation.taxForms[]&#x60;. Must be &#x60;us_w9&#x60; for this variant. 
   */
  public enum FormEnum {
    US_W9(String.valueOf("us_w9"));

    private String value;

    FormEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FormEnum fromValue(String value) {
      for (FormEnum b : FormEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FORM = "form";
  @jakarta.annotation.Nonnull
  private FormEnum form;

  public static final String JSON_PROPERTY_EDELIVERY_CONSENT = "edeliveryConsent";
  @jakarta.annotation.Nonnull
  private Boolean edeliveryConsent;

  public static final String JSON_PROPERTY_ACCEPTED_AT = "acceptedAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime acceptedAt;

  public static final String JSON_PROPERTY_IS_EXEMPT_BACKUP_WITHHOLDING = "isExemptBackupWithholding";
  @jakarta.annotation.Nonnull
  private Boolean isExemptBackupWithholding;

  public UsW9Attestation() { 
  }

  public UsW9Attestation form(@jakarta.annotation.Nonnull FormEnum form) {
    this.form = form;
    return this;
  }

  /**
   * The tax form being attested to, as listed in &#x60;Customer.requirements.taxAttestation.taxForms[]&#x60;. Must be &#x60;us_w9&#x60; for this variant. 
   * @return form
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FORM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public FormEnum getForm() {
    return form;
  }


  @JsonProperty(JSON_PROPERTY_FORM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setForm(@jakarta.annotation.Nonnull FormEnum form) {
    this.form = form;
  }


  public UsW9Attestation edeliveryConsent(@jakarta.annotation.Nonnull Boolean edeliveryConsent) {
    this.edeliveryConsent = edeliveryConsent;
    return this;
  }

  /**
   * Whether the Customer consents to electronic delivery (e-delivery) of tax documents. Both &#x60;true&#x60; and &#x60;false&#x60; are recorded as submitted. 
   * @return edeliveryConsent
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EDELIVERY_CONSENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getEdeliveryConsent() {
    return edeliveryConsent;
  }


  @JsonProperty(JSON_PROPERTY_EDELIVERY_CONSENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEdeliveryConsent(@jakarta.annotation.Nonnull Boolean edeliveryConsent) {
    this.edeliveryConsent = edeliveryConsent;
  }


  public UsW9Attestation acceptedAt(@jakarta.annotation.Nonnull OffsetDateTime acceptedAt) {
    this.acceptedAt = acceptedAt;
    return this;
  }

  /**
   * Timestamp at which the Customer completed the tax attestation, in ISO 8601 / RFC 3339 format. The server may reject obviously non-credible timestamps. 
   * @return acceptedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACCEPTED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getAcceptedAt() {
    return acceptedAt;
  }


  @JsonProperty(JSON_PROPERTY_ACCEPTED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAcceptedAt(@jakarta.annotation.Nonnull OffsetDateTime acceptedAt) {
    this.acceptedAt = acceptedAt;
  }


  public UsW9Attestation isExemptBackupWithholding(@jakarta.annotation.Nonnull Boolean isExemptBackupWithholding) {
    this.isExemptBackupWithholding = isExemptBackupWithholding;
    return this;
  }

  /**
   * Whether the Customer is exempt from backup withholding, as certified on IRS Form W-9. 
   * @return isExemptBackupWithholding
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_EXEMPT_BACKUP_WITHHOLDING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getIsExemptBackupWithholding() {
    return isExemptBackupWithholding;
  }


  @JsonProperty(JSON_PROPERTY_IS_EXEMPT_BACKUP_WITHHOLDING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsExemptBackupWithholding(@jakarta.annotation.Nonnull Boolean isExemptBackupWithholding) {
    this.isExemptBackupWithholding = isExemptBackupWithholding;
  }


  /**
   * Return true if this UsW9Attestation object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsW9Attestation usW9Attestation = (UsW9Attestation) o;
    return Objects.equals(this.form, usW9Attestation.form) &&
        Objects.equals(this.edeliveryConsent, usW9Attestation.edeliveryConsent) &&
        Objects.equals(this.acceptedAt, usW9Attestation.acceptedAt) &&
        Objects.equals(this.isExemptBackupWithholding, usW9Attestation.isExemptBackupWithholding);
  }

  @Override
  public int hashCode() {
    return Objects.hash(form, edeliveryConsent, acceptedAt, isExemptBackupWithholding);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsW9Attestation {\n");
    sb.append("    form: ").append(toIndentedString(form)).append("\n");
    sb.append("    edeliveryConsent: ").append(toIndentedString(edeliveryConsent)).append("\n");
    sb.append("    acceptedAt: ").append(toIndentedString(acceptedAt)).append("\n");
    sb.append("    isExemptBackupWithholding: ").append(toIndentedString(isExemptBackupWithholding)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `form` to the URL query string
    if (getForm() != null) {
      joiner.add(String.format("%sform%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getForm()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `edeliveryConsent` to the URL query string
    if (getEdeliveryConsent() != null) {
      joiner.add(String.format("%sedeliveryConsent%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getEdeliveryConsent()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `acceptedAt` to the URL query string
    if (getAcceptedAt() != null) {
      joiner.add(String.format("%sacceptedAt%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAcceptedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `isExemptBackupWithholding` to the URL query string
    if (getIsExemptBackupWithholding() != null) {
      joiner.add(String.format("%sisExemptBackupWithholding%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getIsExemptBackupWithholding()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }

    public static class Builder {

    private UsW9Attestation instance;

    public Builder() {
      this(new UsW9Attestation());
    }

    protected Builder(UsW9Attestation instance) {
      this.instance = instance;
    }

    public UsW9Attestation.Builder form(FormEnum form) {
      this.instance.form = form;
      return this;
    }
    public UsW9Attestation.Builder edeliveryConsent(Boolean edeliveryConsent) {
      this.instance.edeliveryConsent = edeliveryConsent;
      return this;
    }
    public UsW9Attestation.Builder acceptedAt(OffsetDateTime acceptedAt) {
      this.instance.acceptedAt = acceptedAt;
      return this;
    }
    public UsW9Attestation.Builder isExemptBackupWithholding(Boolean isExemptBackupWithholding) {
      this.instance.isExemptBackupWithholding = isExemptBackupWithholding;
      return this;
    }


    /**
    * returns a built UsW9Attestation instance.
    *
    * The builder is not reusable.
    */
    public UsW9Attestation build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static UsW9Attestation.Builder builder() {
    return new UsW9Attestation.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public UsW9Attestation.Builder toBuilder() {
    return new UsW9Attestation.Builder()
      .form(getForm())
      .edeliveryConsent(getEdeliveryConsent())
      .acceptedAt(getAcceptedAt())
      .isExemptBackupWithholding(getIsExemptBackupWithholding());
  }

}

