/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.X402BatchSettlementChannelConfig;
import com.coinbase.cdp.openapi.model.X402BatchSettlementDepositPayloadDeposit;
import com.coinbase.cdp.openapi.model.X402BatchSettlementVoucher;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * Sent on the first request to fund a channel via an ERC-3009 receiveWithAuthorization deposit.
 */
@JsonPropertyOrder({
  X402BatchSettlementDepositPayload.JSON_PROPERTY_TYPE,
  X402BatchSettlementDepositPayload.JSON_PROPERTY_CHANNEL_CONFIG,
  X402BatchSettlementDepositPayload.JSON_PROPERTY_VOUCHER,
  X402BatchSettlementDepositPayload.JSON_PROPERTY_DEPOSIT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class X402BatchSettlementDepositPayload {
  /**
   * The payload-type discriminator. Must be &#x60;\&quot;deposit\&quot;&#x60; for a channel-funding deposit payload.
   */
  public enum TypeEnum {
    DEPOSIT(String.valueOf("deposit"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_CHANNEL_CONFIG = "channelConfig";
  @jakarta.annotation.Nonnull
  private X402BatchSettlementChannelConfig channelConfig;

  public static final String JSON_PROPERTY_VOUCHER = "voucher";
  @jakarta.annotation.Nonnull
  private X402BatchSettlementVoucher voucher;

  public static final String JSON_PROPERTY_DEPOSIT = "deposit";
  @jakarta.annotation.Nonnull
  private X402BatchSettlementDepositPayloadDeposit deposit;

  public X402BatchSettlementDepositPayload() { 
  }

  public X402BatchSettlementDepositPayload type(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * The payload-type discriminator. Must be &#x60;\&quot;deposit\&quot;&#x60; for a channel-funding deposit payload.
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public X402BatchSettlementDepositPayload channelConfig(@jakarta.annotation.Nonnull X402BatchSettlementChannelConfig channelConfig) {
    this.channelConfig = channelConfig;
    return this;
  }

  /**
   * Get channelConfig
   * @return channelConfig
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CHANNEL_CONFIG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public X402BatchSettlementChannelConfig getChannelConfig() {
    return channelConfig;
  }


  @JsonProperty(JSON_PROPERTY_CHANNEL_CONFIG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChannelConfig(@jakarta.annotation.Nonnull X402BatchSettlementChannelConfig channelConfig) {
    this.channelConfig = channelConfig;
  }


  public X402BatchSettlementDepositPayload voucher(@jakarta.annotation.Nonnull X402BatchSettlementVoucher voucher) {
    this.voucher = voucher;
    return this;
  }

  /**
   * Get voucher
   * @return voucher
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VOUCHER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public X402BatchSettlementVoucher getVoucher() {
    return voucher;
  }


  @JsonProperty(JSON_PROPERTY_VOUCHER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVoucher(@jakarta.annotation.Nonnull X402BatchSettlementVoucher voucher) {
    this.voucher = voucher;
  }


  public X402BatchSettlementDepositPayload deposit(@jakarta.annotation.Nonnull X402BatchSettlementDepositPayloadDeposit deposit) {
    this.deposit = deposit;
    return this;
  }

  /**
   * Get deposit
   * @return deposit
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DEPOSIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public X402BatchSettlementDepositPayloadDeposit getDeposit() {
    return deposit;
  }


  @JsonProperty(JSON_PROPERTY_DEPOSIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeposit(@jakarta.annotation.Nonnull X402BatchSettlementDepositPayloadDeposit deposit) {
    this.deposit = deposit;
  }


  /**
   * Return true if this x402BatchSettlementDepositPayload object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    X402BatchSettlementDepositPayload x402BatchSettlementDepositPayload = (X402BatchSettlementDepositPayload) o;
    return Objects.equals(this.type, x402BatchSettlementDepositPayload.type) &&
        Objects.equals(this.channelConfig, x402BatchSettlementDepositPayload.channelConfig) &&
        Objects.equals(this.voucher, x402BatchSettlementDepositPayload.voucher) &&
        Objects.equals(this.deposit, x402BatchSettlementDepositPayload.deposit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, channelConfig, voucher, deposit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class X402BatchSettlementDepositPayload {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    channelConfig: ").append(toIndentedString(channelConfig)).append("\n");
    sb.append("    voucher: ").append(toIndentedString(voucher)).append("\n");
    sb.append("    deposit: ").append(toIndentedString(deposit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `channelConfig` to the URL query string
    if (getChannelConfig() != null) {
      joiner.add(getChannelConfig().toUrlQueryString(prefix + "channelConfig" + suffix));
    }

    // add `voucher` to the URL query string
    if (getVoucher() != null) {
      joiner.add(getVoucher().toUrlQueryString(prefix + "voucher" + suffix));
    }

    // add `deposit` to the URL query string
    if (getDeposit() != null) {
      joiner.add(getDeposit().toUrlQueryString(prefix + "deposit" + suffix));
    }

    return joiner.toString();
  }

    public static class Builder {

    private X402BatchSettlementDepositPayload instance;

    public Builder() {
      this(new X402BatchSettlementDepositPayload());
    }

    protected Builder(X402BatchSettlementDepositPayload instance) {
      this.instance = instance;
    }

    public X402BatchSettlementDepositPayload.Builder type(TypeEnum type) {
      this.instance.type = type;
      return this;
    }
    public X402BatchSettlementDepositPayload.Builder channelConfig(X402BatchSettlementChannelConfig channelConfig) {
      this.instance.channelConfig = channelConfig;
      return this;
    }
    public X402BatchSettlementDepositPayload.Builder voucher(X402BatchSettlementVoucher voucher) {
      this.instance.voucher = voucher;
      return this;
    }
    public X402BatchSettlementDepositPayload.Builder deposit(X402BatchSettlementDepositPayloadDeposit deposit) {
      this.instance.deposit = deposit;
      return this;
    }


    /**
    * returns a built X402BatchSettlementDepositPayload instance.
    *
    * The builder is not reusable.
    */
    public X402BatchSettlementDepositPayload build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static X402BatchSettlementDepositPayload.Builder builder() {
    return new X402BatchSettlementDepositPayload.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public X402BatchSettlementDepositPayload.Builder toBuilder() {
    return new X402BatchSettlementDepositPayload.Builder()
      .type(getType())
      .channelConfig(getChannelConfig())
      .voucher(getVoucher())
      .deposit(getDeposit());
  }

}

