/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.X402BatchSettlementChannelConfig;
import com.coinbase.cdp.openapi.model.X402BatchSettlementClaim;
import com.coinbase.cdp.openapi.model.X402BatchSettlementVoucher;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * A cooperative refund request. The client emits the minimal shape (just &#x60;channelConfig&#x60; and &#x60;voucher&#x60;, with an optional &#x60;amount&#x60;). A mediating server enriches the payload with &#x60;amount&#x60;, &#x60;refundNonce&#x60;, and &#x60;claims&#x60; before forwarding to the facilitator. Authorizer signatures are optional — the facilitator auto-signs when absent. Field presence determines which shape was sent; the facilitator dispatches accordingly.
 */
@JsonPropertyOrder({
  X402BatchSettlementRefundPayload.JSON_PROPERTY_TYPE,
  X402BatchSettlementRefundPayload.JSON_PROPERTY_CHANNEL_CONFIG,
  X402BatchSettlementRefundPayload.JSON_PROPERTY_VOUCHER,
  X402BatchSettlementRefundPayload.JSON_PROPERTY_AMOUNT,
  X402BatchSettlementRefundPayload.JSON_PROPERTY_REFUND_NONCE,
  X402BatchSettlementRefundPayload.JSON_PROPERTY_CLAIMS,
  X402BatchSettlementRefundPayload.JSON_PROPERTY_REFUND_AUTHORIZER_SIGNATURE,
  X402BatchSettlementRefundPayload.JSON_PROPERTY_CLAIM_AUTHORIZER_SIGNATURE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class X402BatchSettlementRefundPayload {
  /**
   * The payload-type discriminator. Must be &#x60;\&quot;refund\&quot;&#x60; for both the client-emitted and server-enriched shape.
   */
  public enum TypeEnum {
    REFUND(String.valueOf("refund"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_CHANNEL_CONFIG = "channelConfig";
  @jakarta.annotation.Nonnull
  private X402BatchSettlementChannelConfig channelConfig;

  public static final String JSON_PROPERTY_VOUCHER = "voucher";
  @jakarta.annotation.Nonnull
  private X402BatchSettlementVoucher voucher;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @jakarta.annotation.Nullable
  private String amount;

  public static final String JSON_PROPERTY_REFUND_NONCE = "refundNonce";
  @jakarta.annotation.Nullable
  private String refundNonce;

  public static final String JSON_PROPERTY_CLAIMS = "claims";
  @jakarta.annotation.Nullable
  private List<X402BatchSettlementClaim> claims = new ArrayList<>();

  public static final String JSON_PROPERTY_REFUND_AUTHORIZER_SIGNATURE = "refundAuthorizerSignature";
  @jakarta.annotation.Nullable
  private String refundAuthorizerSignature;

  public static final String JSON_PROPERTY_CLAIM_AUTHORIZER_SIGNATURE = "claimAuthorizerSignature";
  @jakarta.annotation.Nullable
  private String claimAuthorizerSignature;

  public X402BatchSettlementRefundPayload() { 
  }

  public X402BatchSettlementRefundPayload type(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * The payload-type discriminator. Must be &#x60;\&quot;refund\&quot;&#x60; for both the client-emitted and server-enriched shape.
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public X402BatchSettlementRefundPayload channelConfig(@jakarta.annotation.Nonnull X402BatchSettlementChannelConfig channelConfig) {
    this.channelConfig = channelConfig;
    return this;
  }

  /**
   * Get channelConfig
   * @return channelConfig
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CHANNEL_CONFIG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public X402BatchSettlementChannelConfig getChannelConfig() {
    return channelConfig;
  }


  @JsonProperty(JSON_PROPERTY_CHANNEL_CONFIG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChannelConfig(@jakarta.annotation.Nonnull X402BatchSettlementChannelConfig channelConfig) {
    this.channelConfig = channelConfig;
  }


  public X402BatchSettlementRefundPayload voucher(@jakarta.annotation.Nonnull X402BatchSettlementVoucher voucher) {
    this.voucher = voucher;
    return this;
  }

  /**
   * Get voucher
   * @return voucher
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VOUCHER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public X402BatchSettlementVoucher getVoucher() {
    return voucher;
  }


  @JsonProperty(JSON_PROPERTY_VOUCHER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVoucher(@jakarta.annotation.Nonnull X402BatchSettlementVoucher voucher) {
    this.voucher = voucher;
  }


  public X402BatchSettlementRefundPayload amount(@jakarta.annotation.Nullable String amount) {
    this.amount = amount;
    return this;
  }

  /**
   * The refund amount in atomic units of &#x60;channelConfig.token&#x60;. Optional in the client-emitted shape (defaults to the full remaining channel balance). Required when the payload is enriched by a mediating server.
   * @return amount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmount(@jakarta.annotation.Nullable String amount) {
    this.amount = amount;
  }


  public X402BatchSettlementRefundPayload refundNonce(@jakarta.annotation.Nullable String refundNonce) {
    this.refundNonce = refundNonce;
    return this;
  }

  /**
   * The on-chain refund nonce for replay protection (uint256 as decimal string). Only present on the server-enriched shape.
   * @return refundNonce
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFUND_NONCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRefundNonce() {
    return refundNonce;
  }


  @JsonProperty(JSON_PROPERTY_REFUND_NONCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefundNonce(@jakarta.annotation.Nullable String refundNonce) {
    this.refundNonce = refundNonce;
  }


  public X402BatchSettlementRefundPayload claims(@jakarta.annotation.Nullable List<X402BatchSettlementClaim> claims) {
    this.claims = claims;
    return this;
  }

  public X402BatchSettlementRefundPayload addClaimsItem(X402BatchSettlementClaim claimsItem) {
    if (this.claims == null) {
      this.claims = new ArrayList<>();
    }
    this.claims.add(claimsItem);
    return this;
  }

  /**
   * Voucher claims to include atomically with the refund. Only present on the server-enriched shape.
   * @return claims
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLAIMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<X402BatchSettlementClaim> getClaims() {
    return claims;
  }


  @JsonProperty(JSON_PROPERTY_CLAIMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClaims(@jakarta.annotation.Nullable List<X402BatchSettlementClaim> claims) {
    this.claims = claims;
  }


  public X402BatchSettlementRefundPayload refundAuthorizerSignature(@jakarta.annotation.Nullable String refundAuthorizerSignature) {
    this.refundAuthorizerSignature = refundAuthorizerSignature;
    return this;
  }

  /**
   * Optional EIP-712 signature from the receiver authorizer over the refund. When omitted, the facilitator auto-signs.
   * @return refundAuthorizerSignature
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFUND_AUTHORIZER_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRefundAuthorizerSignature() {
    return refundAuthorizerSignature;
  }


  @JsonProperty(JSON_PROPERTY_REFUND_AUTHORIZER_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefundAuthorizerSignature(@jakarta.annotation.Nullable String refundAuthorizerSignature) {
    this.refundAuthorizerSignature = refundAuthorizerSignature;
  }


  public X402BatchSettlementRefundPayload claimAuthorizerSignature(@jakarta.annotation.Nullable String claimAuthorizerSignature) {
    this.claimAuthorizerSignature = claimAuthorizerSignature;
    return this;
  }

  /**
   * Optional EIP-712 signature from the receiver authorizer over the included claims. When omitted, the facilitator auto-signs.
   * @return claimAuthorizerSignature
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLAIM_AUTHORIZER_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getClaimAuthorizerSignature() {
    return claimAuthorizerSignature;
  }


  @JsonProperty(JSON_PROPERTY_CLAIM_AUTHORIZER_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClaimAuthorizerSignature(@jakarta.annotation.Nullable String claimAuthorizerSignature) {
    this.claimAuthorizerSignature = claimAuthorizerSignature;
  }


  /**
   * Return true if this x402BatchSettlementRefundPayload object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    X402BatchSettlementRefundPayload x402BatchSettlementRefundPayload = (X402BatchSettlementRefundPayload) o;
    return Objects.equals(this.type, x402BatchSettlementRefundPayload.type) &&
        Objects.equals(this.channelConfig, x402BatchSettlementRefundPayload.channelConfig) &&
        Objects.equals(this.voucher, x402BatchSettlementRefundPayload.voucher) &&
        Objects.equals(this.amount, x402BatchSettlementRefundPayload.amount) &&
        Objects.equals(this.refundNonce, x402BatchSettlementRefundPayload.refundNonce) &&
        Objects.equals(this.claims, x402BatchSettlementRefundPayload.claims) &&
        Objects.equals(this.refundAuthorizerSignature, x402BatchSettlementRefundPayload.refundAuthorizerSignature) &&
        Objects.equals(this.claimAuthorizerSignature, x402BatchSettlementRefundPayload.claimAuthorizerSignature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, channelConfig, voucher, amount, refundNonce, claims, refundAuthorizerSignature, claimAuthorizerSignature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class X402BatchSettlementRefundPayload {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    channelConfig: ").append(toIndentedString(channelConfig)).append("\n");
    sb.append("    voucher: ").append(toIndentedString(voucher)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    refundNonce: ").append(toIndentedString(refundNonce)).append("\n");
    sb.append("    claims: ").append(toIndentedString(claims)).append("\n");
    sb.append("    refundAuthorizerSignature: ").append(toIndentedString(refundAuthorizerSignature)).append("\n");
    sb.append("    claimAuthorizerSignature: ").append(toIndentedString(claimAuthorizerSignature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `channelConfig` to the URL query string
    if (getChannelConfig() != null) {
      joiner.add(getChannelConfig().toUrlQueryString(prefix + "channelConfig" + suffix));
    }

    // add `voucher` to the URL query string
    if (getVoucher() != null) {
      joiner.add(getVoucher().toUrlQueryString(prefix + "voucher" + suffix));
    }

    // add `amount` to the URL query string
    if (getAmount() != null) {
      joiner.add(String.format("%samount%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAmount()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `refundNonce` to the URL query string
    if (getRefundNonce() != null) {
      joiner.add(String.format("%srefundNonce%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getRefundNonce()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `claims` to the URL query string
    if (getClaims() != null) {
      for (int i = 0; i < getClaims().size(); i++) {
        if (getClaims().get(i) != null) {
          joiner.add(getClaims().get(i).toUrlQueryString(String.format("%sclaims%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `refundAuthorizerSignature` to the URL query string
    if (getRefundAuthorizerSignature() != null) {
      joiner.add(String.format("%srefundAuthorizerSignature%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getRefundAuthorizerSignature()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `claimAuthorizerSignature` to the URL query string
    if (getClaimAuthorizerSignature() != null) {
      joiner.add(String.format("%sclaimAuthorizerSignature%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getClaimAuthorizerSignature()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }

    public static class Builder {

    private X402BatchSettlementRefundPayload instance;

    public Builder() {
      this(new X402BatchSettlementRefundPayload());
    }

    protected Builder(X402BatchSettlementRefundPayload instance) {
      this.instance = instance;
    }

    public X402BatchSettlementRefundPayload.Builder type(TypeEnum type) {
      this.instance.type = type;
      return this;
    }
    public X402BatchSettlementRefundPayload.Builder channelConfig(X402BatchSettlementChannelConfig channelConfig) {
      this.instance.channelConfig = channelConfig;
      return this;
    }
    public X402BatchSettlementRefundPayload.Builder voucher(X402BatchSettlementVoucher voucher) {
      this.instance.voucher = voucher;
      return this;
    }
    public X402BatchSettlementRefundPayload.Builder amount(String amount) {
      this.instance.amount = amount;
      return this;
    }
    public X402BatchSettlementRefundPayload.Builder refundNonce(String refundNonce) {
      this.instance.refundNonce = refundNonce;
      return this;
    }
    public X402BatchSettlementRefundPayload.Builder claims(List<X402BatchSettlementClaim> claims) {
      this.instance.claims = claims;
      return this;
    }
    public X402BatchSettlementRefundPayload.Builder refundAuthorizerSignature(String refundAuthorizerSignature) {
      this.instance.refundAuthorizerSignature = refundAuthorizerSignature;
      return this;
    }
    public X402BatchSettlementRefundPayload.Builder claimAuthorizerSignature(String claimAuthorizerSignature) {
      this.instance.claimAuthorizerSignature = claimAuthorizerSignature;
      return this;
    }


    /**
    * returns a built X402BatchSettlementRefundPayload instance.
    *
    * The builder is not reusable.
    */
    public X402BatchSettlementRefundPayload build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static X402BatchSettlementRefundPayload.Builder builder() {
    return new X402BatchSettlementRefundPayload.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public X402BatchSettlementRefundPayload.Builder toBuilder() {
    return new X402BatchSettlementRefundPayload.Builder()
      .type(getType())
      .channelConfig(getChannelConfig())
      .voucher(getVoucher())
      .amount(getAmount())
      .refundNonce(getRefundNonce())
      .claims(getClaims())
      .refundAuthorizerSignature(getRefundAuthorizerSignature())
      .claimAuthorizerSignature(getClaimAuthorizerSignature());
  }

}

