/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.errors;

import com.coinbase.cdp.core.CdpClientApiException;
import com.coinbase.cdp.types.Error;
import okhttp3.Response;

public final class NotFoundError extends CdpClientApiException {
  /**
   * The body of the response that triggered the exception.
   */
  private final Error body;

  public NotFoundError(Error body) {
    super("NotFoundError", 404, body);
    this.body = body;
  }

  public NotFoundError(Error body, Response rawResponse) {
    super("NotFoundError", 404, body, rawResponse);
    this.body = body;
  }

  /**
   * @return the body
   */
  @java.lang.Override
  public Error body() {
    return this.body;
  }
}
