/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.resources.enduseraccounts.requests;

import com.coinbase.cdp.core.ObjectMappers;
import com.coinbase.cdp.resources.enduseraccounts.types.SendSolanaTransactionWithEndUserAccountRequestNetwork;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SendSolanaTransactionWithEndUserAccountRequest.Builder.class
)
public final class SendSolanaTransactionWithEndUserAccountRequest {
  private final Optional<String> idempotencyKey;

  private final Optional<String> developerAuth;

  private final Optional<String> projectId;

  private final String address;

  private final SendSolanaTransactionWithEndUserAccountRequestNetwork network;

  private final Optional<String> walletSecretId;

  private final String transaction;

  private final Optional<Boolean> useCdpSponsor;

  private final Map<String, Object> additionalProperties;

  private SendSolanaTransactionWithEndUserAccountRequest(Optional<String> idempotencyKey,
      Optional<String> developerAuth, Optional<String> projectId, String address,
      SendSolanaTransactionWithEndUserAccountRequestNetwork network,
      Optional<String> walletSecretId, String transaction, Optional<Boolean> useCdpSponsor,
      Map<String, Object> additionalProperties) {
    this.idempotencyKey = idempotencyKey;
    this.developerAuth = developerAuth;
    this.projectId = projectId;
    this.address = address;
    this.network = network;
    this.walletSecretId = walletSecretId;
    this.transaction = transaction;
    this.useCdpSponsor = useCdpSponsor;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return An optional string request header for making requests safely retryable.
   * When included, duplicate requests with the same key will return identical responses.
   * Refer to our <a href="https://docs.cdp.coinbase.com/api-reference/v2/idempotency">Idempotency docs</a> for more information on using idempotency keys.
   */
  @JsonIgnore
  public Optional<String> getIdempotencyKey() {
    return idempotencyKey;
  }

  /**
   * @return A JWT signed using your Wallet Secret, encoded in base64. Refer to the
   * <a href="https://docs.cdp.coinbase.com/api-reference/v2/authentication#2-generate-wallet-token">Generate Wallet Token</a>
   * section of our Authentication docs for more details on how to generate your Wallet Token.
   */
  @JsonIgnore
  public Optional<String> getDeveloperAuth() {
    return developerAuth;
  }

  /**
   * @return The ID of the CDP Project. Required for end users authenticated using custom auth (i.e. a non-CDP JWT provider).
   */
  @JsonIgnore
  public Optional<String> getProjectId() {
    return projectId;
  }

  /**
   * @return The base58 encoded address of the Solana account belonging to the end user.
   */
  @JsonProperty("address")
  public String getAddress() {
    return address;
  }

  /**
   * @return The Solana network to send the transaction to.
   */
  @JsonProperty("network")
  public SendSolanaTransactionWithEndUserAccountRequestNetwork getNetwork() {
    return network;
  }

  /**
   * @return Required when not using delegated signing. The ID of the Temporary Wallet Secret that was used to sign the X-Wallet-Auth Header.
   */
  @JsonProperty("walletSecretId")
  public Optional<String> getWalletSecretId() {
    return walletSecretId;
  }

  /**
   * @return The base64 encoded transaction to sign and send. This transaction can contain multiple instructions for native Solana batching.
   */
  @JsonProperty("transaction")
  public String getTransaction() {
    return transaction;
  }

  /**
   * @return Whether transaction fees should be sponsored by CDP. When true, CDP sponsors the transaction fees on behalf of the end user. When false, the end user is responsible for paying the transaction fees.
   */
  @JsonProperty("useCdpSponsor")
  public Optional<Boolean> getUseCdpSponsor() {
    return useCdpSponsor;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SendSolanaTransactionWithEndUserAccountRequest && equalTo((SendSolanaTransactionWithEndUserAccountRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SendSolanaTransactionWithEndUserAccountRequest other) {
    return idempotencyKey.equals(other.idempotencyKey) && developerAuth.equals(other.developerAuth) && projectId.equals(other.projectId) && address.equals(other.address) && network.equals(other.network) && walletSecretId.equals(other.walletSecretId) && transaction.equals(other.transaction) && useCdpSponsor.equals(other.useCdpSponsor);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.idempotencyKey, this.developerAuth, this.projectId, this.address, this.network, this.walletSecretId, this.transaction, this.useCdpSponsor);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static AddressStage builder() {
    return new Builder();
  }

  public interface AddressStage {
    /**
     * <p>The base58 encoded address of the Solana account belonging to the end user.</p>
     */
    NetworkStage address(@NotNull String address);

    Builder from(SendSolanaTransactionWithEndUserAccountRequest other);
  }

  public interface NetworkStage {
    /**
     * <p>The Solana network to send the transaction to.</p>
     */
    TransactionStage network(
        @NotNull SendSolanaTransactionWithEndUserAccountRequestNetwork network);
  }

  public interface TransactionStage {
    /**
     * <p>The base64 encoded transaction to sign and send. This transaction can contain multiple instructions for native Solana batching.</p>
     */
    _FinalStage transaction(@NotNull String transaction);
  }

  public interface _FinalStage {
    SendSolanaTransactionWithEndUserAccountRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>An optional string request header for making requests safely retryable.
     * When included, duplicate requests with the same key will return identical responses.
     * Refer to our <a href="https://docs.cdp.coinbase.com/api-reference/v2/idempotency">Idempotency docs</a> for more information on using idempotency keys.</p>
     */
    _FinalStage idempotencyKey(Optional<String> idempotencyKey);

    _FinalStage idempotencyKey(String idempotencyKey);

    /**
     * <p>A JWT signed using your Wallet Secret, encoded in base64. Refer to the
     * <a href="https://docs.cdp.coinbase.com/api-reference/v2/authentication#2-generate-wallet-token">Generate Wallet Token</a>
     * section of our Authentication docs for more details on how to generate your Wallet Token.</p>
     */
    _FinalStage developerAuth(Optional<String> developerAuth);

    _FinalStage developerAuth(String developerAuth);

    /**
     * <p>The ID of the CDP Project. Required for end users authenticated using custom auth (i.e. a non-CDP JWT provider).</p>
     */
    _FinalStage projectId(Optional<String> projectId);

    _FinalStage projectId(String projectId);

    /**
     * <p>Required when not using delegated signing. The ID of the Temporary Wallet Secret that was used to sign the X-Wallet-Auth Header.</p>
     */
    _FinalStage walletSecretId(Optional<String> walletSecretId);

    _FinalStage walletSecretId(String walletSecretId);

    /**
     * <p>Whether transaction fees should be sponsored by CDP. When true, CDP sponsors the transaction fees on behalf of the end user. When false, the end user is responsible for paying the transaction fees.</p>
     */
    _FinalStage useCdpSponsor(Optional<Boolean> useCdpSponsor);

    _FinalStage useCdpSponsor(Boolean useCdpSponsor);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements AddressStage, NetworkStage, TransactionStage, _FinalStage {
    private String address;

    private SendSolanaTransactionWithEndUserAccountRequestNetwork network;

    private String transaction;

    private Optional<Boolean> useCdpSponsor = Optional.empty();

    private Optional<String> walletSecretId = Optional.empty();

    private Optional<String> projectId = Optional.empty();

    private Optional<String> developerAuth = Optional.empty();

    private Optional<String> idempotencyKey = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(SendSolanaTransactionWithEndUserAccountRequest other) {
      idempotencyKey(other.getIdempotencyKey());
      developerAuth(other.getDeveloperAuth());
      projectId(other.getProjectId());
      address(other.getAddress());
      network(other.getNetwork());
      walletSecretId(other.getWalletSecretId());
      transaction(other.getTransaction());
      useCdpSponsor(other.getUseCdpSponsor());
      return this;
    }

    /**
     * <p>The base58 encoded address of the Solana account belonging to the end user.</p>
     * <p>The base58 encoded address of the Solana account belonging to the end user.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("address")
    public NetworkStage address(@NotNull String address) {
      this.address = Objects.requireNonNull(address, "address must not be null");
      return this;
    }

    /**
     * <p>The Solana network to send the transaction to.</p>
     * <p>The Solana network to send the transaction to.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("network")
    public TransactionStage network(
        @NotNull SendSolanaTransactionWithEndUserAccountRequestNetwork network) {
      this.network = Objects.requireNonNull(network, "network must not be null");
      return this;
    }

    /**
     * <p>The base64 encoded transaction to sign and send. This transaction can contain multiple instructions for native Solana batching.</p>
     * <p>The base64 encoded transaction to sign and send. This transaction can contain multiple instructions for native Solana batching.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("transaction")
    public _FinalStage transaction(@NotNull String transaction) {
      this.transaction = Objects.requireNonNull(transaction, "transaction must not be null");
      return this;
    }

    /**
     * <p>Whether transaction fees should be sponsored by CDP. When true, CDP sponsors the transaction fees on behalf of the end user. When false, the end user is responsible for paying the transaction fees.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage useCdpSponsor(Boolean useCdpSponsor) {
      this.useCdpSponsor = Optional.ofNullable(useCdpSponsor);
      return this;
    }

    /**
     * <p>Whether transaction fees should be sponsored by CDP. When true, CDP sponsors the transaction fees on behalf of the end user. When false, the end user is responsible for paying the transaction fees.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "useCdpSponsor",
        nulls = Nulls.SKIP
    )
    public _FinalStage useCdpSponsor(Optional<Boolean> useCdpSponsor) {
      this.useCdpSponsor = useCdpSponsor;
      return this;
    }

    /**
     * <p>Required when not using delegated signing. The ID of the Temporary Wallet Secret that was used to sign the X-Wallet-Auth Header.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage walletSecretId(String walletSecretId) {
      this.walletSecretId = Optional.ofNullable(walletSecretId);
      return this;
    }

    /**
     * <p>Required when not using delegated signing. The ID of the Temporary Wallet Secret that was used to sign the X-Wallet-Auth Header.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "walletSecretId",
        nulls = Nulls.SKIP
    )
    public _FinalStage walletSecretId(Optional<String> walletSecretId) {
      this.walletSecretId = walletSecretId;
      return this;
    }

    /**
     * <p>The ID of the CDP Project. Required for end users authenticated using custom auth (i.e. a non-CDP JWT provider).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage projectId(String projectId) {
      this.projectId = Optional.ofNullable(projectId);
      return this;
    }

    /**
     * <p>The ID of the CDP Project. Required for end users authenticated using custom auth (i.e. a non-CDP JWT provider).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "projectID",
        nulls = Nulls.SKIP
    )
    public _FinalStage projectId(Optional<String> projectId) {
      this.projectId = projectId;
      return this;
    }

    /**
     * <p>A JWT signed using your Wallet Secret, encoded in base64. Refer to the
     * <a href="https://docs.cdp.coinbase.com/api-reference/v2/authentication#2-generate-wallet-token">Generate Wallet Token</a>
     * section of our Authentication docs for more details on how to generate your Wallet Token.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage developerAuth(String developerAuth) {
      this.developerAuth = Optional.ofNullable(developerAuth);
      return this;
    }

    /**
     * <p>A JWT signed using your Wallet Secret, encoded in base64. Refer to the
     * <a href="https://docs.cdp.coinbase.com/api-reference/v2/authentication#2-generate-wallet-token">Generate Wallet Token</a>
     * section of our Authentication docs for more details on how to generate your Wallet Token.</p>
     */
    @java.lang.Override
    public _FinalStage developerAuth(Optional<String> developerAuth) {
      this.developerAuth = developerAuth;
      return this;
    }

    /**
     * <p>An optional string request header for making requests safely retryable.
     * When included, duplicate requests with the same key will return identical responses.
     * Refer to our <a href="https://docs.cdp.coinbase.com/api-reference/v2/idempotency">Idempotency docs</a> for more information on using idempotency keys.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage idempotencyKey(String idempotencyKey) {
      this.idempotencyKey = Optional.ofNullable(idempotencyKey);
      return this;
    }

    /**
     * <p>An optional string request header for making requests safely retryable.
     * When included, duplicate requests with the same key will return identical responses.
     * Refer to our <a href="https://docs.cdp.coinbase.com/api-reference/v2/idempotency">Idempotency docs</a> for more information on using idempotency keys.</p>
     */
    @java.lang.Override
    public _FinalStage idempotencyKey(Optional<String> idempotencyKey) {
      this.idempotencyKey = idempotencyKey;
      return this;
    }

    @java.lang.Override
    public SendSolanaTransactionWithEndUserAccountRequest build() {
      return new SendSolanaTransactionWithEndUserAccountRequest(idempotencyKey, developerAuth, projectId, address, network, walletSecretId, transaction, useCdpSponsor, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
