/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.resources.enduseraccountmanagement.requests;

import com.coinbase.cdp.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AddEndUserEvmSmartAccountRequest.Builder.class
)
public final class AddEndUserEvmSmartAccountRequest {
  private final Optional<String> idempotencyKey;

  private final Optional<Boolean> enableSpendPermissions;

  private final Map<String, Object> additionalProperties;

  private AddEndUserEvmSmartAccountRequest(Optional<String> idempotencyKey,
      Optional<Boolean> enableSpendPermissions, Map<String, Object> additionalProperties) {
    this.idempotencyKey = idempotencyKey;
    this.enableSpendPermissions = enableSpendPermissions;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return An optional string request header for making requests safely retryable.
   * When included, duplicate requests with the same key will return identical responses.
   * Refer to our <a href="https://docs.cdp.coinbase.com/api-reference/v2/idempotency">Idempotency docs</a> for more information on using idempotency keys.
   */
  @JsonIgnore
  public Optional<String> getIdempotencyKey() {
    return idempotencyKey;
  }

  /**
   * @return If true, enables spend permissions for the EVM smart account.
   */
  @JsonProperty("enableSpendPermissions")
  public Optional<Boolean> getEnableSpendPermissions() {
    return enableSpendPermissions;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AddEndUserEvmSmartAccountRequest && equalTo((AddEndUserEvmSmartAccountRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AddEndUserEvmSmartAccountRequest other) {
    return idempotencyKey.equals(other.idempotencyKey) && enableSpendPermissions.equals(other.enableSpendPermissions);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.idempotencyKey, this.enableSpendPermissions);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> idempotencyKey = Optional.empty();

    private Optional<Boolean> enableSpendPermissions = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(AddEndUserEvmSmartAccountRequest other) {
      idempotencyKey(other.getIdempotencyKey());
      enableSpendPermissions(other.getEnableSpendPermissions());
      return this;
    }

    /**
     * <p>An optional string request header for making requests safely retryable.
     * When included, duplicate requests with the same key will return identical responses.
     * Refer to our <a href="https://docs.cdp.coinbase.com/api-reference/v2/idempotency">Idempotency docs</a> for more information on using idempotency keys.</p>
     */
    public Builder idempotencyKey(Optional<String> idempotencyKey) {
      this.idempotencyKey = idempotencyKey;
      return this;
    }

    public Builder idempotencyKey(String idempotencyKey) {
      this.idempotencyKey = Optional.ofNullable(idempotencyKey);
      return this;
    }

    /**
     * <p>If true, enables spend permissions for the EVM smart account.</p>
     */
    @JsonSetter(
        value = "enableSpendPermissions",
        nulls = Nulls.SKIP
    )
    public Builder enableSpendPermissions(Optional<Boolean> enableSpendPermissions) {
      this.enableSpendPermissions = enableSpendPermissions;
      return this;
    }

    public Builder enableSpendPermissions(Boolean enableSpendPermissions) {
      this.enableSpendPermissions = Optional.ofNullable(enableSpendPermissions);
      return this;
    }

    public AddEndUserEvmSmartAccountRequest build() {
      return new AddEndUserEvmSmartAccountRequest(idempotencyKey, enableSpendPermissions, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
