"""
Core CDP x402 facilitator, Bazaar, payment client, resource server,
wallet adapters, and spend controls.
"""

from cdp.openapi_client.models import (
    X402DiscoveryMerchantResponse,
    X402DiscoveryResource,
    X402DiscoveryResourcesResponse,
    X402ResourceQuality,
    X402SearchResourcesResponse,
)

from cdp.x402.core.balance_check import InsufficientFundsError, create_balance_check_hook
from cdp.x402.core.bazaar import (
    CDPBazaarClient,
    ListDiscoveryResourcesParams,
    MerchantResourcesParams,
    SearchDiscoveryResourcesParams,
    create_cdp_bazaar_client,
)
from cdp.x402.core.client import (
    CDPx402Client,
    CDPx402ClientConfig,
    CDPx402ClientResult,
    create_cdp_x402_client,
)
from cdp.x402.core.constants import (
    ARBITRUM_CAIP2,
    BASE_MAINNET_CAIP2,
    BASE_SEPOLIA_CAIP2,
    CDP_DEFAULT_NETWORKS,
    CDP_USDC_ADDRESSES,
    POLYGON_CAIP2,
    SOLANA_DEVNET_CAIP2,
    SOLANA_MAINNET_CAIP2,
    USDC_ADDRESS_ARBITRUM,
    USDC_ADDRESS_BASE_MAINNET,
    USDC_ADDRESS_BASE_SEPOLIA,
    USDC_ADDRESS_POLYGON,
    USDC_ADDRESS_SOLANA_DEVNET,
    USDC_ADDRESS_SOLANA_MAINNET,
    USDC_ADDRESS_WORLD,
    USDC_ADDRESS_WORLD_SEPOLIA,
    WORLD_CAIP2,
    WORLD_SEPOLIA_CAIP2,
)
from cdp.x402.core.credentials import resolve_credentials
from cdp.x402.core.extensions import (
    CDP_EXTENSION_BAZAAR,
    CDP_EXTENSION_GAS_SPONSORING_EIP2612,
    CDP_EXTENSION_GAS_SPONSORING_ERC20_APPROVAL,
    CDP_SUPPORTED_EXTENSIONS,
    CDPExtensions,
    build_bazaar_declaration,
    get_cdp_extension_registrations,
)
from cdp.x402.core.facilitator import (
    create_cdp_facilitator_client,
    create_cdp_facilitator_client_sync,
)
from cdp.x402.core.guardrails import (
    DEFAULT_APPROACHING_LIMIT_THRESHOLDS,
    DEFAULT_MAX_LEDGER_ENTRIES,
    Address,
    Amount,
    Asset,
    Duration,
    RecordSpendInput,
    ResolvedSpendControls,
    SpendControlError,
    SpendControlErrorCode,
    SpendControlErrorCodes,
    SpendControlErrorDetails,
    SpendControls,
    SpendControlsRegistry,
    SpendLedgerEntry,
    SpendStore,
    SpendTracker,
    TotalSpendQuery,
    apply_spend_controls,
    cdp_x402_http_adapter,
    cdp_x402_httpx_transport,
    get_spend_controls_registry,
    normalize_asset,
    normalize_network,
    normalize_payee,
    parse_amount,
    parse_duration,
)
from cdp.x402.core.resource_server import (
    CDP_SERVER_DEFAULT_EVM_NETWORKS,
    CDP_SERVER_DEFAULT_NETWORKS,
    CDP_SERVER_DEFAULT_SVM_NETWORKS,
    CDPPaymentScheme,
    CDPResourceServer,
    CDPResourceServerConfig,
    CDPRouteConfig,
    CDPSchemeRegistration,
    create_cdp_resource_server,
    get_cdp_default_schemes,
)
from cdp.x402.core.wallets import (
    WalletConfig,
    from_cdp_evm_account,
    from_cdp_smart_wallet,
    resolve_network_from_chain_id,
    resolve_wallet_config,
)
from cdp.x402.core.wallets.provision import (
    CDPAccountProvisionResult,
    provision_cdp_accounts,
)

__all__ = [
    # Facilitator
    "create_cdp_facilitator_client",
    "create_cdp_facilitator_client_sync",
    # Bazaar client
    "create_cdp_bazaar_client",
    "CDPBazaarClient",
    "ListDiscoveryResourcesParams",
    "SearchDiscoveryResourcesParams",
    "MerchantResourcesParams",
    "X402DiscoveryResourcesResponse",
    "X402SearchResourcesResponse",
    "X402DiscoveryMerchantResponse",
    "X402DiscoveryResource",
    "X402ResourceQuality",
    # Payment client
    "CDPx402Client",
    "CDPx402ClientResult",
    "create_cdp_x402_client",
    "InsufficientFundsError",
    "create_balance_check_hook",
    # Configuration
    "CDPx402ClientConfig",
    "resolve_credentials",
    "WalletConfig",
    "resolve_wallet_config",
    # Wallet adapters
    "from_cdp_evm_account",
    "from_cdp_smart_wallet",
    "resolve_network_from_chain_id",
    # Account provisioning
    "CDPAccountProvisionResult",
    "provision_cdp_accounts",
    # Resource server
    "CDPResourceServer",
    "CDPResourceServerConfig",
    "CDPRouteConfig",
    "CDPPaymentScheme",
    "CDPSchemeRegistration",
    "create_cdp_resource_server",
    "get_cdp_default_schemes",
    "CDP_SERVER_DEFAULT_EVM_NETWORKS",
    "CDP_SERVER_DEFAULT_NETWORKS",
    "CDP_SERVER_DEFAULT_SVM_NETWORKS",
    # CDP supported networks
    "CDP_DEFAULT_NETWORKS",
    # CAIP-2 network identifiers
    "ARBITRUM_CAIP2",
    "BASE_MAINNET_CAIP2",
    "BASE_SEPOLIA_CAIP2",
    "POLYGON_CAIP2",
    "SOLANA_DEVNET_CAIP2",
    "SOLANA_MAINNET_CAIP2",
    "WORLD_CAIP2",
    "WORLD_SEPOLIA_CAIP2",
    # USDC addresses
    "CDP_USDC_ADDRESSES",
    "USDC_ADDRESS_ARBITRUM",
    "USDC_ADDRESS_BASE_MAINNET",
    "USDC_ADDRESS_BASE_SEPOLIA",
    "USDC_ADDRESS_POLYGON",
    "USDC_ADDRESS_SOLANA_DEVNET",
    "USDC_ADDRESS_SOLANA_MAINNET",
    "USDC_ADDRESS_WORLD",
    "USDC_ADDRESS_WORLD_SEPOLIA",
    # Extensions
    "CDP_EXTENSION_BAZAAR",
    "CDP_EXTENSION_GAS_SPONSORING_EIP2612",
    "CDP_EXTENSION_GAS_SPONSORING_ERC20_APPROVAL",
    "CDP_SUPPORTED_EXTENSIONS",
    "CDPExtensions",
    "build_bazaar_declaration",
    "get_cdp_extension_registrations",
    # Guardrails
    "apply_spend_controls",
    "SpendControls",
    "SpendControlError",
    "SpendControlErrorCode",
    "SpendControlErrorCodes",
    "SpendControlErrorDetails",
    "SpendTracker",
    "DEFAULT_MAX_LEDGER_ENTRIES",
    "RecordSpendInput",
    "TotalSpendQuery",
    "SpendStore",
    "SpendLedgerEntry",
    "Amount",
    "Duration",
    "Asset",
    "Address",
    "parse_amount",
    "parse_duration",
    "normalize_asset",
    "normalize_network",
    "normalize_payee",
    "ResolvedSpendControls",
    "DEFAULT_APPROACHING_LIMIT_THRESHOLDS",
    "SpendControlsRegistry",
    "get_spend_controls_registry",
    "cdp_x402_httpx_transport",
    "cdp_x402_http_adapter",
]
