"""CDP x402 constants - network and address values sourced from cdp.networks."""

from cdp.networks import (
    ARBITRUM_CAIP2,
    BASE_MAINNET_CAIP2,
    BASE_SEPOLIA_CAIP2,
    CDP_DEFAULT_NETWORKS,
    CDP_EVM_RPC_URLS,
    CDP_USDC_ADDRESSES,
    CHAIN_ID_TO_CDP_NETWORK,
    POLYGON_CAIP2,
    SOLANA_DEVNET_CAIP2,
    SOLANA_MAINNET_CAIP2,
    USDC_ADDRESS_ARBITRUM,
    USDC_ADDRESS_BASE_MAINNET,
    USDC_ADDRESS_BASE_SEPOLIA,
    USDC_ADDRESS_POLYGON,
    USDC_ADDRESS_SOLANA_DEVNET,
    USDC_ADDRESS_SOLANA_MAINNET,
    USDC_ADDRESS_WORLD,
    USDC_ADDRESS_WORLD_SEPOLIA,
    WORLD_CAIP2,
    WORLD_SEPOLIA_CAIP2,
)

CDP_FACILITATOR_URL = "https://api.cdp.coinbase.com/platform/v2/x402"
CDP_API_BASE_URL = "https://api.cdp.coinbase.com/platform"
SDK_SOURCE = "cdp-x402"
SDK_VERSION = "0.0.1"
SDK_LANGUAGE = "python"
SDK_CORRELATION_CONTEXT = (
    f"sdkLanguage={SDK_LANGUAGE},source={SDK_SOURCE},sourceVersion={SDK_VERSION}"
)
CDP_API_HOST = "api.cdp.coinbase.com"
FACILITATOR_PATHS = {
    "verify": "/verify",
    "settle": "/settle",
    "supported": "/supported",
}

__all__ = [
    "CDP_FACILITATOR_URL",
    "CDP_API_BASE_URL",
    "SDK_SOURCE",
    "SDK_VERSION",
    "SDK_LANGUAGE",
    "SDK_CORRELATION_CONTEXT",
    "CDP_API_HOST",
    "FACILITATOR_PATHS",
    "ARBITRUM_CAIP2",
    "BASE_MAINNET_CAIP2",
    "BASE_SEPOLIA_CAIP2",
    "POLYGON_CAIP2",
    "WORLD_CAIP2",
    "WORLD_SEPOLIA_CAIP2",
    "SOLANA_MAINNET_CAIP2",
    "SOLANA_DEVNET_CAIP2",
    "CDP_DEFAULT_NETWORKS",
    "USDC_ADDRESS_ARBITRUM",
    "USDC_ADDRESS_BASE_MAINNET",
    "USDC_ADDRESS_BASE_SEPOLIA",
    "USDC_ADDRESS_POLYGON",
    "USDC_ADDRESS_WORLD",
    "USDC_ADDRESS_WORLD_SEPOLIA",
    "USDC_ADDRESS_SOLANA_MAINNET",
    "USDC_ADDRESS_SOLANA_DEVNET",
    "CDP_USDC_ADDRESSES",
    "CDP_EVM_RPC_URLS",
    "CHAIN_ID_TO_CDP_NETWORK",
]
