# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cdp.openapi_client.models.evm_eip7702_delegation_network import EvmEip7702DelegationNetwork
from typing import Optional, Set
from typing_extensions import Self

class EvmEip7702DelegationStatus(BaseModel):
    """
    The EIP-7702 delegation status for an EVM account.
    """ # noqa: E501
    status: StrictStr = Field(description="The current delegation state of the account. CURRENT means the account is fully delegated and initialized. NOT_DELEGATED means the account has no active EIP-7702 delegation. WRONG_PROXY means the account is delegated to an unexpected proxy contract. NOT_INITIALIZED means the account is delegated to the correct proxy but has not been initialized.")
    delegate_address: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="The address the account has delegated to, if any. Only present when the account has an active delegation.", alias="delegateAddress")
    network: EvmEip7702DelegationNetwork
    __properties: ClassVar[List[str]] = ["status", "delegateAddress", "network"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['CURRENT', 'NOT_DELEGATED', 'WRONG_PROXY', 'NOT_INITIALIZED']):
            raise ValueError("must be one of enum values ('CURRENT', 'NOT_DELEGATED', 'WRONG_PROXY', 'NOT_INITIALIZED')")
        return value

    @field_validator('delegate_address')
    def delegate_address_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^0x[0-9a-fA-F]{40}$", value):
            raise ValueError(r"must validate the regular expression /^0x[0-9a-fA-F]{40}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EvmEip7702DelegationStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EvmEip7702DelegationStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "delegateAddress": obj.get("delegateAddress"),
            "network": obj.get("network")
        })
        return _obj


