# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cdp.openapi_client.models.date_of_birth_lenient import DateOfBirthLenient
from cdp.openapi_client.models.individual_input_address import IndividualInputAddress
from typing import Optional, Set
from typing_extensions import Self

class IndividualInput(BaseModel):
    """
    Individual customer data submitted on create / update requests. Fields are organized by the capabilities they unlock; not all are required for all customers (the requirements depend on which capabilities are requested). Read responses return the narrower `Individual` object (only `firstName`, `lastName`, and `email`), not this full request shape. 
    """ # noqa: E501
    first_name: Optional[StrictStr] = Field(default=None, description="First name (given name).", alias="firstName")
    last_name: Optional[StrictStr] = Field(default=None, description="Last name (family name/surname).", alias="lastName")
    address: Optional[IndividualInputAddress] = None
    ssn_last4: Optional[Annotated[str, Field(min_length=4, strict=True, max_length=4)]] = Field(default=None, description="Last 4 digits of the Social Security Number (US only). Used for identity verification. ", alias="ssnLast4")
    date_of_birth: Optional[DateOfBirthLenient] = Field(default=None, description="Date of birth.", alias="dateOfBirth")
    full_ssn: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Full Social Security Number (US only). ", alias="fullSsn")
    citizenship: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=2)]] = Field(default=None, description="ISO 3166-1 alpha-2 country code representing the customer's citizenship. ")
    email: Optional[Annotated[str, Field(strict=True, max_length=254)]] = Field(default=None, description="Email address for the customer.")
    phone_number: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format.", alias="phoneNumber")
    purpose_of_account: Optional[StrictStr] = Field(default=None, description="Primary purpose for using Coinbase services. ", alias="purposeOfAccount")
    source_of_funds: Optional[StrictStr] = Field(default=None, description="Primary source of funds for the account. ", alias="sourceOfFunds")
    employment_status: Optional[StrictStr] = Field(default=None, description="Current employment status. ", alias="employmentStatus")
    occupation: Optional[StrictStr] = Field(default=None, description="Industry or occupation. ")
    expected_volume: Optional[StrictStr] = Field(default=None, description="Expected annual volume of activity on the account, expressed as a dollar range. Use the dollar-honest ids below:  - `under_1k`: $0 – $1,000 - `1k_to_10k`: $1,000 – $10,000 - `10k_to_100k`: $10,000 – $100,000 - `100k_to_250k`: $100,000 – $250,000 - `250k_to_750k`: $250,000 – $750,000 - `750k_to_1_5m`: $750,000 – $1.5M - `1_5m_plus`: $1.5M+ ", alias="expectedVolume")
    __properties: ClassVar[List[str]] = ["firstName", "lastName", "address", "ssnLast4", "dateOfBirth", "fullSsn", "citizenship", "email", "phoneNumber", "purposeOfAccount", "sourceOfFunds", "employmentStatus", "occupation", "expectedVolume"]

    @field_validator('ssn_last4')
    def ssn_last4_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[0-9]{4}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}$/")
        return value

    @field_validator('full_ssn')
    def full_ssn_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([0-9]{3}-[0-9]{2}-[0-9]{4}|\*\*\*-\*\*-[0-9]{4})$", value):
            raise ValueError(r"must validate the regular expression /^([0-9]{3}-[0-9]{2}-[0-9]{4}|\*\*\*-\*\*-[0-9]{4})$/")
        return value

    @field_validator('citizenship')
    def citizenship_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Z]{2}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z]{2}$/")
        return value

    @field_validator('email')
    def email_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z0-9.!#$%&\'*+\/=?^_`{|}\/-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}\/-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/")
        return value

    @field_validator('phone_number')
    def phone_number_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\+[1-9]\d{1,14}$", value):
            raise ValueError(r"must validate the regular expression /^\+[1-9]\d{1,14}$/")
        return value

    @field_validator('purpose_of_account')
    def purpose_of_account_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['investing', 'long_term_investment', 'short_term_investment', 'trading', 'trading_on_coinbase', 'trading_on_other_exchanges', 'day_trading', 'arbitrage_trading', 'online_purchases', 'online_payments', 'payments_or_gifts', 'payments_to_friends', 'transfer_crypto', 'investing_on_other_exchanges', 'business', 'other']):
            raise ValueError("must be one of enum values ('investing', 'long_term_investment', 'short_term_investment', 'trading', 'trading_on_coinbase', 'trading_on_other_exchanges', 'day_trading', 'arbitrage_trading', 'online_purchases', 'online_payments', 'payments_or_gifts', 'payments_to_friends', 'transfer_crypto', 'investing_on_other_exchanges', 'business', 'other')")
        return value

    @field_validator('source_of_funds')
    def source_of_funds_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['salary', 'employment_business_income', 'investments', 'savings', 'pension', 'business_earnings', 'crypto_assets', 'inheritance', 'sale_of_assets', 'sale_of_company_shares_or_dividends', 'sale_of_property', 'sale_of_other_assets', 'credit_or_loan', 'government_benefits_or_credits', 'legal_settlement', 'family_or_third_party', 'lottery_or_gambling', 'crypto_mining', 'other']):
            raise ValueError("must be one of enum values ('salary', 'employment_business_income', 'investments', 'savings', 'pension', 'business_earnings', 'crypto_assets', 'inheritance', 'sale_of_assets', 'sale_of_company_shares_or_dividends', 'sale_of_property', 'sale_of_other_assets', 'credit_or_loan', 'government_benefits_or_credits', 'legal_settlement', 'family_or_third_party', 'lottery_or_gambling', 'crypto_mining', 'other')")
        return value

    @field_validator('employment_status')
    def employment_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['employed_fulltime', 'employed_parttime', 'self_employed', 'employed_government_official', 'employed_company_officer_or_board_member', 'employed_crypto_related_business', 'personal_trader_or_angel_investor', 'crypto_miner', 'student', 'retired', 'homemaker', 'unemployed', 'dependent']):
            raise ValueError("must be one of enum values ('employed_fulltime', 'employed_parttime', 'self_employed', 'employed_government_official', 'employed_company_officer_or_board_member', 'employed_crypto_related_business', 'personal_trader_or_angel_investor', 'crypto_miner', 'student', 'retired', 'homemaker', 'unemployed', 'dependent')")
        return value

    @field_validator('occupation')
    def occupation_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['agriculture', 'arts_and_media', 'casinos_and_gaming', 'construction', 'cryptocurrency', 'defense', 'education', 'energy_oil_and_gas', 'energy_other', 'entertainment', 'finance', 'financial_services_non_crypto', 'fintech_non_crypto_software_development', 'fintech_non_crypto_internet_only_financial_institution', 'fintech_non_crypto_other', 'food_and_hospitality', 'government', 'health_and_fitness', 'healthcare', 'healthcare_other', 'healthcare_pharmaceuticals', 'mining', 'mining_crypto', 'non_profit_and_charity', 'pharma_industry', 'politics', 'professional_services', 'property_and_construction_building_work', 'property_and_construction_commercial_and_management', 'property_and_construction_design', 'real_estate', 'retail_fashion', 'retail_food_and_beverage', 'retail_jewelry_and_antiques', 'retail_other', 'retail_pharmacy', 'technology', 'technology_and_it', 'transportation', 'all_other_industries_and_services', 'dependent_student_unemployed', 'other']):
            raise ValueError("must be one of enum values ('agriculture', 'arts_and_media', 'casinos_and_gaming', 'construction', 'cryptocurrency', 'defense', 'education', 'energy_oil_and_gas', 'energy_other', 'entertainment', 'finance', 'financial_services_non_crypto', 'fintech_non_crypto_software_development', 'fintech_non_crypto_internet_only_financial_institution', 'fintech_non_crypto_other', 'food_and_hospitality', 'government', 'health_and_fitness', 'healthcare', 'healthcare_other', 'healthcare_pharmaceuticals', 'mining', 'mining_crypto', 'non_profit_and_charity', 'pharma_industry', 'politics', 'professional_services', 'property_and_construction_building_work', 'property_and_construction_commercial_and_management', 'property_and_construction_design', 'real_estate', 'retail_fashion', 'retail_food_and_beverage', 'retail_jewelry_and_antiques', 'retail_other', 'retail_pharmacy', 'technology', 'technology_and_it', 'transportation', 'all_other_industries_and_services', 'dependent_student_unemployed', 'other')")
        return value

    @field_validator('expected_volume')
    def expected_volume_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['under_1k', '1k_to_10k', '10k_to_100k', '100k_to_250k', '250k_to_750k', '750k_to_1_5m', '1_5m_plus']):
            raise ValueError("must be one of enum values ('under_1k', '1k_to_10k', '10k_to_100k', '100k_to_250k', '250k_to_750k', '750k_to_1_5m', '1_5m_plus')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IndividualInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of date_of_birth
        if self.date_of_birth:
            _dict['dateOfBirth'] = self.date_of_birth.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IndividualInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "address": IndividualInputAddress.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "ssnLast4": obj.get("ssnLast4"),
            "dateOfBirth": DateOfBirthLenient.from_dict(obj["dateOfBirth"]) if obj.get("dateOfBirth") is not None else None,
            "fullSsn": obj.get("fullSsn"),
            "citizenship": obj.get("citizenship"),
            "email": obj.get("email"),
            "phoneNumber": obj.get("phoneNumber"),
            "purposeOfAccount": obj.get("purposeOfAccount"),
            "sourceOfFunds": obj.get("sourceOfFunds"),
            "employmentStatus": obj.get("employmentStatus"),
            "occupation": obj.get("occupation"),
            "expectedVolume": obj.get("expectedVolume")
        })
        return _obj


