# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cdp.openapi_client.models.money_amount import MoneyAmount
from typing import Optional, Set
from typing_extensions import Self

class OnrampTransactionPayload(BaseModel):
    """
    Webhook payload for standard onramp transactions (guest checkout and authed flow). Serialized from the OnrampTransaction proto via protojson with eventType appended.
    """ # noqa: E501
    event_type: StrictStr = Field(description="The webhook event type.", alias="eventType")
    transaction_id: StrictStr = Field(description="Unique transaction identifier.", alias="transactionId")
    status: StrictStr = Field(description="Current status of the transaction.")
    purchase_currency: Optional[StrictStr] = Field(default=None, description="The crypto currency purchased (e.g., \"USDC\", \"ETH\").", alias="purchaseCurrency")
    purchase_network: Optional[StrictStr] = Field(default=None, description="The blockchain network for the purchase (e.g., \"ethereum\", \"base\").", alias="purchaseNetwork")
    purchase_amount: Optional[MoneyAmount] = Field(default=None, alias="purchaseAmount")
    payment_total: Optional[MoneyAmount] = Field(default=None, alias="paymentTotal")
    payment_total_usd: Optional[MoneyAmount] = Field(default=None, alias="paymentTotalUsd")
    payment_subtotal: Optional[MoneyAmount] = Field(default=None, alias="paymentSubtotal")
    coinbase_fee: Optional[MoneyAmount] = Field(default=None, alias="coinbaseFee")
    network_fee: Optional[MoneyAmount] = Field(default=None, alias="networkFee")
    exchange_rate: Optional[MoneyAmount] = Field(default=None, alias="exchangeRate")
    tx_hash: Optional[StrictStr] = Field(default=None, description="The onchain transaction hash of the send (0x-prefixed for EVM).", alias="txHash")
    created_at: Optional[datetime] = Field(default=None, description="When the transaction was created.", alias="createdAt")
    completed_at: Optional[datetime] = Field(default=None, description="When the transaction completed (uses send_started_at for early success).", alias="completedAt")
    country: Optional[StrictStr] = Field(default=None, description="The user's country code.")
    user_id: Optional[StrictStr] = Field(default=None, description="Hashed user identifier (entity hash for guest, user ID for authed).", alias="userId")
    payment_method: Optional[StrictStr] = Field(default=None, description="The payment method used.", alias="paymentMethod")
    wallet_address: Optional[StrictStr] = Field(default=None, description="The destination wallet address.", alias="walletAddress")
    type: Optional[StrictStr] = Field(default=None, description="The type of onramp transaction.")
    user_type: Optional[StrictStr] = Field(default=None, description="Whether the user is authed or guest.", alias="userType")
    partner_user_ref: Optional[StrictStr] = Field(default=None, description="The partnerUserId provided when initializing the onramp session.", alias="partnerUserRef")
    contract_address: Optional[StrictStr] = Field(default=None, description="The token contract address (populated when asset metadata is available).", alias="contractAddress")
    failure_reason: Optional[StrictStr] = Field(default=None, description="The reason for failure (if applicable).", alias="failureReason")
    end_partner_name: Optional[StrictStr] = Field(default=None, description="The name of the developer app.", alias="endPartnerName")
    error_code: Optional[StrictStr] = Field(default=None, description="Error code for the transaction failure (if applicable).", alias="errorCode")
    __properties: ClassVar[List[str]] = ["eventType", "transactionId", "status", "purchaseCurrency", "purchaseNetwork", "purchaseAmount", "paymentTotal", "paymentTotalUsd", "paymentSubtotal", "coinbaseFee", "networkFee", "exchangeRate", "txHash", "createdAt", "completedAt", "country", "userId", "paymentMethod", "walletAddress", "type", "userType", "partnerUserRef", "contractAddress", "failureReason", "endPartnerName", "errorCode"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ONRAMP_TRANSACTION_STATUS_UNSPECIFIED', 'ONRAMP_TRANSACTION_STATUS_CREATED', 'ONRAMP_TRANSACTION_STATUS_IN_PROGRESS', 'ONRAMP_TRANSACTION_STATUS_SUCCESS', 'ONRAMP_TRANSACTION_STATUS_FAILED', 'ONRAMP_TRANSACTION_STATUS_AWAITING_AUTH', 'ONRAMP_TRANSACTION_STATUS_AWAITING_PAYMENT']):
            raise ValueError("must be one of enum values ('ONRAMP_TRANSACTION_STATUS_UNSPECIFIED', 'ONRAMP_TRANSACTION_STATUS_CREATED', 'ONRAMP_TRANSACTION_STATUS_IN_PROGRESS', 'ONRAMP_TRANSACTION_STATUS_SUCCESS', 'ONRAMP_TRANSACTION_STATUS_FAILED', 'ONRAMP_TRANSACTION_STATUS_AWAITING_AUTH', 'ONRAMP_TRANSACTION_STATUS_AWAITING_PAYMENT')")
        return value

    @field_validator('payment_method')
    def payment_method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['UNSPECIFIED', 'CARD', 'ACH_BANK_ACCOUNT', 'APPLE_PAY', 'FIAT_WALLET', 'CRYPTO_ACCOUNT', 'GUEST_CHECKOUT_CARD', 'PAYPAL', 'RTP', 'GUEST_CHECKOUT_APPLE_PAY', 'GUEST_CHECKOUT_GOOGLE_PAY']):
            raise ValueError("must be one of enum values ('UNSPECIFIED', 'CARD', 'ACH_BANK_ACCOUNT', 'APPLE_PAY', 'FIAT_WALLET', 'CRYPTO_ACCOUNT', 'GUEST_CHECKOUT_CARD', 'PAYPAL', 'RTP', 'GUEST_CHECKOUT_APPLE_PAY', 'GUEST_CHECKOUT_GOOGLE_PAY')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ONRAMP_TRANSACTION_TYPE_UNSPECIFIED', 'ONRAMP_TRANSACTION_TYPE_BUY_AND_SEND', 'ONRAMP_TRANSACTION_TYPE_SEND']):
            raise ValueError("must be one of enum values ('ONRAMP_TRANSACTION_TYPE_UNSPECIFIED', 'ONRAMP_TRANSACTION_TYPE_BUY_AND_SEND', 'ONRAMP_TRANSACTION_TYPE_SEND')")
        return value

    @field_validator('user_type')
    def user_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['USER_TYPE_UNSPECIFIED', 'USER_TYPE_AUTHED', 'USER_TYPE_GUEST']):
            raise ValueError("must be one of enum values ('USER_TYPE_UNSPECIFIED', 'USER_TYPE_AUTHED', 'USER_TYPE_GUEST')")
        return value

    @field_validator('failure_reason')
    def failure_reason_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['FAILURE_REASON_UNSPECIFIED', 'FAILURE_REASON_BUY_FAILED', 'FAILURE_REASON_SEND_FAILED']):
            raise ValueError("must be one of enum values ('FAILURE_REASON_UNSPECIFIED', 'FAILURE_REASON_BUY_FAILED', 'FAILURE_REASON_SEND_FAILED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OnrampTransactionPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of purchase_amount
        if self.purchase_amount:
            _dict['purchaseAmount'] = self.purchase_amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payment_total
        if self.payment_total:
            _dict['paymentTotal'] = self.payment_total.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payment_total_usd
        if self.payment_total_usd:
            _dict['paymentTotalUsd'] = self.payment_total_usd.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payment_subtotal
        if self.payment_subtotal:
            _dict['paymentSubtotal'] = self.payment_subtotal.to_dict()
        # override the default output from pydantic by calling `to_dict()` of coinbase_fee
        if self.coinbase_fee:
            _dict['coinbaseFee'] = self.coinbase_fee.to_dict()
        # override the default output from pydantic by calling `to_dict()` of network_fee
        if self.network_fee:
            _dict['networkFee'] = self.network_fee.to_dict()
        # override the default output from pydantic by calling `to_dict()` of exchange_rate
        if self.exchange_rate:
            _dict['exchangeRate'] = self.exchange_rate.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OnrampTransactionPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "eventType": obj.get("eventType"),
            "transactionId": obj.get("transactionId"),
            "status": obj.get("status"),
            "purchaseCurrency": obj.get("purchaseCurrency"),
            "purchaseNetwork": obj.get("purchaseNetwork"),
            "purchaseAmount": MoneyAmount.from_dict(obj["purchaseAmount"]) if obj.get("purchaseAmount") is not None else None,
            "paymentTotal": MoneyAmount.from_dict(obj["paymentTotal"]) if obj.get("paymentTotal") is not None else None,
            "paymentTotalUsd": MoneyAmount.from_dict(obj["paymentTotalUsd"]) if obj.get("paymentTotalUsd") is not None else None,
            "paymentSubtotal": MoneyAmount.from_dict(obj["paymentSubtotal"]) if obj.get("paymentSubtotal") is not None else None,
            "coinbaseFee": MoneyAmount.from_dict(obj["coinbaseFee"]) if obj.get("coinbaseFee") is not None else None,
            "networkFee": MoneyAmount.from_dict(obj["networkFee"]) if obj.get("networkFee") is not None else None,
            "exchangeRate": MoneyAmount.from_dict(obj["exchangeRate"]) if obj.get("exchangeRate") is not None else None,
            "txHash": obj.get("txHash"),
            "createdAt": obj.get("createdAt"),
            "completedAt": obj.get("completedAt"),
            "country": obj.get("country"),
            "userId": obj.get("userId"),
            "paymentMethod": obj.get("paymentMethod"),
            "walletAddress": obj.get("walletAddress"),
            "type": obj.get("type"),
            "userType": obj.get("userType"),
            "partnerUserRef": obj.get("partnerUserRef"),
            "contractAddress": obj.get("contractAddress"),
            "failureReason": obj.get("failureReason"),
            "endPartnerName": obj.get("endPartnerName"),
            "errorCode": obj.get("errorCode")
        })
        return _obj


