# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from cdp.openapi_client.models.api_key_wallet_evm import APIKeyWalletEVM
from cdp.openapi_client.models.api_key_wallet_solana import APIKeyWalletSolana
from cdp.openapi_client.models.user_wallet_delegated_signing_evm import UserWalletDelegatedSigningEVM
from cdp.openapi_client.models.user_wallet_delegated_signing_solana import UserWalletDelegatedSigningSolana
from cdp.openapi_client.models.user_wallet_evm import UserWalletEVM
from cdp.openapi_client.models.user_wallet_solana import UserWalletSolana
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

WALLETTRANSACTIONCREATEDEVENT_ONE_OF_SCHEMAS = ["APIKeyWalletEVM", "APIKeyWalletSolana", "UserWalletDelegatedSigningEVM", "UserWalletDelegatedSigningSolana", "UserWalletEVM", "UserWalletSolana"]

class WalletTransactionCreatedEvent(BaseModel):
    """
    Delivered when a transaction is created. The payload is one of six variants: API Key Wallet, User Wallet, or User Wallet (Delegated Signing), each delivered as an EVM or Solana variant.
    """
    # data type: APIKeyWalletEVM
    oneof_schema_1_validator: Optional[APIKeyWalletEVM] = None
    # data type: APIKeyWalletSolana
    oneof_schema_2_validator: Optional[APIKeyWalletSolana] = None
    # data type: UserWalletEVM
    oneof_schema_3_validator: Optional[UserWalletEVM] = None
    # data type: UserWalletSolana
    oneof_schema_4_validator: Optional[UserWalletSolana] = None
    # data type: UserWalletDelegatedSigningEVM
    oneof_schema_5_validator: Optional[UserWalletDelegatedSigningEVM] = None
    # data type: UserWalletDelegatedSigningSolana
    oneof_schema_6_validator: Optional[UserWalletDelegatedSigningSolana] = None
    actual_instance: Optional[Union[APIKeyWalletEVM, APIKeyWalletSolana, UserWalletDelegatedSigningEVM, UserWalletDelegatedSigningSolana, UserWalletEVM, UserWalletSolana]] = None
    one_of_schemas: Set[str] = { "APIKeyWalletEVM", "APIKeyWalletSolana", "UserWalletDelegatedSigningEVM", "UserWalletDelegatedSigningSolana", "UserWalletEVM", "UserWalletSolana" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = WalletTransactionCreatedEvent.model_construct()
        error_messages = []
        match = 0
        # validate data type: APIKeyWalletEVM
        if not isinstance(v, APIKeyWalletEVM):
            error_messages.append(f"Error! Input type `{type(v)}` is not `APIKeyWalletEVM`")
        else:
            match += 1
        # validate data type: APIKeyWalletSolana
        if not isinstance(v, APIKeyWalletSolana):
            error_messages.append(f"Error! Input type `{type(v)}` is not `APIKeyWalletSolana`")
        else:
            match += 1
        # validate data type: UserWalletEVM
        if not isinstance(v, UserWalletEVM):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserWalletEVM`")
        else:
            match += 1
        # validate data type: UserWalletSolana
        if not isinstance(v, UserWalletSolana):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserWalletSolana`")
        else:
            match += 1
        # validate data type: UserWalletDelegatedSigningEVM
        if not isinstance(v, UserWalletDelegatedSigningEVM):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserWalletDelegatedSigningEVM`")
        else:
            match += 1
        # validate data type: UserWalletDelegatedSigningSolana
        if not isinstance(v, UserWalletDelegatedSigningSolana):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserWalletDelegatedSigningSolana`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in WalletTransactionCreatedEvent with oneOf schemas: APIKeyWalletEVM, APIKeyWalletSolana, UserWalletDelegatedSigningEVM, UserWalletDelegatedSigningSolana, UserWalletEVM, UserWalletSolana. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in WalletTransactionCreatedEvent with oneOf schemas: APIKeyWalletEVM, APIKeyWalletSolana, UserWalletDelegatedSigningEVM, UserWalletDelegatedSigningSolana, UserWalletEVM, UserWalletSolana. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into APIKeyWalletEVM
        try:
            instance.actual_instance = APIKeyWalletEVM.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into APIKeyWalletSolana
        try:
            instance.actual_instance = APIKeyWalletSolana.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserWalletEVM
        try:
            instance.actual_instance = UserWalletEVM.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserWalletSolana
        try:
            instance.actual_instance = UserWalletSolana.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserWalletDelegatedSigningEVM
        try:
            instance.actual_instance = UserWalletDelegatedSigningEVM.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserWalletDelegatedSigningSolana
        try:
            instance.actual_instance = UserWalletDelegatedSigningSolana.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into WalletTransactionCreatedEvent with oneOf schemas: APIKeyWalletEVM, APIKeyWalletSolana, UserWalletDelegatedSigningEVM, UserWalletDelegatedSigningSolana, UserWalletEVM, UserWalletSolana. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into WalletTransactionCreatedEvent with oneOf schemas: APIKeyWalletEVM, APIKeyWalletSolana, UserWalletDelegatedSigningEVM, UserWalletDelegatedSigningSolana, UserWalletEVM, UserWalletSolana. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], APIKeyWalletEVM, APIKeyWalletSolana, UserWalletDelegatedSigningEVM, UserWalletDelegatedSigningSolana, UserWalletEVM, UserWalletSolana]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


