/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.resources.depositdestinations;

import com.coinbase.cdp.core.ClientOptions;
import com.coinbase.cdp.core.RequestOptions;
import com.coinbase.cdp.resources.depositdestinations.requests.CreateDepositDestinationBody;
import com.coinbase.cdp.resources.depositdestinations.requests.GetDepositDestinationByIdRequest;
import com.coinbase.cdp.resources.depositdestinations.requests.ListDepositDestinationsRequest;
import com.coinbase.cdp.resources.depositdestinations.types.ListDepositDestinationsResponse;
import com.coinbase.cdp.types.CreateDepositDestinationRequest;
import com.coinbase.cdp.types.DepositDestination;
import com.coinbase.cdp.types.DepositDestinationId;
import java.util.concurrent.CompletableFuture;

public class AsyncDepositDestinationsClient {
  protected final ClientOptions clientOptions;

  private final AsyncWithRawResponseDepositDestinationsClient rawClient;

  public AsyncDepositDestinationsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncWithRawResponseDepositDestinationsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncWithRawResponseDepositDestinationsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * List deposit destinations. You can optionally filter the results by type, account ID, network, or cryptocurrency address. Results are sorted by creation date in descending order (newest first).
   */
  public CompletableFuture<ListDepositDestinationsResponse> listDepositDestinations() {
    return this.rawClient.listDepositDestinations().thenApply(response -> response.body());
  }

  /**
   * List deposit destinations. You can optionally filter the results by type, account ID, network, or cryptocurrency address. Results are sorted by creation date in descending order (newest first).
   */
  public CompletableFuture<ListDepositDestinationsResponse> listDepositDestinations(
      RequestOptions requestOptions) {
    return this.rawClient.listDepositDestinations(requestOptions).thenApply(response -> response.body());
  }

  /**
   * List deposit destinations. You can optionally filter the results by type, account ID, network, or cryptocurrency address. Results are sorted by creation date in descending order (newest first).
   */
  public CompletableFuture<ListDepositDestinationsResponse> listDepositDestinations(
      ListDepositDestinationsRequest request) {
    return this.rawClient.listDepositDestinations(request).thenApply(response -> response.body());
  }

  /**
   * List deposit destinations. You can optionally filter the results by type, account ID, network, or cryptocurrency address. Results are sorted by creation date in descending order (newest first).
   */
  public CompletableFuture<ListDepositDestinationsResponse> listDepositDestinations(
      ListDepositDestinationsRequest request, RequestOptions requestOptions) {
    return this.rawClient.listDepositDestinations(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Create a new deposit destination for an account. Two types are supported:
   * <ul>
   * <li>
   * <p><code>crypto</code> (public): provisions a cryptocurrency address on the requested
   * network. The returned <code>crypto.address</code> is the deposit address; funds
   * sent to it are credited to the <code>target</code> account in the specified asset.
   * For Customer-owned accounts, the Customer must have the <code>custodyCrypto</code>
   * and <code>custodyStablecoin</code> capabilities enabled.</p>
   * </li>
   * <li>
   * <p><code>fiat</code> (private-beta): provisions a bank
   * account at a CDP banking partner. The server picks the account type
   * (e.g. <code>us_bank</code>) and supported payment rails based on the account's
   * eligibility; pass <code>fiat.paymentRail</code> to influence partner selection.
   * The returned <code>fiat</code> object contains the bank account details the
   * depositor needs to send funds. For Customer-owned accounts, the Customer
   * must have the <code>custodyFiat</code> capability enabled. Requires account
   * enablement — contact your Coinbase representative for access. Fields
   * and behavior may change before general availability.</p>
   * </li>
   * </ul>
   * <p>For Customer-owned accounts not authorized for the required capabilities,
   * the request is rejected with <code>customer_not_authorized</code> (HTTP 403).</p>
   * <p>The created destination's <code>status</code> starts as <code>pending</code> for fiat (it
   * becomes <code>active</code> once the partner provisioning callback completes) and
   * <code>active</code> for crypto.</p>
   */
  public CompletableFuture<DepositDestination> createDepositDestination(
      CreateDepositDestinationRequest body) {
    return this.rawClient.createDepositDestination(body).thenApply(response -> response.body());
  }

  /**
   * Create a new deposit destination for an account. Two types are supported:
   * <ul>
   * <li>
   * <p><code>crypto</code> (public): provisions a cryptocurrency address on the requested
   * network. The returned <code>crypto.address</code> is the deposit address; funds
   * sent to it are credited to the <code>target</code> account in the specified asset.
   * For Customer-owned accounts, the Customer must have the <code>custodyCrypto</code>
   * and <code>custodyStablecoin</code> capabilities enabled.</p>
   * </li>
   * <li>
   * <p><code>fiat</code> (private-beta): provisions a bank
   * account at a CDP banking partner. The server picks the account type
   * (e.g. <code>us_bank</code>) and supported payment rails based on the account's
   * eligibility; pass <code>fiat.paymentRail</code> to influence partner selection.
   * The returned <code>fiat</code> object contains the bank account details the
   * depositor needs to send funds. For Customer-owned accounts, the Customer
   * must have the <code>custodyFiat</code> capability enabled. Requires account
   * enablement — contact your Coinbase representative for access. Fields
   * and behavior may change before general availability.</p>
   * </li>
   * </ul>
   * <p>For Customer-owned accounts not authorized for the required capabilities,
   * the request is rejected with <code>customer_not_authorized</code> (HTTP 403).</p>
   * <p>The created destination's <code>status</code> starts as <code>pending</code> for fiat (it
   * becomes <code>active</code> once the partner provisioning callback completes) and
   * <code>active</code> for crypto.</p>
   */
  public CompletableFuture<DepositDestination> createDepositDestination(
      CreateDepositDestinationRequest body, RequestOptions requestOptions) {
    return this.rawClient.createDepositDestination(body, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Create a new deposit destination for an account. Two types are supported:
   * <ul>
   * <li>
   * <p><code>crypto</code> (public): provisions a cryptocurrency address on the requested
   * network. The returned <code>crypto.address</code> is the deposit address; funds
   * sent to it are credited to the <code>target</code> account in the specified asset.
   * For Customer-owned accounts, the Customer must have the <code>custodyCrypto</code>
   * and <code>custodyStablecoin</code> capabilities enabled.</p>
   * </li>
   * <li>
   * <p><code>fiat</code> (private-beta): provisions a bank
   * account at a CDP banking partner. The server picks the account type
   * (e.g. <code>us_bank</code>) and supported payment rails based on the account's
   * eligibility; pass <code>fiat.paymentRail</code> to influence partner selection.
   * The returned <code>fiat</code> object contains the bank account details the
   * depositor needs to send funds. For Customer-owned accounts, the Customer
   * must have the <code>custodyFiat</code> capability enabled. Requires account
   * enablement — contact your Coinbase representative for access. Fields
   * and behavior may change before general availability.</p>
   * </li>
   * </ul>
   * <p>For Customer-owned accounts not authorized for the required capabilities,
   * the request is rejected with <code>customer_not_authorized</code> (HTTP 403).</p>
   * <p>The created destination's <code>status</code> starts as <code>pending</code> for fiat (it
   * becomes <code>active</code> once the partner provisioning callback completes) and
   * <code>active</code> for crypto.</p>
   */
  public CompletableFuture<DepositDestination> createDepositDestination(
      CreateDepositDestinationBody request) {
    return this.rawClient.createDepositDestination(request).thenApply(response -> response.body());
  }

  /**
   * Create a new deposit destination for an account. Two types are supported:
   * <ul>
   * <li>
   * <p><code>crypto</code> (public): provisions a cryptocurrency address on the requested
   * network. The returned <code>crypto.address</code> is the deposit address; funds
   * sent to it are credited to the <code>target</code> account in the specified asset.
   * For Customer-owned accounts, the Customer must have the <code>custodyCrypto</code>
   * and <code>custodyStablecoin</code> capabilities enabled.</p>
   * </li>
   * <li>
   * <p><code>fiat</code> (private-beta): provisions a bank
   * account at a CDP banking partner. The server picks the account type
   * (e.g. <code>us_bank</code>) and supported payment rails based on the account's
   * eligibility; pass <code>fiat.paymentRail</code> to influence partner selection.
   * The returned <code>fiat</code> object contains the bank account details the
   * depositor needs to send funds. For Customer-owned accounts, the Customer
   * must have the <code>custodyFiat</code> capability enabled. Requires account
   * enablement — contact your Coinbase representative for access. Fields
   * and behavior may change before general availability.</p>
   * </li>
   * </ul>
   * <p>For Customer-owned accounts not authorized for the required capabilities,
   * the request is rejected with <code>customer_not_authorized</code> (HTTP 403).</p>
   * <p>The created destination's <code>status</code> starts as <code>pending</code> for fiat (it
   * becomes <code>active</code> once the partner provisioning callback completes) and
   * <code>active</code> for crypto.</p>
   */
  public CompletableFuture<DepositDestination> createDepositDestination(
      CreateDepositDestinationBody request, RequestOptions requestOptions) {
    return this.rawClient.createDepositDestination(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get a specific deposit destination by its ID.
   */
  public CompletableFuture<DepositDestination> getDepositDestinationById(
      DepositDestinationId depositDestinationId) {
    return this.rawClient.getDepositDestinationById(depositDestinationId).thenApply(response -> response.body());
  }

  /**
   * Get a specific deposit destination by its ID.
   */
  public CompletableFuture<DepositDestination> getDepositDestinationById(
      DepositDestinationId depositDestinationId, RequestOptions requestOptions) {
    return this.rawClient.getDepositDestinationById(depositDestinationId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get a specific deposit destination by its ID.
   */
  public CompletableFuture<DepositDestination> getDepositDestinationById(
      DepositDestinationId depositDestinationId, GetDepositDestinationByIdRequest request) {
    return this.rawClient.getDepositDestinationById(depositDestinationId, request).thenApply(response -> response.body());
  }

  /**
   * Get a specific deposit destination by its ID.
   */
  public CompletableFuture<DepositDestination> getDepositDestinationById(
      DepositDestinationId depositDestinationId, GetDepositDestinationByIdRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getDepositDestinationById(depositDestinationId, request, requestOptions).thenApply(response -> response.body());
  }
}
