/*
 * Coinbase Developer Platform APIs
 *
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSwapQuoteResponse {
    /// The block number at which the liquidity conditions were examined.
    #[serde(rename = "blockNumber")]
    pub block_number: String,
    /// The amount of the `toToken` that will be received in atomic units of the `toToken`. For example, `1000000000000000000` when receiving ETH equates to 1 ETH, `1000000` when receiving USDC equates to 1 USDC, etc.
    #[serde(rename = "toAmount")]
    pub to_amount: String,
    /// The 0x-prefixed contract address of the token that will be received.
    #[serde(rename = "toToken")]
    pub to_token: String,
    #[serde(rename = "fees")]
    pub fees: Box<models::CommonSwapResponseFees>,
    #[serde(rename = "issues")]
    pub issues: Box<models::CommonSwapResponseIssues>,
    /// Whether sufficient liquidity is available to settle the swap. All other fields in the response will be empty if this is false.
    #[serde(rename = "liquidityAvailable")]
    pub liquidity_available: bool,
    /// The minimum amount of the `toToken` that must be received for the swap to succeed, in atomic units of the `toToken`.  For example, `1000000000000000000` when receiving ETH equates to 1 ETH, `1000000` when receiving USDC equates to 1 USDC, etc. This value is influenced by the `slippageBps` parameter.
    #[serde(rename = "minToAmount")]
    pub min_to_amount: String,
    /// The amount of the `fromToken` that will be sent in this swap, in atomic units of the `fromToken`. For example, `1000000000000000000` when sending ETH equates to 1 ETH, `1000000` when sending USDC equates to 1 USDC, etc.
    #[serde(rename = "fromAmount")]
    pub from_amount: String,
    /// The 0x-prefixed contract address of the token that will be sent.
    #[serde(rename = "fromToken")]
    pub from_token: String,
    #[serde(rename = "permit2", deserialize_with = "Option::deserialize")]
    pub permit2: Option<Box<models::CreateSwapQuoteResponseAllOfPermit2>>,
    #[serde(rename = "transaction")]
    pub transaction: Box<models::CreateSwapQuoteResponseAllOfTransaction>,
}

impl CreateSwapQuoteResponse {
    pub fn new(block_number: String, to_amount: String, to_token: String, fees: models::CommonSwapResponseFees, issues: models::CommonSwapResponseIssues, liquidity_available: bool, min_to_amount: String, from_amount: String, from_token: String, permit2: Option<models::CreateSwapQuoteResponseAllOfPermit2>, transaction: models::CreateSwapQuoteResponseAllOfTransaction) -> CreateSwapQuoteResponse {
        CreateSwapQuoteResponse {
            block_number,
            to_amount,
            to_token,
            fees: Box::new(fees),
            issues: Box::new(issues),
            liquidity_available,
            min_to_amount,
            from_amount,
            from_token,
            permit2: if let Some(x) = permit2 {Some(Box::new(x))} else {None},
            transaction: Box::new(transaction),
        }
    }
}

