/*
 * Coinbase Developer Platform APIs
 *
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EvmTypedNumericalCondition : A schema for specifying criterion for a numerical field of an EVM typed message. The value can be deeply nested within the typed data's message.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvmTypedNumericalCondition {
    /// The amount that the value located at the message's path should be compared to.
    #[serde(rename = "value")]
    pub value: String,
    /// The operator to use for the comparison. The value located at the message's path will be on the left-hand side of the operator, and the `value` field will be on the right-hand side.
    #[serde(rename = "operator")]
    pub operator: Operator,
    /// The path to the field to compare against this criterion. To reference deeply nested fields within the message, separate object keys by `.`, and access array values using `[index]`. If the field does not exist or is not an address, the operation will be rejected.
    #[serde(rename = "path")]
    pub path: String,
}

impl EvmTypedNumericalCondition {
    /// A schema for specifying criterion for a numerical field of an EVM typed message. The value can be deeply nested within the typed data's message.
    pub fn new(value: String, operator: Operator, path: String) -> EvmTypedNumericalCondition {
        EvmTypedNumericalCondition {
            value,
            operator,
            path,
        }
    }
}
/// The operator to use for the comparison. The value located at the message's path will be on the left-hand side of the operator, and the `value` field will be on the right-hand side.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operator {
    #[serde(rename = ">")]
    GreaterThan,
    #[serde(rename = ">=")]
    GreaterThanEqual,
    #[serde(rename = "<")]
    LessThan,
    #[serde(rename = "<=")]
    LessThanEqual,
    #[serde(rename = "==")]
    EqualEqual,
}

impl Default for Operator {
    fn default() -> Operator {
        Self::GreaterThan
    }
}

