/*
 * Coinbase Developer Platform APIs
 *
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// X402PaymentPayload : The x402 protocol payment payload that the client attaches to x402-paid API requests to the resource server in the X-PAYMENT header.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct X402PaymentPayload {
    #[serde(rename = "x402Version")]
    pub x402_version: models::X402Version,
    /// The scheme of the payment protocol to use. Currently, the only supported scheme is `exact`.
    #[serde(rename = "scheme")]
    pub scheme: Scheme,
    /// The network of the blockchain to send payment on.
    #[serde(rename = "network")]
    pub network: Network,
    #[serde(rename = "payload")]
    pub payload: Box<models::X402PaymentPayloadPayload>,
}

impl X402PaymentPayload {
    /// The x402 protocol payment payload that the client attaches to x402-paid API requests to the resource server in the X-PAYMENT header.
    pub fn new(x402_version: models::X402Version, scheme: Scheme, network: Network, payload: models::X402PaymentPayloadPayload) -> X402PaymentPayload {
        X402PaymentPayload {
            x402_version,
            scheme,
            network,
            payload: Box::new(payload),
        }
    }
}
/// The scheme of the payment protocol to use. Currently, the only supported scheme is `exact`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scheme {
    #[serde(rename = "exact")]
    Exact,
}

impl Default for Scheme {
    fn default() -> Scheme {
        Self::Exact
    }
}
/// The network of the blockchain to send payment on.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Network {
    #[serde(rename = "base-sepolia")]
    BaseSepolia,
    #[serde(rename = "base")]
    Base,
}

impl Default for Network {
    fn default() -> Network {
        Self::BaseSepolia
    }
}

