/*
 * Coinbase Developer Platform APIs
 *
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvmDataParameterConditionList {
    /// The name of the parameter to check against a transaction's calldata. If name is unknown, or is not named, you may supply an array index, e.g., `0` for first parameter.
    #[serde(rename = "name")]
    pub name: String,
    /// The operator to use for the comparison. The value resolved at the `name` will be on the left-hand side of the operator, and the `values` field will be on the right-hand side.
    #[serde(rename = "operator")]
    pub operator: Operator,
    /// Values to compare against the resolved `name` value. All values are encoded as strings. Refer to the table in the documentation for how values should be encoded, and which operators are supported for each type.
    #[serde(rename = "values")]
    pub values: Vec<String>,
}

impl EvmDataParameterConditionList {
    pub fn new(name: String, operator: Operator, values: Vec<String>) -> EvmDataParameterConditionList {
        EvmDataParameterConditionList {
            name,
            operator,
            values,
        }
    }
}
/// The operator to use for the comparison. The value resolved at the `name` will be on the left-hand side of the operator, and the `values` field will be on the right-hand side.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operator {
    #[serde(rename = "in")]
    In,
    #[serde(rename = "not in")]
    NotIn,
}

impl Default for Operator {
    fn default() -> Operator {
        Self::In
    }
}

