/*
 * Coinbase Developer Platform APIs
 *
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NetUsdChangeCriterion : A schema for specifying a criterion for the USD denominated asset transfer or exposure for a transaction. This includes native transfers, as well as token transfers.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NetUsdChangeCriterion {
    /// The type of criterion to use. This should be `netUSDChange`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The amount of USD, in cents, that the total value of a transaction's asset transfer should be compared to.
    #[serde(rename = "changeCents")]
    pub change_cents: i32,
    /// The operator to use for the comparison. The total value of a transaction's asset transfer will be on the left-hand side of the operator, and the `changeCents` field will be on the right-hand side.
    #[serde(rename = "operator")]
    pub operator: Operator,
}

impl NetUsdChangeCriterion {
    /// A schema for specifying a criterion for the USD denominated asset transfer or exposure for a transaction. This includes native transfers, as well as token transfers.
    pub fn new(r#type: Type, change_cents: i32, operator: Operator) -> NetUsdChangeCriterion {
        NetUsdChangeCriterion {
            r#type,
            change_cents,
            operator,
        }
    }
}
/// The type of criterion to use. This should be `netUSDChange`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "netUSDChange")]
    NetUsdChange,
}

impl Default for Type {
    fn default() -> Type {
        Self::NetUsdChange
    }
}
/// The operator to use for the comparison. The total value of a transaction's asset transfer will be on the left-hand side of the operator, and the `changeCents` field will be on the right-hand side.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operator {
    #[serde(rename = ">")]
    GreaterThan,
    #[serde(rename = ">=")]
    GreaterThanEqual,
    #[serde(rename = "<")]
    LessThan,
    #[serde(rename = "<=")]
    LessThanEqual,
    #[serde(rename = "==")]
    EqualEqual,
}

impl Default for Operator {
    fn default() -> Operator {
        Self::GreaterThan
    }
}

