/*
 * Coinbase Developer Platform APIs
 *
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SplAddressCriterion : The criterion for the recipient addresses of a Solana transaction's SPL token transfer instructions.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SplAddressCriterion {
    /// The type of criterion to use. This should be `splAddress`.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The Solana addresses that are compared to the list of SPL token transfer recipient addresses in the transaction's `accountKeys` (for legacy transactions) or `staticAccountKeys` (for V0 transactions) array.
    #[serde(rename = "addresses")]
    pub addresses: Vec<String>,
    /// The operator to use for the comparison. Each of the SPL token transfer recipient addresses in the transaction's `accountKeys` (for legacy transactions) or `staticAccountKeys` (for V0 transactions) array will be on the left-hand side of the operator, and the `addresses` field will be on the right-hand side.
    #[serde(rename = "operator")]
    pub operator: Operator,
}

impl SplAddressCriterion {
    /// The criterion for the recipient addresses of a Solana transaction's SPL token transfer instructions.
    pub fn new(r#type: Type, addresses: Vec<String>, operator: Operator) -> SplAddressCriterion {
        SplAddressCriterion {
            r#type,
            addresses,
            operator,
        }
    }
}
/// The type of criterion to use. This should be `splAddress`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "splAddress")]
    SplAddress,
}

impl Default for Type {
    fn default() -> Type {
        Self::SplAddress
    }
}
/// The operator to use for the comparison. Each of the SPL token transfer recipient addresses in the transaction's `accountKeys` (for legacy transactions) or `staticAccountKeys` (for V0 transactions) array will be on the left-hand side of the operator, and the `addresses` field will be on the right-hand side.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operator {
    #[serde(rename = "in")]
    In,
    #[serde(rename = "not in")]
    NotIn,
}

impl Default for Operator {
    fn default() -> Operator {
        Self::In
    }
}

