/*
 * Coinbase Developer Platform APIs
 *
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferTarget : The target of the transfer.
/// The target of the transfer.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TransferTarget {
    CryptoRailAddress(Box<models::CryptoRailAddress>),
}

impl Default for TransferTarget {
    fn default() -> Self {
        Self::CryptoRailAddress(Default::default())
    }
}

