# Clippy configuration for CDP Rust SDK

# Allow certain patterns common in generated code
too-many-arguments-threshold = 15
enum-variant-name-threshold = 300
enum-variant-size-threshold = 300

# Configuration for generated code patterns
avoid-breaking-exported-api = false
allow-unwrap-in-tests = true
