/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.resources.evmaccounts.requests;

import com.coinbase.cdp.core.ObjectMappers;
import com.coinbase.cdp.types.Eip712Message;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SignEvmTypedDataRequest.Builder.class
)
public final class SignEvmTypedDataRequest {
  private final Optional<String> idempotencyKey;

  private final Eip712Message body;

  private final Map<String, Object> additionalProperties;

  private SignEvmTypedDataRequest(Optional<String> idempotencyKey, Eip712Message body,
      Map<String, Object> additionalProperties) {
    this.idempotencyKey = idempotencyKey;
    this.body = body;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return An optional string request header for making requests safely retryable.
   * When included, duplicate requests with the same key will return identical responses.
   * Refer to our <a href="https://docs.cdp.coinbase.com/api-reference/v2/idempotency">Idempotency docs</a> for more information on using idempotency keys.
   */
  @JsonIgnore
  public Optional<String> getIdempotencyKey() {
    return idempotencyKey;
  }

  @JsonProperty("body")
  public Eip712Message getBody() {
    return body;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SignEvmTypedDataRequest && equalTo((SignEvmTypedDataRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SignEvmTypedDataRequest other) {
    return idempotencyKey.equals(other.idempotencyKey) && body.equals(other.body);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.idempotencyKey, this.body);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static BodyStage builder() {
    return new Builder();
  }

  public interface BodyStage {
    _FinalStage body(@NotNull Eip712Message body);

    Builder from(SignEvmTypedDataRequest other);
  }

  public interface _FinalStage {
    SignEvmTypedDataRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>An optional string request header for making requests safely retryable.
     * When included, duplicate requests with the same key will return identical responses.
     * Refer to our <a href="https://docs.cdp.coinbase.com/api-reference/v2/idempotency">Idempotency docs</a> for more information on using idempotency keys.</p>
     */
    _FinalStage idempotencyKey(Optional<String> idempotencyKey);

    _FinalStage idempotencyKey(String idempotencyKey);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements BodyStage, _FinalStage {
    private Eip712Message body;

    private Optional<String> idempotencyKey = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(SignEvmTypedDataRequest other) {
      idempotencyKey(other.getIdempotencyKey());
      body(other.getBody());
      return this;
    }

    @java.lang.Override
    @JsonSetter("body")
    public _FinalStage body(@NotNull Eip712Message body) {
      this.body = Objects.requireNonNull(body, "body must not be null");
      return this;
    }

    /**
     * <p>An optional string request header for making requests safely retryable.
     * When included, duplicate requests with the same key will return identical responses.
     * Refer to our <a href="https://docs.cdp.coinbase.com/api-reference/v2/idempotency">Idempotency docs</a> for more information on using idempotency keys.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage idempotencyKey(String idempotencyKey) {
      this.idempotencyKey = Optional.ofNullable(idempotencyKey);
      return this;
    }

    /**
     * <p>An optional string request header for making requests safely retryable.
     * When included, duplicate requests with the same key will return identical responses.
     * Refer to our <a href="https://docs.cdp.coinbase.com/api-reference/v2/idempotency">Idempotency docs</a> for more information on using idempotency keys.</p>
     */
    @java.lang.Override
    public _FinalStage idempotencyKey(Optional<String> idempotencyKey) {
      this.idempotencyKey = idempotencyKey;
      return this;
    }

    @java.lang.Override
    public SignEvmTypedDataRequest build() {
      return new SignEvmTypedDataRequest(idempotencyKey, body, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
