/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.resources.solanaaccounts.types;

import com.coinbase.cdp.core.ObjectMappers;
import com.coinbase.cdp.types.SolanaAccount;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListSolanaAccountsResponse.Builder.class
)
public final class ListSolanaAccountsResponse {
  private final List<SolanaAccount> accounts;

  private final Optional<String> nextPageToken;

  private final Map<String, Object> additionalProperties;

  private ListSolanaAccountsResponse(List<SolanaAccount> accounts, Optional<String> nextPageToken,
      Map<String, Object> additionalProperties) {
    this.accounts = accounts;
    this.nextPageToken = nextPageToken;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The list of Solana accounts.
   */
  @JsonProperty("accounts")
  public List<SolanaAccount> getAccounts() {
    return accounts;
  }

  /**
   * @return The token for the next page of items, if any.
   */
  @JsonProperty("nextPageToken")
  public Optional<String> getNextPageToken() {
    return nextPageToken;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListSolanaAccountsResponse && equalTo((ListSolanaAccountsResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListSolanaAccountsResponse other) {
    return accounts.equals(other.accounts) && nextPageToken.equals(other.nextPageToken);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.accounts, this.nextPageToken);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private List<SolanaAccount> accounts = new ArrayList<>();

    private Optional<String> nextPageToken = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ListSolanaAccountsResponse other) {
      accounts(other.getAccounts());
      nextPageToken(other.getNextPageToken());
      return this;
    }

    /**
     * <p>The list of Solana accounts.</p>
     */
    @JsonSetter(
        value = "accounts",
        nulls = Nulls.SKIP
    )
    public Builder accounts(List<SolanaAccount> accounts) {
      this.accounts.clear();
      if (accounts != null) {
        this.accounts.addAll(accounts);
      }
      return this;
    }

    public Builder addAccounts(SolanaAccount accounts) {
      this.accounts.add(accounts);
      return this;
    }

    public Builder addAllAccounts(List<SolanaAccount> accounts) {
      if (accounts != null) {
        this.accounts.addAll(accounts);
      }
      return this;
    }

    /**
     * <p>The token for the next page of items, if any.</p>
     */
    @JsonSetter(
        value = "nextPageToken",
        nulls = Nulls.SKIP
    )
    public Builder nextPageToken(Optional<String> nextPageToken) {
      this.nextPageToken = nextPageToken;
      return this;
    }

    public Builder nextPageToken(String nextPageToken) {
      this.nextPageToken = Optional.ofNullable(nextPageToken);
      return this;
    }

    public ListSolanaAccountsResponse build() {
      return new ListSolanaAccountsResponse(accounts, nextPageToken, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
