/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.core;

import java.io.IOException;
import java.io.InputStream;
import java.util.Objects;
import okhttp3.MediaType;
import okhttp3.RequestBody;
import okio.BufferedSink;
import okio.Okio;
import okio.Source;
import org.jetbrains.annotations.Nullable;

/**
 * A custom implementation of OkHttp's RequestBody that wraps an InputStream.
 * This class allows streaming of data from an InputStream directly to an HTTP request body,
 * which is useful for file uploads or sending large amounts of data without loading it all into memory.
 */
public class InputStreamRequestBody extends RequestBody {
    private final InputStream inputStream;
    private final MediaType contentType;

    /**
     * Constructs an InputStreamRequestBody with the specified content type and input stream.
     *
     * @param contentType the MediaType of the content, or null if not known
     * @param inputStream the InputStream containing the data to be sent
     * @throws NullPointerException if inputStream is null
     */
    public InputStreamRequestBody(@Nullable MediaType contentType, InputStream inputStream) {
        this.contentType = contentType;
        this.inputStream = Objects.requireNonNull(inputStream, "inputStream == null");
    }

    /**
     * Returns the content type of this request body.
     *
     * @return the MediaType of the content, or null if not specified
     */
    @Nullable
    @Override
    public MediaType contentType() {
        return contentType;
    }

    /**
     * Returns {@code -1} because a general InputStream has no reliable total length.
     *
     * @return {@code -1}, indicating an unknown content length
     */
    @Override
    public long contentLength() {
        return -1;
    }

    /**
     * Writes the content of the InputStream to the given BufferedSink.
     * This method is responsible for transferring the data from the InputStream to the network request.
     *
     * @param sink the BufferedSink to write the content to
     * @throws IOException if an I/O error occurs during writing
     */
    @Override
    public void writeTo(BufferedSink sink) throws IOException {
        try (Source source = Okio.source(inputStream)) {
            sink.writeAll(source);
        }
    }
}