/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.resources.evmswaps.requests;

import com.coinbase.cdp.core.ObjectMappers;
import com.coinbase.cdp.types.EvmSwapsNetwork;
import com.coinbase.cdp.types.FromAmount;
import com.coinbase.cdp.types.FromToken;
import com.coinbase.cdp.types.GasPrice;
import com.coinbase.cdp.types.SignerAddress;
import com.coinbase.cdp.types.SlippageBps;
import com.coinbase.cdp.types.Taker;
import com.coinbase.cdp.types.ToToken;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetEvmSwapPriceRequest.Builder.class
)
public final class GetEvmSwapPriceRequest {
  private final EvmSwapsNetwork network;

  private final ToToken toToken;

  private final FromToken fromToken;

  private final FromAmount fromAmount;

  private final Taker taker;

  private final Optional<SignerAddress> signerAddress;

  private final Optional<GasPrice> gasPrice;

  private final Optional<SlippageBps> slippageBps;

  private final Map<String, Object> additionalProperties;

  private GetEvmSwapPriceRequest(EvmSwapsNetwork network, ToToken toToken, FromToken fromToken,
      FromAmount fromAmount, Taker taker, Optional<SignerAddress> signerAddress,
      Optional<GasPrice> gasPrice, Optional<SlippageBps> slippageBps,
      Map<String, Object> additionalProperties) {
    this.network = network;
    this.toToken = toToken;
    this.fromToken = fromToken;
    this.fromAmount = fromAmount;
    this.taker = taker;
    this.signerAddress = signerAddress;
    this.gasPrice = gasPrice;
    this.slippageBps = slippageBps;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("network")
  public EvmSwapsNetwork getNetwork() {
    return network;
  }

  @JsonProperty("toToken")
  public ToToken getToToken() {
    return toToken;
  }

  @JsonProperty("fromToken")
  public FromToken getFromToken() {
    return fromToken;
  }

  @JsonProperty("fromAmount")
  public FromAmount getFromAmount() {
    return fromAmount;
  }

  @JsonProperty("taker")
  public Taker getTaker() {
    return taker;
  }

  @JsonProperty("signerAddress")
  public Optional<SignerAddress> getSignerAddress() {
    return signerAddress;
  }

  @JsonProperty("gasPrice")
  public Optional<GasPrice> getGasPrice() {
    return gasPrice;
  }

  @JsonProperty("slippageBps")
  public Optional<SlippageBps> getSlippageBps() {
    return slippageBps;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetEvmSwapPriceRequest && equalTo((GetEvmSwapPriceRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetEvmSwapPriceRequest other) {
    return network.equals(other.network) && toToken.equals(other.toToken) && fromToken.equals(other.fromToken) && fromAmount.equals(other.fromAmount) && taker.equals(other.taker) && signerAddress.equals(other.signerAddress) && gasPrice.equals(other.gasPrice) && slippageBps.equals(other.slippageBps);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.network, this.toToken, this.fromToken, this.fromAmount, this.taker, this.signerAddress, this.gasPrice, this.slippageBps);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NetworkStage builder() {
    return new Builder();
  }

  public interface NetworkStage {
    ToTokenStage network(@NotNull EvmSwapsNetwork network);

    Builder from(GetEvmSwapPriceRequest other);
  }

  public interface ToTokenStage {
    FromTokenStage toToken(@NotNull ToToken toToken);
  }

  public interface FromTokenStage {
    FromAmountStage fromToken(@NotNull FromToken fromToken);
  }

  public interface FromAmountStage {
    TakerStage fromAmount(@NotNull FromAmount fromAmount);
  }

  public interface TakerStage {
    _FinalStage taker(@NotNull Taker taker);
  }

  public interface _FinalStage {
    GetEvmSwapPriceRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage signerAddress(Optional<SignerAddress> signerAddress);

    _FinalStage signerAddress(SignerAddress signerAddress);

    _FinalStage gasPrice(Optional<GasPrice> gasPrice);

    _FinalStage gasPrice(GasPrice gasPrice);

    _FinalStage slippageBps(Optional<SlippageBps> slippageBps);

    _FinalStage slippageBps(SlippageBps slippageBps);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NetworkStage, ToTokenStage, FromTokenStage, FromAmountStage, TakerStage, _FinalStage {
    private EvmSwapsNetwork network;

    private ToToken toToken;

    private FromToken fromToken;

    private FromAmount fromAmount;

    private Taker taker;

    private Optional<SlippageBps> slippageBps = Optional.empty();

    private Optional<GasPrice> gasPrice = Optional.empty();

    private Optional<SignerAddress> signerAddress = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GetEvmSwapPriceRequest other) {
      network(other.getNetwork());
      toToken(other.getToToken());
      fromToken(other.getFromToken());
      fromAmount(other.getFromAmount());
      taker(other.getTaker());
      signerAddress(other.getSignerAddress());
      gasPrice(other.getGasPrice());
      slippageBps(other.getSlippageBps());
      return this;
    }

    @java.lang.Override
    @JsonSetter("network")
    public ToTokenStage network(@NotNull EvmSwapsNetwork network) {
      this.network = Objects.requireNonNull(network, "network must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("toToken")
    public FromTokenStage toToken(@NotNull ToToken toToken) {
      this.toToken = Objects.requireNonNull(toToken, "toToken must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("fromToken")
    public FromAmountStage fromToken(@NotNull FromToken fromToken) {
      this.fromToken = Objects.requireNonNull(fromToken, "fromToken must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("fromAmount")
    public TakerStage fromAmount(@NotNull FromAmount fromAmount) {
      this.fromAmount = Objects.requireNonNull(fromAmount, "fromAmount must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("taker")
    public _FinalStage taker(@NotNull Taker taker) {
      this.taker = Objects.requireNonNull(taker, "taker must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage slippageBps(SlippageBps slippageBps) {
      this.slippageBps = Optional.ofNullable(slippageBps);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "slippageBps",
        nulls = Nulls.SKIP
    )
    public _FinalStage slippageBps(Optional<SlippageBps> slippageBps) {
      this.slippageBps = slippageBps;
      return this;
    }

    @java.lang.Override
    public _FinalStage gasPrice(GasPrice gasPrice) {
      this.gasPrice = Optional.ofNullable(gasPrice);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "gasPrice",
        nulls = Nulls.SKIP
    )
    public _FinalStage gasPrice(Optional<GasPrice> gasPrice) {
      this.gasPrice = gasPrice;
      return this;
    }

    @java.lang.Override
    public _FinalStage signerAddress(SignerAddress signerAddress) {
      this.signerAddress = Optional.ofNullable(signerAddress);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "signerAddress",
        nulls = Nulls.SKIP
    )
    public _FinalStage signerAddress(Optional<SignerAddress> signerAddress) {
      this.signerAddress = signerAddress;
      return this;
    }

    @java.lang.Override
    public GetEvmSwapPriceRequest build() {
      return new GetEvmSwapPriceRequest(network, toToken, fromToken, fromAmount, taker, signerAddress, gasPrice, slippageBps, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
