/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public final class CreateDepositDestinationRequest {
  private final Value value;

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  private CreateDepositDestinationRequest(Value value) {
    this.value = value;
  }

  public <T> T visit(Visitor<T> visitor) {
    return value.visit(visitor);
  }

  public static CreateDepositDestinationRequest crypto(
      CreateCryptoDepositDestinationRequest value) {
    return new CreateDepositDestinationRequest(new CryptoValue(value));
  }

  public static CreateDepositDestinationRequest fiat(CreateFiatDepositDestinationRequest value) {
    return new CreateDepositDestinationRequest(new FiatValue(value));
  }

  public boolean isCrypto() {
    return value instanceof CryptoValue;
  }

  public boolean isFiat() {
    return value instanceof FiatValue;
  }

  public boolean _isUnknown() {
    return value instanceof _UnknownValue;
  }

  public Optional<CreateCryptoDepositDestinationRequest> getCrypto() {
    if (isCrypto()) {
      return Optional.of(((CryptoValue) value).value);
    }
    return Optional.empty();
  }

  public Optional<CreateFiatDepositDestinationRequest> getFiat() {
    if (isFiat()) {
      return Optional.of(((FiatValue) value).value);
    }
    return Optional.empty();
  }

  public Optional<Object> _getUnknown() {
    if (_isUnknown()) {
      return Optional.of(((_UnknownValue) value).value);
    }
    return Optional.empty();
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateDepositDestinationRequest && value.equals(((CreateDepositDestinationRequest) other).value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public String toString() {
    return value.toString();
  }

  @JsonValue
  private Value getValue() {
    return this.value;
  }

  public interface Visitor<T> {
    T visitCrypto(CreateCryptoDepositDestinationRequest crypto);

    T visitFiat(CreateFiatDepositDestinationRequest fiat);

    T _visitUnknown(Object unknownType);
  }

  @JsonTypeInfo(
      use = JsonTypeInfo.Id.NAME,
      property = "type",
      visible = true,
      defaultImpl = _UnknownValue.class
  )
  @JsonSubTypes({
      @JsonSubTypes.Type(CryptoValue.class),
      @JsonSubTypes.Type(FiatValue.class)
  })
  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  private interface Value {
    <T> T visit(Visitor<T> visitor);
  }

  @JsonTypeName("crypto")
  @JsonIgnoreProperties("type")
  private static final class CryptoValue implements Value {
    @JsonUnwrapped
    @JsonIgnoreProperties(
        value = "type",
        allowSetters = true
    )
    private CreateCryptoDepositDestinationRequest value;

    @JsonCreator(
        mode = JsonCreator.Mode.PROPERTIES
    )
    private CryptoValue() {
    }

    private CryptoValue(CreateCryptoDepositDestinationRequest value) {
      this.value = value;
    }

    @java.lang.Override
    public <T> T visit(Visitor<T> visitor) {
      return visitor.visitCrypto(value);
    }

    @java.lang.Override
    public boolean equals(Object other) {
      if (this == other) return true;
      return other instanceof CryptoValue && equalTo((CryptoValue) other);
    }

    private boolean equalTo(CryptoValue other) {
      return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
      return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
      return "CreateDepositDestinationRequest{" + "value: " + value + "}";
    }
  }

  @JsonTypeName("fiat")
  @JsonIgnoreProperties("type")
  private static final class FiatValue implements Value {
    @JsonUnwrapped
    @JsonIgnoreProperties(
        value = "type",
        allowSetters = true
    )
    private CreateFiatDepositDestinationRequest value;

    @JsonCreator(
        mode = JsonCreator.Mode.PROPERTIES
    )
    private FiatValue() {
    }

    private FiatValue(CreateFiatDepositDestinationRequest value) {
      this.value = value;
    }

    @java.lang.Override
    public <T> T visit(Visitor<T> visitor) {
      return visitor.visitFiat(value);
    }

    @java.lang.Override
    public boolean equals(Object other) {
      if (this == other) return true;
      return other instanceof FiatValue && equalTo((FiatValue) other);
    }

    private boolean equalTo(FiatValue other) {
      return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
      return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
      return "CreateDepositDestinationRequest{" + "value: " + value + "}";
    }
  }

  @JsonIgnoreProperties("type")
  private static final class _UnknownValue implements Value {
    private String type;

    @JsonValue
    private Object value;

    @JsonCreator(
        mode = JsonCreator.Mode.PROPERTIES
    )
    private _UnknownValue(@JsonProperty("value") Object value) {
    }

    @java.lang.Override
    public <T> T visit(Visitor<T> visitor) {
      return visitor._visitUnknown(value);
    }

    @java.lang.Override
    public boolean equals(Object other) {
      if (this == other) return true;
      return other instanceof _UnknownValue && equalTo((_UnknownValue) other);
    }

    private boolean equalTo(_UnknownValue other) {
      return type.equals(other.type) && value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
      return Objects.hash(this.type, this.value);
    }

    @java.lang.Override
    public String toString() {
      return "CreateDepositDestinationRequest{" + "type: " + type + ", value: " + value + "}";
    }
  }
}
