/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.types;

import com.coinbase.cdp.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DepositDestinationTargetAccount.Builder.class
)
public final class DepositDestinationTargetAccount {
  private final Optional<AccountId> accountId;

  private final Asset asset;

  private final Map<String, Object> additionalProperties;

  private DepositDestinationTargetAccount(Optional<AccountId> accountId, Asset asset,
      Map<String, Object> additionalProperties) {
    this.accountId = accountId;
    this.asset = asset;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The ID of the CDP Account to which deposited funds should be transferred.
   */
  @JsonProperty("accountId")
  public Optional<AccountId> getAccountId() {
    return accountId;
  }

  /**
   * @return The symbol of the asset that should land in the target account.
   */
  @JsonProperty("asset")
  public Asset getAsset() {
    return asset;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DepositDestinationTargetAccount && equalTo((DepositDestinationTargetAccount) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DepositDestinationTargetAccount other) {
    return accountId.equals(other.accountId) && asset.equals(other.asset);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.accountId, this.asset);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static AssetStage builder() {
    return new Builder();
  }

  public interface AssetStage {
    /**
     * <p>The symbol of the asset that should land in the target account.</p>
     */
    _FinalStage asset(@NotNull Asset asset);

    Builder from(DepositDestinationTargetAccount other);
  }

  public interface _FinalStage {
    DepositDestinationTargetAccount build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>The ID of the CDP Account to which deposited funds should be transferred.</p>
     */
    _FinalStage accountId(Optional<AccountId> accountId);

    _FinalStage accountId(AccountId accountId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements AssetStage, _FinalStage {
    private Asset asset;

    private Optional<AccountId> accountId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(DepositDestinationTargetAccount other) {
      accountId(other.getAccountId());
      asset(other.getAsset());
      return this;
    }

    /**
     * <p>The symbol of the asset that should land in the target account.</p>
     * <p>The symbol of the asset that should land in the target account.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("asset")
    public _FinalStage asset(@NotNull Asset asset) {
      this.asset = Objects.requireNonNull(asset, "asset must not be null");
      return this;
    }

    /**
     * <p>The ID of the CDP Account to which deposited funds should be transferred.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage accountId(AccountId accountId) {
      this.accountId = Optional.ofNullable(accountId);
      return this;
    }

    /**
     * <p>The ID of the CDP Account to which deposited funds should be transferred.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "accountId",
        nulls = Nulls.SKIP
    )
    public _FinalStage accountId(Optional<AccountId> accountId) {
      this.accountId = accountId;
      return this;
    }

    @java.lang.Override
    public DepositDestinationTargetAccount build() {
      return new DepositDestinationTargetAccount(accountId, asset, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
