/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.types;

import com.coinbase.cdp.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = Eip712Domain.Builder.class
)
public final class Eip712Domain {
  private final Optional<String> name;

  private final Optional<String> version;

  private final Optional<Long> chainId;

  private final Optional<String> verifyingContract;

  private final Optional<String> salt;

  private final Map<String, Object> additionalProperties;

  private Eip712Domain(Optional<String> name, Optional<String> version, Optional<Long> chainId,
      Optional<String> verifyingContract, Optional<String> salt,
      Map<String, Object> additionalProperties) {
    this.name = name;
    this.version = version;
    this.chainId = chainId;
    this.verifyingContract = verifyingContract;
    this.salt = salt;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The name of the DApp or protocol.
   */
  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  /**
   * @return The version of the DApp or protocol.
   */
  @JsonProperty("version")
  public Optional<String> getVersion() {
    return version;
  }

  /**
   * @return The chain ID of the EVM network.
   */
  @JsonProperty("chainId")
  public Optional<Long> getChainId() {
    return chainId;
  }

  /**
   * @return The 0x-prefixed EVM address of the verifying smart contract.
   */
  @JsonProperty("verifyingContract")
  public Optional<String> getVerifyingContract() {
    return verifyingContract;
  }

  /**
   * @return The optional 32-byte 0x-prefixed hex salt for domain separation.
   */
  @JsonProperty("salt")
  public Optional<String> getSalt() {
    return salt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof Eip712Domain && equalTo((Eip712Domain) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(Eip712Domain other) {
    return name.equals(other.name) && version.equals(other.version) && chainId.equals(other.chainId) && verifyingContract.equals(other.verifyingContract) && salt.equals(other.salt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.version, this.chainId, this.verifyingContract, this.salt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> name = Optional.empty();

    private Optional<String> version = Optional.empty();

    private Optional<Long> chainId = Optional.empty();

    private Optional<String> verifyingContract = Optional.empty();

    private Optional<String> salt = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(Eip712Domain other) {
      name(other.getName());
      version(other.getVersion());
      chainId(other.getChainId());
      verifyingContract(other.getVerifyingContract());
      salt(other.getSalt());
      return this;
    }

    /**
     * <p>The name of the DApp or protocol.</p>
     */
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    /**
     * <p>The version of the DApp or protocol.</p>
     */
    @JsonSetter(
        value = "version",
        nulls = Nulls.SKIP
    )
    public Builder version(Optional<String> version) {
      this.version = version;
      return this;
    }

    public Builder version(String version) {
      this.version = Optional.ofNullable(version);
      return this;
    }

    /**
     * <p>The chain ID of the EVM network.</p>
     */
    @JsonSetter(
        value = "chainId",
        nulls = Nulls.SKIP
    )
    public Builder chainId(Optional<Long> chainId) {
      this.chainId = chainId;
      return this;
    }

    public Builder chainId(Long chainId) {
      this.chainId = Optional.ofNullable(chainId);
      return this;
    }

    /**
     * <p>The 0x-prefixed EVM address of the verifying smart contract.</p>
     */
    @JsonSetter(
        value = "verifyingContract",
        nulls = Nulls.SKIP
    )
    public Builder verifyingContract(Optional<String> verifyingContract) {
      this.verifyingContract = verifyingContract;
      return this;
    }

    public Builder verifyingContract(String verifyingContract) {
      this.verifyingContract = Optional.ofNullable(verifyingContract);
      return this;
    }

    /**
     * <p>The optional 32-byte 0x-prefixed hex salt for domain separation.</p>
     */
    @JsonSetter(
        value = "salt",
        nulls = Nulls.SKIP
    )
    public Builder salt(Optional<String> salt) {
      this.salt = salt;
      return this;
    }

    public Builder salt(String salt) {
      this.salt = Optional.ofNullable(salt);
      return this;
    }

    public Eip712Domain build() {
      return new Eip712Domain(name, version, chainId, verifyingContract, salt, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
