/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.types;

import com.coinbase.cdp.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = EndUser.Builder.class
)
public final class EndUser {
  private final String userId;

  private final AuthenticationMethods authenticationMethods;

  private final Optional<MfaMethods> mfaMethods;

  private final List<String> evmAccounts;

  private final List<EndUserEvmAccount> evmAccountObjects;

  private final List<String> evmSmartAccounts;

  private final List<EndUserEvmSmartAccount> evmSmartAccountObjects;

  private final List<String> solanaAccounts;

  private final List<EndUserSolanaAccount> solanaAccountObjects;

  private final OffsetDateTime createdAt;

  private final Map<String, Object> additionalProperties;

  private EndUser(String userId, AuthenticationMethods authenticationMethods,
      Optional<MfaMethods> mfaMethods, List<String> evmAccounts,
      List<EndUserEvmAccount> evmAccountObjects, List<String> evmSmartAccounts,
      List<EndUserEvmSmartAccount> evmSmartAccountObjects, List<String> solanaAccounts,
      List<EndUserSolanaAccount> solanaAccountObjects, OffsetDateTime createdAt,
      Map<String, Object> additionalProperties) {
    this.userId = userId;
    this.authenticationMethods = authenticationMethods;
    this.mfaMethods = mfaMethods;
    this.evmAccounts = evmAccounts;
    this.evmAccountObjects = evmAccountObjects;
    this.evmSmartAccounts = evmSmartAccounts;
    this.evmSmartAccountObjects = evmSmartAccountObjects;
    this.solanaAccounts = solanaAccounts;
    this.solanaAccountObjects = solanaAccountObjects;
    this.createdAt = createdAt;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return A stable, unique identifier for the end user. The <code>userId</code> must be unique across all end users in the developer's CDP Project. It must be between 1 and 100 characters long and can only contain alphanumeric characters and hyphens.
   */
  @JsonProperty("userId")
  public String getUserId() {
    return userId;
  }

  @JsonProperty("authenticationMethods")
  public AuthenticationMethods getAuthenticationMethods() {
    return authenticationMethods;
  }

  @JsonProperty("mfaMethods")
  public Optional<MfaMethods> getMfaMethods() {
    return mfaMethods;
  }

  /**
   * @return <strong>DEPRECATED</strong>: Use <code>evmAccountObjects</code> instead for richer account information. The list of EVM account addresses associated with the end user. End users can have up to 10 EVM accounts.
   */
  @JsonProperty("evmAccounts")
  public List<String> getEvmAccounts() {
    return evmAccounts;
  }

  /**
   * @return The list of EVM accounts associated with the end user. End users can have up to 10 EVM accounts.
   */
  @JsonProperty("evmAccountObjects")
  public List<EndUserEvmAccount> getEvmAccountObjects() {
    return evmAccountObjects;
  }

  /**
   * @return <strong>DEPRECATED</strong>: Use <code>evmSmartAccountObjects</code> instead for richer account information including owner relationships. The list of EVM smart account addresses associated with the end user. Each EVM EOA can own one smart account.
   */
  @JsonProperty("evmSmartAccounts")
  public List<String> getEvmSmartAccounts() {
    return evmSmartAccounts;
  }

  /**
   * @return The list of EVM smart accounts associated with the end user. Each EVM EOA can own one smart account.
   */
  @JsonProperty("evmSmartAccountObjects")
  public List<EndUserEvmSmartAccount> getEvmSmartAccountObjects() {
    return evmSmartAccountObjects;
  }

  /**
   * @return <strong>DEPRECATED</strong>: Use <code>solanaAccountObjects</code> instead for richer account information. The list of Solana account addresses associated with the end user. End users can have up to 10 Solana accounts.
   */
  @JsonProperty("solanaAccounts")
  public List<String> getSolanaAccounts() {
    return solanaAccounts;
  }

  /**
   * @return The list of Solana accounts associated with the end user. End users can have up to 10 Solana accounts.
   */
  @JsonProperty("solanaAccountObjects")
  public List<EndUserSolanaAccount> getSolanaAccountObjects() {
    return solanaAccountObjects;
  }

  /**
   * @return The date and time when the end user was created, in ISO 8601 format.
   */
  @JsonProperty("createdAt")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof EndUser && equalTo((EndUser) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(EndUser other) {
    return userId.equals(other.userId) && authenticationMethods.equals(other.authenticationMethods) && mfaMethods.equals(other.mfaMethods) && evmAccounts.equals(other.evmAccounts) && evmAccountObjects.equals(other.evmAccountObjects) && evmSmartAccounts.equals(other.evmSmartAccounts) && evmSmartAccountObjects.equals(other.evmSmartAccountObjects) && solanaAccounts.equals(other.solanaAccounts) && solanaAccountObjects.equals(other.solanaAccountObjects) && createdAt.equals(other.createdAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.userId, this.authenticationMethods, this.mfaMethods, this.evmAccounts, this.evmAccountObjects, this.evmSmartAccounts, this.evmSmartAccountObjects, this.solanaAccounts, this.solanaAccountObjects, this.createdAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static UserIdStage builder() {
    return new Builder();
  }

  public interface UserIdStage {
    /**
     * <p>A stable, unique identifier for the end user. The <code>userId</code> must be unique across all end users in the developer's CDP Project. It must be between 1 and 100 characters long and can only contain alphanumeric characters and hyphens.</p>
     */
    AuthenticationMethodsStage userId(@NotNull String userId);

    Builder from(EndUser other);
  }

  public interface AuthenticationMethodsStage {
    CreatedAtStage authenticationMethods(@NotNull AuthenticationMethods authenticationMethods);
  }

  public interface CreatedAtStage {
    /**
     * <p>The date and time when the end user was created, in ISO 8601 format.</p>
     */
    _FinalStage createdAt(@NotNull OffsetDateTime createdAt);
  }

  public interface _FinalStage {
    EndUser build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage mfaMethods(Optional<MfaMethods> mfaMethods);

    _FinalStage mfaMethods(MfaMethods mfaMethods);

    /**
     * <p><strong>DEPRECATED</strong>: Use <code>evmAccountObjects</code> instead for richer account information. The list of EVM account addresses associated with the end user. End users can have up to 10 EVM accounts.</p>
     */
    _FinalStage evmAccounts(List<String> evmAccounts);

    _FinalStage addEvmAccounts(String evmAccounts);

    _FinalStage addAllEvmAccounts(List<String> evmAccounts);

    /**
     * <p>The list of EVM accounts associated with the end user. End users can have up to 10 EVM accounts.</p>
     */
    _FinalStage evmAccountObjects(List<EndUserEvmAccount> evmAccountObjects);

    _FinalStage addEvmAccountObjects(EndUserEvmAccount evmAccountObjects);

    _FinalStage addAllEvmAccountObjects(List<EndUserEvmAccount> evmAccountObjects);

    /**
     * <p><strong>DEPRECATED</strong>: Use <code>evmSmartAccountObjects</code> instead for richer account information including owner relationships. The list of EVM smart account addresses associated with the end user. Each EVM EOA can own one smart account.</p>
     */
    _FinalStage evmSmartAccounts(List<String> evmSmartAccounts);

    _FinalStage addEvmSmartAccounts(String evmSmartAccounts);

    _FinalStage addAllEvmSmartAccounts(List<String> evmSmartAccounts);

    /**
     * <p>The list of EVM smart accounts associated with the end user. Each EVM EOA can own one smart account.</p>
     */
    _FinalStage evmSmartAccountObjects(List<EndUserEvmSmartAccount> evmSmartAccountObjects);

    _FinalStage addEvmSmartAccountObjects(EndUserEvmSmartAccount evmSmartAccountObjects);

    _FinalStage addAllEvmSmartAccountObjects(List<EndUserEvmSmartAccount> evmSmartAccountObjects);

    /**
     * <p><strong>DEPRECATED</strong>: Use <code>solanaAccountObjects</code> instead for richer account information. The list of Solana account addresses associated with the end user. End users can have up to 10 Solana accounts.</p>
     */
    _FinalStage solanaAccounts(List<String> solanaAccounts);

    _FinalStage addSolanaAccounts(String solanaAccounts);

    _FinalStage addAllSolanaAccounts(List<String> solanaAccounts);

    /**
     * <p>The list of Solana accounts associated with the end user. End users can have up to 10 Solana accounts.</p>
     */
    _FinalStage solanaAccountObjects(List<EndUserSolanaAccount> solanaAccountObjects);

    _FinalStage addSolanaAccountObjects(EndUserSolanaAccount solanaAccountObjects);

    _FinalStage addAllSolanaAccountObjects(List<EndUserSolanaAccount> solanaAccountObjects);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements UserIdStage, AuthenticationMethodsStage, CreatedAtStage, _FinalStage {
    private String userId;

    private AuthenticationMethods authenticationMethods;

    private OffsetDateTime createdAt;

    private List<EndUserSolanaAccount> solanaAccountObjects = new ArrayList<>();

    private List<String> solanaAccounts = new ArrayList<>();

    private List<EndUserEvmSmartAccount> evmSmartAccountObjects = new ArrayList<>();

    private List<String> evmSmartAccounts = new ArrayList<>();

    private List<EndUserEvmAccount> evmAccountObjects = new ArrayList<>();

    private List<String> evmAccounts = new ArrayList<>();

    private Optional<MfaMethods> mfaMethods = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(EndUser other) {
      userId(other.getUserId());
      authenticationMethods(other.getAuthenticationMethods());
      mfaMethods(other.getMfaMethods());
      evmAccounts(other.getEvmAccounts());
      evmAccountObjects(other.getEvmAccountObjects());
      evmSmartAccounts(other.getEvmSmartAccounts());
      evmSmartAccountObjects(other.getEvmSmartAccountObjects());
      solanaAccounts(other.getSolanaAccounts());
      solanaAccountObjects(other.getSolanaAccountObjects());
      createdAt(other.getCreatedAt());
      return this;
    }

    /**
     * <p>A stable, unique identifier for the end user. The <code>userId</code> must be unique across all end users in the developer's CDP Project. It must be between 1 and 100 characters long and can only contain alphanumeric characters and hyphens.</p>
     * <p>A stable, unique identifier for the end user. The <code>userId</code> must be unique across all end users in the developer's CDP Project. It must be between 1 and 100 characters long and can only contain alphanumeric characters and hyphens.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("userId")
    public AuthenticationMethodsStage userId(@NotNull String userId) {
      this.userId = Objects.requireNonNull(userId, "userId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("authenticationMethods")
    public CreatedAtStage authenticationMethods(
        @NotNull AuthenticationMethods authenticationMethods) {
      this.authenticationMethods = Objects.requireNonNull(authenticationMethods, "authenticationMethods must not be null");
      return this;
    }

    /**
     * <p>The date and time when the end user was created, in ISO 8601 format.</p>
     * <p>The date and time when the end user was created, in ISO 8601 format.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("createdAt")
    public _FinalStage createdAt(@NotNull OffsetDateTime createdAt) {
      this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
      return this;
    }

    /**
     * <p>The list of Solana accounts associated with the end user. End users can have up to 10 Solana accounts.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllSolanaAccountObjects(List<EndUserSolanaAccount> solanaAccountObjects) {
      if (solanaAccountObjects != null) {
        this.solanaAccountObjects.addAll(solanaAccountObjects);
      }
      return this;
    }

    /**
     * <p>The list of Solana accounts associated with the end user. End users can have up to 10 Solana accounts.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addSolanaAccountObjects(EndUserSolanaAccount solanaAccountObjects) {
      this.solanaAccountObjects.add(solanaAccountObjects);
      return this;
    }

    /**
     * <p>The list of Solana accounts associated with the end user. End users can have up to 10 Solana accounts.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "solanaAccountObjects",
        nulls = Nulls.SKIP
    )
    public _FinalStage solanaAccountObjects(List<EndUserSolanaAccount> solanaAccountObjects) {
      this.solanaAccountObjects.clear();
      if (solanaAccountObjects != null) {
        this.solanaAccountObjects.addAll(solanaAccountObjects);
      }
      return this;
    }

    /**
     * <p><strong>DEPRECATED</strong>: Use <code>solanaAccountObjects</code> instead for richer account information. The list of Solana account addresses associated with the end user. End users can have up to 10 Solana accounts.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllSolanaAccounts(List<String> solanaAccounts) {
      if (solanaAccounts != null) {
        this.solanaAccounts.addAll(solanaAccounts);
      }
      return this;
    }

    /**
     * <p><strong>DEPRECATED</strong>: Use <code>solanaAccountObjects</code> instead for richer account information. The list of Solana account addresses associated with the end user. End users can have up to 10 Solana accounts.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addSolanaAccounts(String solanaAccounts) {
      this.solanaAccounts.add(solanaAccounts);
      return this;
    }

    /**
     * <p><strong>DEPRECATED</strong>: Use <code>solanaAccountObjects</code> instead for richer account information. The list of Solana account addresses associated with the end user. End users can have up to 10 Solana accounts.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "solanaAccounts",
        nulls = Nulls.SKIP
    )
    public _FinalStage solanaAccounts(List<String> solanaAccounts) {
      this.solanaAccounts.clear();
      if (solanaAccounts != null) {
        this.solanaAccounts.addAll(solanaAccounts);
      }
      return this;
    }

    /**
     * <p>The list of EVM smart accounts associated with the end user. Each EVM EOA can own one smart account.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllEvmSmartAccountObjects(
        List<EndUserEvmSmartAccount> evmSmartAccountObjects) {
      if (evmSmartAccountObjects != null) {
        this.evmSmartAccountObjects.addAll(evmSmartAccountObjects);
      }
      return this;
    }

    /**
     * <p>The list of EVM smart accounts associated with the end user. Each EVM EOA can own one smart account.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addEvmSmartAccountObjects(EndUserEvmSmartAccount evmSmartAccountObjects) {
      this.evmSmartAccountObjects.add(evmSmartAccountObjects);
      return this;
    }

    /**
     * <p>The list of EVM smart accounts associated with the end user. Each EVM EOA can own one smart account.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "evmSmartAccountObjects",
        nulls = Nulls.SKIP
    )
    public _FinalStage evmSmartAccountObjects(List<EndUserEvmSmartAccount> evmSmartAccountObjects) {
      this.evmSmartAccountObjects.clear();
      if (evmSmartAccountObjects != null) {
        this.evmSmartAccountObjects.addAll(evmSmartAccountObjects);
      }
      return this;
    }

    /**
     * <p><strong>DEPRECATED</strong>: Use <code>evmSmartAccountObjects</code> instead for richer account information including owner relationships. The list of EVM smart account addresses associated with the end user. Each EVM EOA can own one smart account.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllEvmSmartAccounts(List<String> evmSmartAccounts) {
      if (evmSmartAccounts != null) {
        this.evmSmartAccounts.addAll(evmSmartAccounts);
      }
      return this;
    }

    /**
     * <p><strong>DEPRECATED</strong>: Use <code>evmSmartAccountObjects</code> instead for richer account information including owner relationships. The list of EVM smart account addresses associated with the end user. Each EVM EOA can own one smart account.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addEvmSmartAccounts(String evmSmartAccounts) {
      this.evmSmartAccounts.add(evmSmartAccounts);
      return this;
    }

    /**
     * <p><strong>DEPRECATED</strong>: Use <code>evmSmartAccountObjects</code> instead for richer account information including owner relationships. The list of EVM smart account addresses associated with the end user. Each EVM EOA can own one smart account.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "evmSmartAccounts",
        nulls = Nulls.SKIP
    )
    public _FinalStage evmSmartAccounts(List<String> evmSmartAccounts) {
      this.evmSmartAccounts.clear();
      if (evmSmartAccounts != null) {
        this.evmSmartAccounts.addAll(evmSmartAccounts);
      }
      return this;
    }

    /**
     * <p>The list of EVM accounts associated with the end user. End users can have up to 10 EVM accounts.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllEvmAccountObjects(List<EndUserEvmAccount> evmAccountObjects) {
      if (evmAccountObjects != null) {
        this.evmAccountObjects.addAll(evmAccountObjects);
      }
      return this;
    }

    /**
     * <p>The list of EVM accounts associated with the end user. End users can have up to 10 EVM accounts.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addEvmAccountObjects(EndUserEvmAccount evmAccountObjects) {
      this.evmAccountObjects.add(evmAccountObjects);
      return this;
    }

    /**
     * <p>The list of EVM accounts associated with the end user. End users can have up to 10 EVM accounts.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "evmAccountObjects",
        nulls = Nulls.SKIP
    )
    public _FinalStage evmAccountObjects(List<EndUserEvmAccount> evmAccountObjects) {
      this.evmAccountObjects.clear();
      if (evmAccountObjects != null) {
        this.evmAccountObjects.addAll(evmAccountObjects);
      }
      return this;
    }

    /**
     * <p><strong>DEPRECATED</strong>: Use <code>evmAccountObjects</code> instead for richer account information. The list of EVM account addresses associated with the end user. End users can have up to 10 EVM accounts.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllEvmAccounts(List<String> evmAccounts) {
      if (evmAccounts != null) {
        this.evmAccounts.addAll(evmAccounts);
      }
      return this;
    }

    /**
     * <p><strong>DEPRECATED</strong>: Use <code>evmAccountObjects</code> instead for richer account information. The list of EVM account addresses associated with the end user. End users can have up to 10 EVM accounts.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addEvmAccounts(String evmAccounts) {
      this.evmAccounts.add(evmAccounts);
      return this;
    }

    /**
     * <p><strong>DEPRECATED</strong>: Use <code>evmAccountObjects</code> instead for richer account information. The list of EVM account addresses associated with the end user. End users can have up to 10 EVM accounts.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "evmAccounts",
        nulls = Nulls.SKIP
    )
    public _FinalStage evmAccounts(List<String> evmAccounts) {
      this.evmAccounts.clear();
      if (evmAccounts != null) {
        this.evmAccounts.addAll(evmAccounts);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage mfaMethods(MfaMethods mfaMethods) {
      this.mfaMethods = Optional.ofNullable(mfaMethods);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "mfaMethods",
        nulls = Nulls.SKIP
    )
    public _FinalStage mfaMethods(Optional<MfaMethods> mfaMethods) {
      this.mfaMethods = mfaMethods;
      return this;
    }

    @java.lang.Override
    public EndUser build() {
      return new EndUser(userId, authenticationMethods, mfaMethods, evmAccounts, evmAccountObjects, evmSmartAccounts, evmSmartAccountObjects, solanaAccounts, solanaAccountObjects, createdAt, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
