/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class SendEndUserEvmTransactionRuleAction {
  public static final SendEndUserEvmTransactionRuleAction REJECT = new SendEndUserEvmTransactionRuleAction(Value.REJECT, "reject");

  public static final SendEndUserEvmTransactionRuleAction ACCEPT = new SendEndUserEvmTransactionRuleAction(Value.ACCEPT, "accept");

  private final Value value;

  private final String string;

  SendEndUserEvmTransactionRuleAction(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other)
      || (other instanceof SendEndUserEvmTransactionRuleAction && this.string.equals(((SendEndUserEvmTransactionRuleAction) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case REJECT:
        return visitor.visitReject();
      case ACCEPT:
        return visitor.visitAccept();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static SendEndUserEvmTransactionRuleAction valueOf(String value) {
    switch (value) {
      case "reject":
        return REJECT;
      case "accept":
        return ACCEPT;
      default:
        return new SendEndUserEvmTransactionRuleAction(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    REJECT,

    ACCEPT,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitReject();

    T visitAccept();

    T visitUnknown(String unknownType);
  }
}
