/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.types;

import com.coinbase.cdp.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SolanaToken.Builder.class
)
public final class SolanaToken {
  private final Optional<String> symbol;

  private final Optional<String> name;

  private final String mintAddress;

  private final Map<String, Object> additionalProperties;

  private SolanaToken(Optional<String> symbol, Optional<String> name, String mintAddress,
      Map<String, Object> additionalProperties) {
    this.symbol = symbol;
    this.name = name;
    this.mintAddress = mintAddress;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The symbol of this token (ex: SOL, USDC, RAY).
   * The token symbol is not unique. It is possible for two different tokens to have the same symbol.
   * For the native SOL token, this symbol is &quot;SOL&quot;. For SPL tokens, this symbol is defined in the token's metadata.
   * Not all tokens have a symbol. This field will only be populated when the token has metadata available.
   */
  @JsonProperty("symbol")
  public Optional<String> getSymbol() {
    return symbol;
  }

  /**
   * @return The name of this token (ex: &quot;Solana&quot;, &quot;USD Coin&quot;, &quot;Raydium&quot;).
   * The token name is not unique. It is possible for two different tokens to have the same name.
   * For the native SOL token, this name is &quot;Solana&quot;. For SPL tokens, this name is defined in the token's metadata.
   * Not all tokens have a name. This field will only be populated when the token has metadata available.
   */
  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  /**
   * @return The mint address of the token.
   * For native SOL, the mint address is <code>So11111111111111111111111111111111111111111</code>. For SPL tokens, this is the mint address where the token is defined.
   */
  @JsonProperty("mintAddress")
  public String getMintAddress() {
    return mintAddress;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SolanaToken && equalTo((SolanaToken) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SolanaToken other) {
    return symbol.equals(other.symbol) && name.equals(other.name) && mintAddress.equals(other.mintAddress);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.symbol, this.name, this.mintAddress);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static MintAddressStage builder() {
    return new Builder();
  }

  public interface MintAddressStage {
    /**
     * <p>The mint address of the token.
     * For native SOL, the mint address is <code>So11111111111111111111111111111111111111111</code>. For SPL tokens, this is the mint address where the token is defined.</p>
     */
    _FinalStage mintAddress(@NotNull String mintAddress);

    Builder from(SolanaToken other);
  }

  public interface _FinalStage {
    SolanaToken build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>The symbol of this token (ex: SOL, USDC, RAY).
     * The token symbol is not unique. It is possible for two different tokens to have the same symbol.
     * For the native SOL token, this symbol is &quot;SOL&quot;. For SPL tokens, this symbol is defined in the token's metadata.
     * Not all tokens have a symbol. This field will only be populated when the token has metadata available.</p>
     */
    _FinalStage symbol(Optional<String> symbol);

    _FinalStage symbol(String symbol);

    /**
     * <p>The name of this token (ex: &quot;Solana&quot;, &quot;USD Coin&quot;, &quot;Raydium&quot;).
     * The token name is not unique. It is possible for two different tokens to have the same name.
     * For the native SOL token, this name is &quot;Solana&quot;. For SPL tokens, this name is defined in the token's metadata.
     * Not all tokens have a name. This field will only be populated when the token has metadata available.</p>
     */
    _FinalStage name(Optional<String> name);

    _FinalStage name(String name);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements MintAddressStage, _FinalStage {
    private String mintAddress;

    private Optional<String> name = Optional.empty();

    private Optional<String> symbol = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(SolanaToken other) {
      symbol(other.getSymbol());
      name(other.getName());
      mintAddress(other.getMintAddress());
      return this;
    }

    /**
     * <p>The mint address of the token.
     * For native SOL, the mint address is <code>So11111111111111111111111111111111111111111</code>. For SPL tokens, this is the mint address where the token is defined.</p>
     * <p>The mint address of the token.
     * For native SOL, the mint address is <code>So11111111111111111111111111111111111111111</code>. For SPL tokens, this is the mint address where the token is defined.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("mintAddress")
    public _FinalStage mintAddress(@NotNull String mintAddress) {
      this.mintAddress = Objects.requireNonNull(mintAddress, "mintAddress must not be null");
      return this;
    }

    /**
     * <p>The name of this token (ex: &quot;Solana&quot;, &quot;USD Coin&quot;, &quot;Raydium&quot;).
     * The token name is not unique. It is possible for two different tokens to have the same name.
     * For the native SOL token, this name is &quot;Solana&quot;. For SPL tokens, this name is defined in the token's metadata.
     * Not all tokens have a name. This field will only be populated when the token has metadata available.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    /**
     * <p>The name of this token (ex: &quot;Solana&quot;, &quot;USD Coin&quot;, &quot;Raydium&quot;).
     * The token name is not unique. It is possible for two different tokens to have the same name.
     * For the native SOL token, this name is &quot;Solana&quot;. For SPL tokens, this name is defined in the token's metadata.
     * Not all tokens have a name. This field will only be populated when the token has metadata available.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public _FinalStage name(Optional<String> name) {
      this.name = name;
      return this;
    }

    /**
     * <p>The symbol of this token (ex: SOL, USDC, RAY).
     * The token symbol is not unique. It is possible for two different tokens to have the same symbol.
     * For the native SOL token, this symbol is &quot;SOL&quot;. For SPL tokens, this symbol is defined in the token's metadata.
     * Not all tokens have a symbol. This field will only be populated when the token has metadata available.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage symbol(String symbol) {
      this.symbol = Optional.ofNullable(symbol);
      return this;
    }

    /**
     * <p>The symbol of this token (ex: SOL, USDC, RAY).
     * The token symbol is not unique. It is possible for two different tokens to have the same symbol.
     * For the native SOL token, this symbol is &quot;SOL&quot;. For SPL tokens, this symbol is defined in the token's metadata.
     * Not all tokens have a symbol. This field will only be populated when the token has metadata available.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "symbol",
        nulls = Nulls.SKIP
    )
    public _FinalStage symbol(Optional<String> symbol) {
      this.symbol = symbol;
      return this;
    }

    @java.lang.Override
    public SolanaToken build() {
      return new SolanaToken(symbol, name, mintAddress, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
