/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.types;

import com.coinbase.cdp.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SolDataParameterConditionList.Builder.class
)
public final class SolDataParameterConditionList {
  private final String name;

  private final SolDataParameterConditionListOperator operator;

  private final List<String> values;

  private final Map<String, Object> additionalProperties;

  private SolDataParameterConditionList(String name, SolDataParameterConditionListOperator operator,
      List<String> values, Map<String, Object> additionalProperties) {
    this.name = name;
    this.operator = operator;
    this.values = values;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The parameter name.
   */
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  /**
   * @return The operator to use for the comparison. The value resolved at the <code>name</code> will be on the left-hand side of the operator, and the <code>value</code> field will be on the right-hand side.
   */
  @JsonProperty("operator")
  public SolDataParameterConditionListOperator getOperator() {
    return operator;
  }

  /**
   * @return The values to compare against.
   */
  @JsonProperty("values")
  public List<String> getValues() {
    return values;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SolDataParameterConditionList && equalTo((SolDataParameterConditionList) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SolDataParameterConditionList other) {
    return name.equals(other.name) && operator.equals(other.operator) && values.equals(other.values);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.operator, this.values);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NameStage builder() {
    return new Builder();
  }

  public interface NameStage {
    /**
     * <p>The parameter name.</p>
     */
    OperatorStage name(@NotNull String name);

    Builder from(SolDataParameterConditionList other);
  }

  public interface OperatorStage {
    /**
     * <p>The operator to use for the comparison. The value resolved at the <code>name</code> will be on the left-hand side of the operator, and the <code>value</code> field will be on the right-hand side.</p>
     */
    _FinalStage operator(@NotNull SolDataParameterConditionListOperator operator);
  }

  public interface _FinalStage {
    SolDataParameterConditionList build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>The values to compare against.</p>
     */
    _FinalStage values(List<String> values);

    _FinalStage addValues(String values);

    _FinalStage addAllValues(List<String> values);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NameStage, OperatorStage, _FinalStage {
    private String name;

    private SolDataParameterConditionListOperator operator;

    private List<String> values = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(SolDataParameterConditionList other) {
      name(other.getName());
      operator(other.getOperator());
      values(other.getValues());
      return this;
    }

    /**
     * <p>The parameter name.</p>
     * <p>The parameter name.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("name")
    public OperatorStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    /**
     * <p>The operator to use for the comparison. The value resolved at the <code>name</code> will be on the left-hand side of the operator, and the <code>value</code> field will be on the right-hand side.</p>
     * <p>The operator to use for the comparison. The value resolved at the <code>name</code> will be on the left-hand side of the operator, and the <code>value</code> field will be on the right-hand side.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("operator")
    public _FinalStage operator(@NotNull SolDataParameterConditionListOperator operator) {
      this.operator = Objects.requireNonNull(operator, "operator must not be null");
      return this;
    }

    /**
     * <p>The values to compare against.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllValues(List<String> values) {
      if (values != null) {
        this.values.addAll(values);
      }
      return this;
    }

    /**
     * <p>The values to compare against.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addValues(String values) {
      this.values.add(values);
      return this;
    }

    /**
     * <p>The values to compare against.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "values",
        nulls = Nulls.SKIP
    )
    public _FinalStage values(List<String> values) {
      this.values.clear();
      if (values != null) {
        this.values.addAll(values);
      }
      return this;
    }

    @java.lang.Override
    public SolDataParameterConditionList build() {
      return new SolDataParameterConditionList(name, operator, values, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
