/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.types;

import com.coinbase.cdp.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TokenFee.Builder.class
)
public final class TokenFee {
  private final String amount;

  private final String token;

  private final Map<String, Object> additionalProperties;

  private TokenFee(String amount, String token, Map<String, Object> additionalProperties) {
    this.amount = amount;
    this.token = token;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The estimated amount of the fee in atomic units of the <code>token</code>. For example, <code>1000000000000000</code> if the fee is in ETH equates to 0.001 ETH, <code>10000</code> if the fee is in USDC equates to 0.01 USDC, etc.
   */
  @JsonProperty("amount")
  public String getAmount() {
    return amount;
  }

  /**
   * @return The contract address of the token that the fee is paid in. The address <code>0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE</code> is used for the native token of the network (e.g. ETH).
   */
  @JsonProperty("token")
  public String getToken() {
    return token;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TokenFee && equalTo((TokenFee) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TokenFee other) {
    return amount.equals(other.amount) && token.equals(other.token);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.amount, this.token);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static AmountStage builder() {
    return new Builder();
  }

  public interface AmountStage {
    /**
     * <p>The estimated amount of the fee in atomic units of the <code>token</code>. For example, <code>1000000000000000</code> if the fee is in ETH equates to 0.001 ETH, <code>10000</code> if the fee is in USDC equates to 0.01 USDC, etc.</p>
     */
    TokenStage amount(@NotNull String amount);

    Builder from(TokenFee other);
  }

  public interface TokenStage {
    /**
     * <p>The contract address of the token that the fee is paid in. The address <code>0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE</code> is used for the native token of the network (e.g. ETH).</p>
     */
    _FinalStage token(@NotNull String token);
  }

  public interface _FinalStage {
    TokenFee build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements AmountStage, TokenStage, _FinalStage {
    private String amount;

    private String token;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(TokenFee other) {
      amount(other.getAmount());
      token(other.getToken());
      return this;
    }

    /**
     * <p>The estimated amount of the fee in atomic units of the <code>token</code>. For example, <code>1000000000000000</code> if the fee is in ETH equates to 0.001 ETH, <code>10000</code> if the fee is in USDC equates to 0.01 USDC, etc.</p>
     * <p>The estimated amount of the fee in atomic units of the <code>token</code>. For example, <code>1000000000000000</code> if the fee is in ETH equates to 0.001 ETH, <code>10000</code> if the fee is in USDC equates to 0.01 USDC, etc.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("amount")
    public TokenStage amount(@NotNull String amount) {
      this.amount = Objects.requireNonNull(amount, "amount must not be null");
      return this;
    }

    /**
     * <p>The contract address of the token that the fee is paid in. The address <code>0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE</code> is used for the native token of the network (e.g. ETH).</p>
     * <p>The contract address of the token that the fee is paid in. The address <code>0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE</code> is used for the native token of the network (e.g. ETH).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("token")
    public _FinalStage token(@NotNull String token) {
      this.token = Objects.requireNonNull(token, "token must not be null");
      return this;
    }

    @java.lang.Override
    public TokenFee build() {
      return new TokenFee(amount, token, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
