/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.types;

import com.coinbase.cdp.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TransferDetailsOnchainTransactionsItem.Builder.class
)
public final class TransferDetailsOnchainTransactionsItem {
  private final String transactionHash;

  private final PaymentNetwork network;

  private final Map<String, Object> additionalProperties;

  private TransferDetailsOnchainTransactionsItem(String transactionHash, PaymentNetwork network,
      Map<String, Object> additionalProperties) {
    this.transactionHash = transactionHash;
    this.network = network;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The transaction hash.
   */
  @JsonProperty("transactionHash")
  public String getTransactionHash() {
    return transactionHash;
  }

  @JsonProperty("network")
  public PaymentNetwork getNetwork() {
    return network;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TransferDetailsOnchainTransactionsItem && equalTo((TransferDetailsOnchainTransactionsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TransferDetailsOnchainTransactionsItem other) {
    return transactionHash.equals(other.transactionHash) && network.equals(other.network);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.transactionHash, this.network);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TransactionHashStage builder() {
    return new Builder();
  }

  public interface TransactionHashStage {
    /**
     * <p>The transaction hash.</p>
     */
    NetworkStage transactionHash(@NotNull String transactionHash);

    Builder from(TransferDetailsOnchainTransactionsItem other);
  }

  public interface NetworkStage {
    _FinalStage network(@NotNull PaymentNetwork network);
  }

  public interface _FinalStage {
    TransferDetailsOnchainTransactionsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TransactionHashStage, NetworkStage, _FinalStage {
    private String transactionHash;

    private PaymentNetwork network;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(TransferDetailsOnchainTransactionsItem other) {
      transactionHash(other.getTransactionHash());
      network(other.getNetwork());
      return this;
    }

    /**
     * <p>The transaction hash.</p>
     * <p>The transaction hash.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("transactionHash")
    public NetworkStage transactionHash(@NotNull String transactionHash) {
      this.transactionHash = Objects.requireNonNull(transactionHash, "transactionHash must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("network")
    public _FinalStage network(@NotNull PaymentNetwork network) {
      this.network = Objects.requireNonNull(network, "network must not be null");
      return this;
    }

    @java.lang.Override
    public TransferDetailsOnchainTransactionsItem build() {
      return new TransferDetailsOnchainTransactionsItem(transactionHash, network, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
