/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.types;

import com.coinbase.cdp.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TransferFee.Builder.class
)
public final class TransferFee {
  private final TransferFeeType type;

  private final String amount;

  private final Asset asset;

  private final Map<String, Object> additionalProperties;

  private TransferFee(TransferFeeType type, String amount, Asset asset,
      Map<String, Object> additionalProperties) {
    this.type = type;
    this.amount = amount;
    this.asset = asset;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The type of the fee, indicating its purpose.
   */
  @JsonProperty("type")
  public TransferFeeType getType() {
    return type;
  }

  /**
   * @return The amount of the fee in units of the asset specified by <code>asset</code>.
   */
  @JsonProperty("amount")
  public String getAmount() {
    return amount;
  }

  /**
   * @return The asset symbol.
   */
  @JsonProperty("asset")
  public Asset getAsset() {
    return asset;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TransferFee && equalTo((TransferFee) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TransferFee other) {
    return type.equals(other.type) && amount.equals(other.amount) && asset.equals(other.asset);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type, this.amount, this.asset);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TypeStage builder() {
    return new Builder();
  }

  public interface TypeStage {
    /**
     * <p>The type of the fee, indicating its purpose.</p>
     */
    AmountStage type(@NotNull TransferFeeType type);

    Builder from(TransferFee other);
  }

  public interface AmountStage {
    /**
     * <p>The amount of the fee in units of the asset specified by <code>asset</code>.</p>
     */
    AssetStage amount(@NotNull String amount);
  }

  public interface AssetStage {
    /**
     * <p>The asset symbol.</p>
     */
    _FinalStage asset(@NotNull Asset asset);
  }

  public interface _FinalStage {
    TransferFee build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TypeStage, AmountStage, AssetStage, _FinalStage {
    private TransferFeeType type;

    private String amount;

    private Asset asset;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(TransferFee other) {
      type(other.getType());
      amount(other.getAmount());
      asset(other.getAsset());
      return this;
    }

    /**
     * <p>The type of the fee, indicating its purpose.</p>
     * <p>The type of the fee, indicating its purpose.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("type")
    public AmountStage type(@NotNull TransferFeeType type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    /**
     * <p>The amount of the fee in units of the asset specified by <code>asset</code>.</p>
     * <p>The amount of the fee in units of the asset specified by <code>asset</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("amount")
    public AssetStage amount(@NotNull String amount) {
      this.amount = Objects.requireNonNull(amount, "amount must not be null");
      return this;
    }

    /**
     * <p>The asset symbol.</p>
     * <p>The asset symbol.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("asset")
    public _FinalStage asset(@NotNull Asset asset) {
      this.asset = Objects.requireNonNull(asset, "asset must not be null");
      return this;
    }

    @java.lang.Override
    public TransferFee build() {
      return new TransferFee(type, amount, asset, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
