/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.types;

import com.coinbase.cdp.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import java.io.IOException;
import java.lang.IllegalStateException;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Map;
import java.util.Objects;

@JsonDeserialize(
    using = TransferSource.Deserializer.class
)
public final class TransferSource {
  private final Object value;

  private final int type;

  private TransferSource(Object value, int type) {
    this.value = value;
    this.type = type;
  }

  @JsonValue
  public Object get() {
    return this.value;
  }

  @SuppressWarnings("unchecked")
  public <T> T visit(Visitor<T> visitor) {
    if(this.type == 0) {
      return visitor.visit((TransfersAccount) this.value);
    } else if(this.type == 1) {
      return visitor.visit((PaymentMethod) this.value);
    } else if(this.type == 2) {
      return visitor.visit((OnchainAddress) this.value);
    } else if(this.type == 3) {
      return visitor.visit((AchDepositSource) this.value);
    } else if(this.type == 4) {
      return visitor.visit((FedwireDepositSource) this.value);
    }
    throw new IllegalStateException("Failed to visit value. This should never happen.");
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TransferSource && equalTo((TransferSource) other);
  }

  private boolean equalTo(TransferSource other) {
    return value.equals(other.value);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.value);
  }

  @java.lang.Override
  public String toString() {
    return this.value.toString();
  }

  public static TransferSource of(TransfersAccount value) {
    return new TransferSource(value, 0);
  }

  public static TransferSource of(PaymentMethod value) {
    return new TransferSource(value, 1);
  }

  public static TransferSource of(OnchainAddress value) {
    return new TransferSource(value, 2);
  }

  public static TransferSource of(AchDepositSource value) {
    return new TransferSource(value, 3);
  }

  public static TransferSource of(FedwireDepositSource value) {
    return new TransferSource(value, 4);
  }

  public interface Visitor<T> {
    T visit(TransfersAccount value);

    T visit(PaymentMethod value);

    T visit(OnchainAddress value);

    T visit(AchDepositSource value);

    T visit(FedwireDepositSource value);
  }

  static final class Deserializer extends StdDeserializer<TransferSource> {
    Deserializer() {
      super(TransferSource.class);
    }

    @java.lang.Override
    public TransferSource deserialize(JsonParser p, DeserializationContext context) throws
        IOException {
      Object value = p.readValueAs(Object.class);
      if (value instanceof Map<?, ?> && ((Map<?, ?>) value).containsKey("accountId") && ((Map<?, ?>) value).containsKey("asset")) {
        try {
          return of(ObjectMappers.JSON_MAPPER.convertValue(value, TransfersAccount.class));
        } catch(RuntimeException e) {
        }
      }
      if (value instanceof Map<?, ?> && ((Map<?, ?>) value).containsKey("paymentMethodId") && ((Map<?, ?>) value).containsKey("asset")) {
        try {
          return of(ObjectMappers.JSON_MAPPER.convertValue(value, PaymentMethod.class));
        } catch(RuntimeException e) {
        }
      }
      if (value instanceof Map<?, ?> && ((Map<?, ?>) value).containsKey("address") && ((Map<?, ?>) value).containsKey("network") && ((Map<?, ?>) value).containsKey("asset")) {
        try {
          return of(ObjectMappers.JSON_MAPPER.convertValue(value, OnchainAddress.class));
        } catch(RuntimeException e) {
        }
      }
      if (value instanceof Map<?, ?> && ((Map<?, ?>) value).containsKey("currency") && ((Map<?, ?>) value).containsKey("companyName") && ((Map<?, ?>) value).containsKey("companyEntryDescription")) {
        try {
          return of(ObjectMappers.JSON_MAPPER.convertValue(value, AchDepositSource.class));
        } catch(RuntimeException e) {
        }
      }
      if (value instanceof Map<?, ?> && ((Map<?, ?>) value).containsKey("currency") && ((Map<?, ?>) value).containsKey("omad") && ((Map<?, ?>) value).containsKey("accountNumber") && ((Map<?, ?>) value).containsKey("originatorName")) {
        try {
          return of(ObjectMappers.JSON_MAPPER.convertValue(value, FedwireDepositSource.class));
        } catch(RuntimeException e) {
        }
      }
      throw new JsonParseException(p, "Failed to deserialize");
    }
  }
}
