/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.types;

import com.coinbase.cdp.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TransferEstimate.Builder.class
)
public final class TransferEstimate {
  private final Optional<TransferExchangeRate> exchangeRate;

  private final Optional<String> targetAmount;

  private final Optional<Asset> targetAsset;

  private final Optional<TransferFees> fees;

  private final OffsetDateTime estimatedAt;

  private final Map<String, Object> additionalProperties;

  private TransferEstimate(Optional<TransferExchangeRate> exchangeRate,
      Optional<String> targetAmount, Optional<Asset> targetAsset, Optional<TransferFees> fees,
      OffsetDateTime estimatedAt, Map<String, Object> additionalProperties) {
    this.exchangeRate = exchangeRate;
    this.targetAmount = targetAmount;
    this.targetAsset = targetAsset;
    this.fees = fees;
    this.estimatedAt = estimatedAt;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The estimated exchange rate at the time this estimate was captured.
   */
  @JsonProperty("exchangeRate")
  public Optional<TransferExchangeRate> getExchangeRate() {
    return exchangeRate;
  }

  /**
   * @return Estimated amount of the target asset that will be received, as a decimal string in standard unit denomination.
   */
  @JsonProperty("targetAmount")
  public Optional<String> getTargetAmount() {
    return targetAmount;
  }

  /**
   * @return The asset symbol of the estimated target amount.
   */
  @JsonProperty("targetAsset")
  public Optional<Asset> getTargetAsset() {
    return targetAsset;
  }

  /**
   * @return The estimated fees at the time this estimate was captured.
   */
  @JsonProperty("fees")
  public Optional<TransferFees> getFees() {
    return fees;
  }

  /**
   * @return The date and time when this estimate was captured.
   */
  @JsonProperty("estimatedAt")
  public OffsetDateTime getEstimatedAt() {
    return estimatedAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TransferEstimate && equalTo((TransferEstimate) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TransferEstimate other) {
    return exchangeRate.equals(other.exchangeRate) && targetAmount.equals(other.targetAmount) && targetAsset.equals(other.targetAsset) && fees.equals(other.fees) && estimatedAt.equals(other.estimatedAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.exchangeRate, this.targetAmount, this.targetAsset, this.fees, this.estimatedAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static EstimatedAtStage builder() {
    return new Builder();
  }

  public interface EstimatedAtStage {
    /**
     * <p>The date and time when this estimate was captured.</p>
     */
    _FinalStage estimatedAt(@NotNull OffsetDateTime estimatedAt);

    Builder from(TransferEstimate other);
  }

  public interface _FinalStage {
    TransferEstimate build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>The estimated exchange rate at the time this estimate was captured.</p>
     */
    _FinalStage exchangeRate(Optional<TransferExchangeRate> exchangeRate);

    _FinalStage exchangeRate(TransferExchangeRate exchangeRate);

    /**
     * <p>Estimated amount of the target asset that will be received, as a decimal string in standard unit denomination.</p>
     */
    _FinalStage targetAmount(Optional<String> targetAmount);

    _FinalStage targetAmount(String targetAmount);

    /**
     * <p>The asset symbol of the estimated target amount.</p>
     */
    _FinalStage targetAsset(Optional<Asset> targetAsset);

    _FinalStage targetAsset(Asset targetAsset);

    /**
     * <p>The estimated fees at the time this estimate was captured.</p>
     */
    _FinalStage fees(Optional<TransferFees> fees);

    _FinalStage fees(TransferFees fees);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements EstimatedAtStage, _FinalStage {
    private OffsetDateTime estimatedAt;

    private Optional<TransferFees> fees = Optional.empty();

    private Optional<Asset> targetAsset = Optional.empty();

    private Optional<String> targetAmount = Optional.empty();

    private Optional<TransferExchangeRate> exchangeRate = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(TransferEstimate other) {
      exchangeRate(other.getExchangeRate());
      targetAmount(other.getTargetAmount());
      targetAsset(other.getTargetAsset());
      fees(other.getFees());
      estimatedAt(other.getEstimatedAt());
      return this;
    }

    /**
     * <p>The date and time when this estimate was captured.</p>
     * <p>The date and time when this estimate was captured.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("estimatedAt")
    public _FinalStage estimatedAt(@NotNull OffsetDateTime estimatedAt) {
      this.estimatedAt = Objects.requireNonNull(estimatedAt, "estimatedAt must not be null");
      return this;
    }

    /**
     * <p>The estimated fees at the time this estimate was captured.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage fees(TransferFees fees) {
      this.fees = Optional.ofNullable(fees);
      return this;
    }

    /**
     * <p>The estimated fees at the time this estimate was captured.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "fees",
        nulls = Nulls.SKIP
    )
    public _FinalStage fees(Optional<TransferFees> fees) {
      this.fees = fees;
      return this;
    }

    /**
     * <p>The asset symbol of the estimated target amount.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage targetAsset(Asset targetAsset) {
      this.targetAsset = Optional.ofNullable(targetAsset);
      return this;
    }

    /**
     * <p>The asset symbol of the estimated target amount.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "targetAsset",
        nulls = Nulls.SKIP
    )
    public _FinalStage targetAsset(Optional<Asset> targetAsset) {
      this.targetAsset = targetAsset;
      return this;
    }

    /**
     * <p>Estimated amount of the target asset that will be received, as a decimal string in standard unit denomination.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage targetAmount(String targetAmount) {
      this.targetAmount = Optional.ofNullable(targetAmount);
      return this;
    }

    /**
     * <p>Estimated amount of the target asset that will be received, as a decimal string in standard unit denomination.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "targetAmount",
        nulls = Nulls.SKIP
    )
    public _FinalStage targetAmount(Optional<String> targetAmount) {
      this.targetAmount = targetAmount;
      return this;
    }

    /**
     * <p>The estimated exchange rate at the time this estimate was captured.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage exchangeRate(TransferExchangeRate exchangeRate) {
      this.exchangeRate = Optional.ofNullable(exchangeRate);
      return this;
    }

    /**
     * <p>The estimated exchange rate at the time this estimate was captured.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "exchangeRate",
        nulls = Nulls.SKIP
    )
    public _FinalStage exchangeRate(Optional<TransferExchangeRate> exchangeRate) {
      this.exchangeRate = exchangeRate;
      return this;
    }

    @java.lang.Override
    public TransferEstimate build() {
      return new TransferEstimate(exchangeRate, targetAmount, targetAsset, fees, estimatedAt, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
