# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdp.openapi_client.models.acceptance_disbursement_failed_event import AcceptanceDisbursementFailedEvent

class TestAcceptanceDisbursementFailedEvent(unittest.TestCase):
    """AcceptanceDisbursementFailedEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AcceptanceDisbursementFailedEvent:
        """Test AcceptanceDisbursementFailedEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AcceptanceDisbursementFailedEvent`
        """
        model = AcceptanceDisbursementFailedEvent()
        if include_optional:
            return AcceptanceDisbursementFailedEvent(
                event_id = '123e4567-e89b-12d3-a456-426614174000',
                timestamp = '2025-06-01T12:00:00Z',
                data = {disbursementId=disbursement_82c879c1-84e1-44ed-a8c2-1ac239cf09ad, source={accountId=account_af2937b0-9846-4fe7-bfe9-ccc22d935114, asset=usdc}, target={coinbaseUserId=coinbase_user_abc123}, amount=25.00, asset=usdc, status=pending, reason=Goodwill disbursement for delayed shipment., externalReferenceId=disbursement-2026-04-1234, metadata={customer_id=cust_12345, order_id=order_67890}, createdAt=2026-04-17T17:00:00.000Z, updatedAt=2026-04-17T17:00:00.000Z},
                event_type = 'acceptance.disbursement.failed'
            )
        else:
            return AcceptanceDisbursementFailedEvent(
                event_id = '123e4567-e89b-12d3-a456-426614174000',
                timestamp = '2025-06-01T12:00:00Z',
                data = {disbursementId=disbursement_82c879c1-84e1-44ed-a8c2-1ac239cf09ad, source={accountId=account_af2937b0-9846-4fe7-bfe9-ccc22d935114, asset=usdc}, target={coinbaseUserId=coinbase_user_abc123}, amount=25.00, asset=usdc, status=pending, reason=Goodwill disbursement for delayed shipment., externalReferenceId=disbursement-2026-04-1234, metadata={customer_id=cust_12345, order_id=order_67890}, createdAt=2026-04-17T17:00:00.000Z, updatedAt=2026-04-17T17:00:00.000Z},
                event_type = 'acceptance.disbursement.failed',
        )
        """

    def testAcceptanceDisbursementFailedEvent(self):
        """Test AcceptanceDisbursementFailedEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
