# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdp.openapi_client.models.onramp_limit_upgrade_option import OnrampLimitUpgradeOption

class TestOnrampLimitUpgradeOption(unittest.TestCase):
    """OnrampLimitUpgradeOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OnrampLimitUpgradeOption:
        """Test OnrampLimitUpgradeOption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OnrampLimitUpgradeOption`
        """
        model = OnrampLimitUpgradeOption()
        if include_optional:
            return OnrampLimitUpgradeOption(
                status = 'unrequested',
                fields = [ssnLast4, dateOfBirth],
                limit_upgrades = [{limitType=weekly_spending, maxUpgrade=2500}, {limitType=lifetime_transactions, maxUpgrade=2147483647}]
            )
        else:
            return OnrampLimitUpgradeOption(
                status = 'unrequested',
                fields = [ssnLast4, dateOfBirth],
                limit_upgrades = [{limitType=weekly_spending, maxUpgrade=2500}, {limitType=lifetime_transactions, maxUpgrade=2147483647}],
        )
        """

    def testOnrampLimitUpgradeOption(self):
        """Test OnrampLimitUpgradeOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
