# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdp.openapi_client.models.x402_batch_settlement_evm_payload import X402BatchSettlementEvmPayload

class TestX402BatchSettlementEvmPayload(unittest.TestCase):
    """X402BatchSettlementEvmPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> X402BatchSettlementEvmPayload:
        """Test X402BatchSettlementEvmPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `X402BatchSettlementEvmPayload`
        """
        model = X402BatchSettlementEvmPayload()
        if include_optional:
            return X402BatchSettlementEvmPayload(
                type = 'deposit',
                channel_config = {payer=0x857b06519E91e3A54538791bDbb0E22373e36b66, payerAuthorizer=0x857b06519E91e3A54538791bDbb0E22373e36b66, receiver=0x209693Bc6afc0C5328bA36FaF03C514EF312287C, receiverAuthorizer=0x1111111111111111111111111111111111111111, token=0x036CbD53842c5426634e7929541eC2318f3dCF7e, withdrawDelay=86400, salt=0x0000000000000000000000000000000000000000000000000000000000000001},
                voucher = {channelId=0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890, maxClaimableAmount=5000000, signature=0xf3746613c2d920b5fdabc0856f2aeb2d4f88ee6037b8cc5d04a71a4462f134801234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1b},
                deposit = cdp.openapi_client.models.x402_batch_settlement_deposit_payload_deposit.x402BatchSettlementDepositPayload_deposit(
                    amount = '10000000', 
                    authorization = cdp.openapi_client.models.x402_batch_settlement_deposit_payload_deposit_authorization.x402BatchSettlementDepositPayload_deposit_authorization(
                        erc3009_authorization = cdp.openapi_client.models.x402_batch_settlement_deposit_payload_deposit_authorization_erc3009_authorization.x402BatchSettlementDepositPayload_deposit_authorization_erc3009Authorization(
                            valid_after = '1716150000', 
                            valid_before = '1716160000', 
                            salt = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef', 
                            signature = '0xf3746613c2d920b5fdabc0856f2aeb2d4f88ee6037b8cc5d04a71a4462f134801234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1b', ), ), ),
                amount = '1000000',
                refund_nonce = '1',
                claims = [
                    {voucher={channel={payer=0x857b06519E91e3A54538791bDbb0E22373e36b66, payerAuthorizer=0x857b06519E91e3A54538791bDbb0E22373e36b66, receiver=0x209693Bc6afc0C5328bA36FaF03C514EF312287C, receiverAuthorizer=0x1111111111111111111111111111111111111111, token=0x036CbD53842c5426634e7929541eC2318f3dCF7e, withdrawDelay=86400, salt=0x0000000000000000000000000000000000000000000000000000000000000001}, maxClaimableAmount=5000000}, signature=0xf3746613c2d920b5fdabc0856f2aeb2d4f88ee6037b8cc5d04a71a4462f134801234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1b, totalClaimed=3000000}
                    ],
                refund_authorizer_signature = '0x2',
                claim_authorizer_signature = '0x2',
                receiver = '0x209693Bc6afc0C5328bA36FaF03C514EF312287C',
                token = '0x036CbD53842c5426634e7929541eC2318f3dCF7e'
            )
        else:
            return X402BatchSettlementEvmPayload(
                type = 'deposit',
                channel_config = {payer=0x857b06519E91e3A54538791bDbb0E22373e36b66, payerAuthorizer=0x857b06519E91e3A54538791bDbb0E22373e36b66, receiver=0x209693Bc6afc0C5328bA36FaF03C514EF312287C, receiverAuthorizer=0x1111111111111111111111111111111111111111, token=0x036CbD53842c5426634e7929541eC2318f3dCF7e, withdrawDelay=86400, salt=0x0000000000000000000000000000000000000000000000000000000000000001},
                voucher = {channelId=0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890, maxClaimableAmount=5000000, signature=0xf3746613c2d920b5fdabc0856f2aeb2d4f88ee6037b8cc5d04a71a4462f134801234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1b},
                deposit = cdp.openapi_client.models.x402_batch_settlement_deposit_payload_deposit.x402BatchSettlementDepositPayload_deposit(
                    amount = '10000000', 
                    authorization = cdp.openapi_client.models.x402_batch_settlement_deposit_payload_deposit_authorization.x402BatchSettlementDepositPayload_deposit_authorization(
                        erc3009_authorization = cdp.openapi_client.models.x402_batch_settlement_deposit_payload_deposit_authorization_erc3009_authorization.x402BatchSettlementDepositPayload_deposit_authorization_erc3009Authorization(
                            valid_after = '1716150000', 
                            valid_before = '1716160000', 
                            salt = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef', 
                            signature = '0xf3746613c2d920b5fdabc0856f2aeb2d4f88ee6037b8cc5d04a71a4462f134801234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1b', ), ), ),
                claims = [
                    {voucher={channel={payer=0x857b06519E91e3A54538791bDbb0E22373e36b66, payerAuthorizer=0x857b06519E91e3A54538791bDbb0E22373e36b66, receiver=0x209693Bc6afc0C5328bA36FaF03C514EF312287C, receiverAuthorizer=0x1111111111111111111111111111111111111111, token=0x036CbD53842c5426634e7929541eC2318f3dCF7e, withdrawDelay=86400, salt=0x0000000000000000000000000000000000000000000000000000000000000001}, maxClaimableAmount=5000000}, signature=0xf3746613c2d920b5fdabc0856f2aeb2d4f88ee6037b8cc5d04a71a4462f134801234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1b, totalClaimed=3000000}
                    ],
                receiver = '0x209693Bc6afc0C5328bA36FaF03C514EF312287C',
                token = '0x036CbD53842c5426634e7929541eC2318f3dCF7e',
        )
        """

    def testX402BatchSettlementEvmPayload(self):
        """Test X402BatchSettlementEvmPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
