# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdp.openapi_client.models.balance import Balance

class TestBalance(unittest.TestCase):
    """Balance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Balance:
        """Test Balance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Balance`
        """
        model = Balance()
        if include_optional:
            return Balance(
                asset = {symbol=btc, type=crypto, name=Bitcoin, decimals=8},
                amount = {
                    'key' : cdp.openapi_client.models.amount_detail.AmountDetail(
                        available = '2.5', 
                        total = '3.0', )
                    }
            )
        else:
            return Balance(
                asset = {symbol=btc, type=crypto, name=Bitcoin, decimals=8},
                amount = {
                    'key' : cdp.openapi_client.models.amount_detail.AmountDetail(
                        available = '2.5', 
                        total = '3.0', )
                    },
        )
        """

    def testBalance(self):
        """Test Balance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
