# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdp.openapi_client.models.list_customers200_response import ListCustomers200Response

class TestListCustomers200Response(unittest.TestCase):
    """ListCustomers200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCustomers200Response:
        """Test ListCustomers200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCustomers200Response`
        """
        model = ListCustomers200Response()
        if include_optional:
            return ListCustomers200Response(
                next_page_token = 'eyJsYXN0X2lkIjogImFiYzEyMyIsICJ0aW1lc3RhbXAiOiAxNzA3ODIzNzAxfQ==',
                customers = [
                    cdp.openapi_client.models.customer.Customer(
                        customer_id = 'customer_af2937b0-9846-4fe7-bfe9-ccc22d935114', 
                        type = 'individual', 
                        capabilities = {}, 
                        requirements = {}, 
                        created_at = '2026-01-10T14:25:00Z', 
                        updated_at = '2026-01-10T14:30:00Z', 
                        individual = {firstName=Jane, lastName=Doe, email=jane.doe@example.com}, 
                        project_ids = [], 
                        tos_acceptances = [{versionId=us_individual_2026-05-29, language=en, acceptedAt=2026-04-10T12:00:00Z}], )
                    ]
            )
        else:
            return ListCustomers200Response(
                customers = [
                    cdp.openapi_client.models.customer.Customer(
                        customer_id = 'customer_af2937b0-9846-4fe7-bfe9-ccc22d935114', 
                        type = 'individual', 
                        capabilities = {}, 
                        requirements = {}, 
                        created_at = '2026-01-10T14:25:00Z', 
                        updated_at = '2026-01-10T14:30:00Z', 
                        individual = {firstName=Jane, lastName=Doe, email=jane.doe@example.com}, 
                        project_ids = [], 
                        tos_acceptances = [{versionId=us_individual_2026-05-29, language=en, acceptedAt=2026-04-10T12:00:00Z}], )
                    ],
        )
        """

    def testListCustomers200Response(self):
        """Test ListCustomers200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
