# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdp.openapi_client.models.customer_write_base import CustomerWriteBase

class TestCustomerWriteBase(unittest.TestCase):
    """CustomerWriteBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerWriteBase:
        """Test CustomerWriteBase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerWriteBase`
        """
        model = CustomerWriteBase()
        if include_optional:
            return CustomerWriteBase(
                type = 'individual',
                capabilities = {custodyCrypto={requested=true}, transferCrypto={requested=true}},
                individual = {firstName=Jane, lastName=Doe, address={line1=500 Main St, city=Boston, state=MA, postCode=02108, countryCode=US}, ssnLast4=6789, dateOfBirth={day=15, month=08, year=1990}, email=jane.doe@example.com, phoneNumber=+15551234567},
                project_ids = [],
                tos_acceptances = [{versionId=us_individual_2026-05-29, language=en, acceptedAt=2026-04-10T12:00:00Z}],
                tax_attestations = [{form=us_w9, isExemptBackupWithholding=true, edeliveryConsent=true, acceptedAt=2026-04-17T20:00:00Z}],
                compliance = {requesterIpAddress=203.0.113.42}
            )
        else:
            return CustomerWriteBase(
        )
        """

    def testCustomerWriteBase(self):
        """Test CustomerWriteBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
