# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdp.openapi_client.models.rate_limiting_criterion import RateLimitingCriterion

class TestRateLimitingCriterion(unittest.TestCase):
    """RateLimitingCriterion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RateLimitingCriterion:
        """Test RateLimitingCriterion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RateLimitingCriterion`
        """
        model = RateLimitingCriterion()
        if include_optional:
            return RateLimitingCriterion(
                type = 'rateLimiting',
                window = '4d2h45m',
                max_count = 10,
                max_value_cents = 100000
            )
        else:
            return RateLimitingCriterion(
                type = 'rateLimiting',
                window = '4d2h45m',
        )
        """

    def testRateLimitingCriterion(self):
        """Test RateLimitingCriterion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
