# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdp.openapi_client.models.bank_account_us import BankAccountUS

class TestBankAccountUS(unittest.TestCase):
    """BankAccountUS unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BankAccountUS:
        """Test BankAccountUS
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BankAccountUS`
        """
        model = BankAccountUS()
        if include_optional:
            return BankAccountUS(
                account_type = 'us_bank',
                currency = 'usd',
                bank_name = 'Citibank, N.A.',
                beneficiary_name = 'John Smith',
                routing_number = '987654321',
                account_number = '123456789',
                bank_address = '399 Park Avenue, New York, NY 10022',
                reference_code = 'CBAUSD1A2B3C4D',
                supported_rails = [ach]
            )
        else:
            return BankAccountUS(
                account_type = 'us_bank',
                currency = 'usd',
                bank_name = 'Citibank, N.A.',
                beneficiary_name = 'John Smith',
                routing_number = '987654321',
                account_number = '123456789',
                supported_rails = [ach],
        )
        """

    def testBankAccountUS(self):
        """Test BankAccountUS"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
