# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdp.openapi_client.models.list_payment_session_voids200_response import ListPaymentSessionVoids200Response

class TestListPaymentSessionVoids200Response(unittest.TestCase):
    """ListPaymentSessionVoids200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListPaymentSessionVoids200Response:
        """Test ListPaymentSessionVoids200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListPaymentSessionVoids200Response`
        """
        model = ListPaymentSessionVoids200Response()
        if include_optional:
            return ListPaymentSessionVoids200Response(
                next_page_token = 'eyJsYXN0X2lkIjogImFiYzEyMyIsICJ0aW1lc3RhbXAiOiAxNzA3ODIzNzAxfQ==',
                voids = [
                    {voidId=void_82c879c1-84e1-44ed-a8c2-1ac239cf09ad, paymentSessionId=paymentSession_82c879c1-84e1-44ed-a8c2-1ac239cf09ad, status=succeeded, amount=1.00, onchainTransactions=[{transactionHash=0x789012345678901234567890abcdef1234567890abcdef1234567890abcdef12, network=base}], metadata={customer_id=cust_12345}, createdAt=2025-06-15T12:30:00.000Z, updatedAt=2025-06-15T12:31:00.000Z}
                    ]
            )
        else:
            return ListPaymentSessionVoids200Response(
                voids = [
                    {voidId=void_82c879c1-84e1-44ed-a8c2-1ac239cf09ad, paymentSessionId=paymentSession_82c879c1-84e1-44ed-a8c2-1ac239cf09ad, status=succeeded, amount=1.00, onchainTransactions=[{transactionHash=0x789012345678901234567890abcdef1234567890abcdef1234567890abcdef12, network=base}], metadata={customer_id=cust_12345}, createdAt=2025-06-15T12:30:00.000Z, updatedAt=2025-06-15T12:31:00.000Z}
                    ],
        )
        """

    def testListPaymentSessionVoids200Response(self):
        """Test ListPaymentSessionVoids200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
