# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdp.openapi_client.models.deposit_travel_rule_request import DepositTravelRuleRequest

class TestDepositTravelRuleRequest(unittest.TestCase):
    """DepositTravelRuleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DepositTravelRuleRequest:
        """Test DepositTravelRuleRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DepositTravelRuleRequest`
        """
        model = DepositTravelRuleRequest()
        if include_optional:
            return DepositTravelRuleRequest(
                originator = {name=John Doe, address={line1=123 Main St, city=San Francisco, state=CA, postCode=94105, countryCode=US}, walletType=custodial, vasp={identifier=5493001KJTIIGC8Y1R17, name=Fidelity Digital Asset Services, LLC}},
                beneficiary = {name=Jane Smith},
                is_self = False
            )
        else:
            return DepositTravelRuleRequest(
        )
        """

    def testDepositTravelRuleRequest(self):
        """Test DepositTravelRuleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
