# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdp.openapi_client.models.mandate_authorization_request import MandateAuthorizationRequest

class TestMandateAuthorizationRequest(unittest.TestCase):
    """MandateAuthorizationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MandateAuthorizationRequest:
        """Test MandateAuthorizationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MandateAuthorizationRequest`
        """
        model = MandateAuthorizationRequest()
        if include_optional:
            return MandateAuthorizationRequest(
                mandate_id = 'mandate_82c879c1-84e1-44ed-a8c2-1ac239cf09ad',
                metadata = {customer_id=cust_12345, order_reference=order-67890},
                customer_display = {referenceCode=REF-ABC123},
                external_reference_id = 'merchant-reference-abc123'
            )
        else:
            return MandateAuthorizationRequest(
                mandate_id = 'mandate_82c879c1-84e1-44ed-a8c2-1ac239cf09ad',
        )
        """

    def testMandateAuthorizationRequest(self):
        """Test MandateAuthorizationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
