# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdp.openapi_client.models.eip2612_payload import EIP2612Payload

class TestEIP2612Payload(unittest.TestCase):
    """EIP2612Payload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EIP2612Payload:
        """Test EIP2612Payload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EIP2612Payload`
        """
        model = EIP2612Payload()
        if include_optional:
            return EIP2612Payload(
                payload_id = 'payload_af2937b0-9846-4fe7-bfe9-ccc22d935114',
                type = 'eip2612',
                data = {domain={name=Permit2, chainId=1, verifyingContract=0x000000000022D473030F116dDEE9F6B43aC78BA3}, types={EIP712Domain=[{name=name, type=string}, {name=chainId, type=uint256}, {name=verifyingContract, type=address}], PermitTransferFrom=[{name=permitted, type=TokenPermissions}, {name=spender, type=address}, {name=nonce, type=uint256}, {name=deadline, type=uint256}], TokenPermissions=[{name=token, type=address}, {name=amount, type=uint256}]}, primaryType=PermitTransferFrom, message={permitted={token=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48, amount=1000000}, spender=0xFfFfFfFFfFFfFFfFFfFFFFFffFFFffffFfFFFfFf, nonce=123456, deadline=1717123200}}
            )
        else:
            return EIP2612Payload(
                payload_id = 'payload_af2937b0-9846-4fe7-bfe9-ccc22d935114',
                type = 'eip2612',
                data = {domain={name=Permit2, chainId=1, verifyingContract=0x000000000022D473030F116dDEE9F6B43aC78BA3}, types={EIP712Domain=[{name=name, type=string}, {name=chainId, type=uint256}, {name=verifyingContract, type=address}], PermitTransferFrom=[{name=permitted, type=TokenPermissions}, {name=spender, type=address}, {name=nonce, type=uint256}, {name=deadline, type=uint256}], TokenPermissions=[{name=token, type=address}, {name=amount, type=uint256}]}, primaryType=PermitTransferFrom, message={permitted={token=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48, amount=1000000}, spender=0xFfFfFfFFfFFfFFfFFfFFFFFffFFFffffFfFFFfFf, nonce=123456, deadline=1717123200}},
        )
        """

    def testEIP2612Payload(self):
        """Test EIP2612Payload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
