# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdp.openapi_client.models.erc20_approval_payload import Erc20ApprovalPayload

class TestErc20ApprovalPayload(unittest.TestCase):
    """Erc20ApprovalPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Erc20ApprovalPayload:
        """Test Erc20ApprovalPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Erc20ApprovalPayload`
        """
        model = Erc20ApprovalPayload()
        if include_optional:
            return Erc20ApprovalPayload(
                payload_id = 'payload_bf3948c1-a957-5gh8-cgf0-ddd33e046225',
                type = 'erc20_approval',
                data = {chainId=1, to=0xdAC17F958D2ee523a2206206994597C13D831ec7, data=0x095ea7b3000000000000000000000000000000000022d473030f116ddee9f6b43ac78ba3000000000000000000000000ffffffffffffffffffffffffffffffffffffffff, value=0, gas=63804, maxFeePerGas=1751588354, maxPriorityFeePerGas=1000000000}
            )
        else:
            return Erc20ApprovalPayload(
                payload_id = 'payload_bf3948c1-a957-5gh8-cgf0-ddd33e046225',
                type = 'erc20_approval',
                data = {chainId=1, to=0xdAC17F958D2ee523a2206206994597C13D831ec7, data=0x095ea7b3000000000000000000000000000000000022d473030f116ddee9f6b43ac78ba3000000000000000000000000ffffffffffffffffffffffffffffffffffffffff, value=0, gas=63804, maxFeePerGas=1751588354, maxPriorityFeePerGas=1000000000},
        )
        """

    def testErc20ApprovalPayload(self):
        """Test Erc20ApprovalPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
