# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdp.openapi_client.api.x402_facilitator_api import X402FacilitatorApi


class TestX402FacilitatorApi(unittest.IsolatedAsyncioTestCase):
    """X402FacilitatorApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = X402FacilitatorApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_list_x402_discovery_resources(self) -> None:
        """Test case for list_x402_discovery_resources

        List discovered x402 resources
        """
        pass


if __name__ == '__main__':
    unittest.main()
