# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdp.openapi_client.models.tos_acceptance import TosAcceptance

class TestTosAcceptance(unittest.TestCase):
    """TosAcceptance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TosAcceptance:
        """Test TosAcceptance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TosAcceptance`
        """
        model = TosAcceptance()
        if include_optional:
            return TosAcceptance(
                version_id = 'us_individual_2026-05-29',
                language = 'en',
                accepted_at = '2026-04-10T12:00:00Z'
            )
        else:
            return TosAcceptance(
                version_id = 'us_individual_2026-05-29',
                language = 'en',
                accepted_at = '2026-04-10T12:00:00Z',
        )
        """

    def testTosAcceptance(self):
        """Test TosAcceptance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
