import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/core/client/index.ts",
    "src/core/wallets/index.ts",
    "src/core/facilitator/index.ts",
    "src/core/server/index.ts",
    "src/core/extensions/index.ts",
    "src/core/guardrails/index.ts",
    "src/core/index.ts",
  ],
  format: ["cjs", "esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: false,
  treeshake: true,
  external: [
    "@coinbase/cdp-sdk",
    "@coinbase/cdp-sdk/auth",
    "@x402/core",
    "@x402/core/client",
    "@x402/core/types",
    "@x402/core/http",
    "@x402/core/server",
    "@x402/fetch",
    "@x402/evm",
    "@x402/evm/v1",
    "@x402/evm/exact/client",
    "@x402/evm/exact/server",
    "@x402/evm/upto/server",
    "@x402/svm",
    "@x402/svm/exact/client",
    "@x402/svm/exact/server",
    "@solana/kit",
  ],
});
