/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.coinbase.cdp.openapi.api;

import com.coinbase.cdp.openapi.ApiClient;
import com.coinbase.cdp.openapi.ApiException;
import com.coinbase.cdp.openapi.ApiResponse;
import com.coinbase.cdp.openapi.Pair;

import com.coinbase.cdp.openapi.model.WalletDelegationCreatedEvent;
import com.coinbase.cdp.openapi.model.WalletDelegationRevokedEvent;
import com.coinbase.cdp.openapi.model.WalletHashSignedEvent;
import com.coinbase.cdp.openapi.model.WalletMessageSignedEvent;
import com.coinbase.cdp.openapi.model.WalletTransactionBroadcastEvent;
import com.coinbase.cdp.openapi.model.WalletTransactionConfirmedEvent;
import com.coinbase.cdp.openapi.model.WalletTransactionCreatedEvent;
import com.coinbase.cdp.openapi.model.WalletTransactionFailedEvent;
import com.coinbase.cdp.openapi.model.WalletTransactionPendingEvent;
import com.coinbase.cdp.openapi.model.WalletTransactionReplacedEvent;
import com.coinbase.cdp.openapi.model.WalletTransactionSignedEvent;
import com.coinbase.cdp.openapi.model.WalletTypedDataSignedEvent;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class WalletWebhooksApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public WalletWebhooksApi() {
    this(new ApiClient());
  }

  public WalletWebhooksApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Wallet delegation created
   * Triggered when the &#x60;wallet.delegation.created&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletDelegationCreatedEvent The &#x60;wallet.delegation.created&#x60; webhook event payload. (required)
   * @throws ApiException if fails to make API call
   */
  public void walletDelegationCreatedWebhook(WalletDelegationCreatedEvent walletDelegationCreatedEvent) throws ApiException {
    walletDelegationCreatedWebhookWithHttpInfo(walletDelegationCreatedEvent);
  }

  /**
   * Wallet delegation created
   * Triggered when the &#x60;wallet.delegation.created&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletDelegationCreatedEvent The &#x60;wallet.delegation.created&#x60; webhook event payload. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> walletDelegationCreatedWebhookWithHttpInfo(WalletDelegationCreatedEvent walletDelegationCreatedEvent) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = walletDelegationCreatedWebhookRequestBuilder(walletDelegationCreatedEvent);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("walletDelegationCreatedWebhook", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder walletDelegationCreatedWebhookRequestBuilder(WalletDelegationCreatedEvent walletDelegationCreatedEvent) throws ApiException {
    // verify the required parameter 'walletDelegationCreatedEvent' is set
    if (walletDelegationCreatedEvent == null) {
      throw new ApiException(400, "Missing the required parameter 'walletDelegationCreatedEvent' when calling walletDelegationCreatedWebhook");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/walletDelegationCreated";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(walletDelegationCreatedEvent);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Wallet delegation revoked
   * Triggered when the &#x60;wallet.delegation.revoked&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletDelegationRevokedEvent The &#x60;wallet.delegation.revoked&#x60; webhook event payload. (required)
   * @throws ApiException if fails to make API call
   */
  public void walletDelegationRevokedWebhook(WalletDelegationRevokedEvent walletDelegationRevokedEvent) throws ApiException {
    walletDelegationRevokedWebhookWithHttpInfo(walletDelegationRevokedEvent);
  }

  /**
   * Wallet delegation revoked
   * Triggered when the &#x60;wallet.delegation.revoked&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletDelegationRevokedEvent The &#x60;wallet.delegation.revoked&#x60; webhook event payload. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> walletDelegationRevokedWebhookWithHttpInfo(WalletDelegationRevokedEvent walletDelegationRevokedEvent) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = walletDelegationRevokedWebhookRequestBuilder(walletDelegationRevokedEvent);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("walletDelegationRevokedWebhook", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder walletDelegationRevokedWebhookRequestBuilder(WalletDelegationRevokedEvent walletDelegationRevokedEvent) throws ApiException {
    // verify the required parameter 'walletDelegationRevokedEvent' is set
    if (walletDelegationRevokedEvent == null) {
      throw new ApiException(400, "Missing the required parameter 'walletDelegationRevokedEvent' when calling walletDelegationRevokedWebhook");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/walletDelegationRevoked";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(walletDelegationRevokedEvent);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Wallet hash signed
   * Triggered when the &#x60;wallet.hash.signed&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletHashSignedEvent The &#x60;wallet.hash.signed&#x60; webhook event payload. (required)
   * @throws ApiException if fails to make API call
   */
  public void walletHashSignedWebhook(WalletHashSignedEvent walletHashSignedEvent) throws ApiException {
    walletHashSignedWebhookWithHttpInfo(walletHashSignedEvent);
  }

  /**
   * Wallet hash signed
   * Triggered when the &#x60;wallet.hash.signed&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletHashSignedEvent The &#x60;wallet.hash.signed&#x60; webhook event payload. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> walletHashSignedWebhookWithHttpInfo(WalletHashSignedEvent walletHashSignedEvent) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = walletHashSignedWebhookRequestBuilder(walletHashSignedEvent);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("walletHashSignedWebhook", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder walletHashSignedWebhookRequestBuilder(WalletHashSignedEvent walletHashSignedEvent) throws ApiException {
    // verify the required parameter 'walletHashSignedEvent' is set
    if (walletHashSignedEvent == null) {
      throw new ApiException(400, "Missing the required parameter 'walletHashSignedEvent' when calling walletHashSignedWebhook");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/walletHashSigned";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(walletHashSignedEvent);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Wallet message signed
   * Triggered when the &#x60;wallet.message.signed&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletMessageSignedEvent The &#x60;wallet.message.signed&#x60; webhook event payload. (required)
   * @throws ApiException if fails to make API call
   */
  public void walletMessageSignedWebhook(WalletMessageSignedEvent walletMessageSignedEvent) throws ApiException {
    walletMessageSignedWebhookWithHttpInfo(walletMessageSignedEvent);
  }

  /**
   * Wallet message signed
   * Triggered when the &#x60;wallet.message.signed&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletMessageSignedEvent The &#x60;wallet.message.signed&#x60; webhook event payload. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> walletMessageSignedWebhookWithHttpInfo(WalletMessageSignedEvent walletMessageSignedEvent) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = walletMessageSignedWebhookRequestBuilder(walletMessageSignedEvent);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("walletMessageSignedWebhook", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder walletMessageSignedWebhookRequestBuilder(WalletMessageSignedEvent walletMessageSignedEvent) throws ApiException {
    // verify the required parameter 'walletMessageSignedEvent' is set
    if (walletMessageSignedEvent == null) {
      throw new ApiException(400, "Missing the required parameter 'walletMessageSignedEvent' when calling walletMessageSignedWebhook");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/walletMessageSigned";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(walletMessageSignedEvent);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Wallet transaction broadcast
   * Triggered when the &#x60;wallet.transaction.broadcast&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletTransactionBroadcastEvent The &#x60;wallet.transaction.broadcast&#x60; webhook event payload. (required)
   * @throws ApiException if fails to make API call
   */
  public void walletTransactionBroadcastWebhook(WalletTransactionBroadcastEvent walletTransactionBroadcastEvent) throws ApiException {
    walletTransactionBroadcastWebhookWithHttpInfo(walletTransactionBroadcastEvent);
  }

  /**
   * Wallet transaction broadcast
   * Triggered when the &#x60;wallet.transaction.broadcast&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletTransactionBroadcastEvent The &#x60;wallet.transaction.broadcast&#x60; webhook event payload. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> walletTransactionBroadcastWebhookWithHttpInfo(WalletTransactionBroadcastEvent walletTransactionBroadcastEvent) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = walletTransactionBroadcastWebhookRequestBuilder(walletTransactionBroadcastEvent);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("walletTransactionBroadcastWebhook", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder walletTransactionBroadcastWebhookRequestBuilder(WalletTransactionBroadcastEvent walletTransactionBroadcastEvent) throws ApiException {
    // verify the required parameter 'walletTransactionBroadcastEvent' is set
    if (walletTransactionBroadcastEvent == null) {
      throw new ApiException(400, "Missing the required parameter 'walletTransactionBroadcastEvent' when calling walletTransactionBroadcastWebhook");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/walletTransactionBroadcast";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(walletTransactionBroadcastEvent);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Wallet transaction confirmed
   * Triggered when the &#x60;wallet.transaction.confirmed&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletTransactionConfirmedEvent The &#x60;wallet.transaction.confirmed&#x60; webhook event payload. (required)
   * @throws ApiException if fails to make API call
   */
  public void walletTransactionConfirmedWebhook(WalletTransactionConfirmedEvent walletTransactionConfirmedEvent) throws ApiException {
    walletTransactionConfirmedWebhookWithHttpInfo(walletTransactionConfirmedEvent);
  }

  /**
   * Wallet transaction confirmed
   * Triggered when the &#x60;wallet.transaction.confirmed&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletTransactionConfirmedEvent The &#x60;wallet.transaction.confirmed&#x60; webhook event payload. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> walletTransactionConfirmedWebhookWithHttpInfo(WalletTransactionConfirmedEvent walletTransactionConfirmedEvent) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = walletTransactionConfirmedWebhookRequestBuilder(walletTransactionConfirmedEvent);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("walletTransactionConfirmedWebhook", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder walletTransactionConfirmedWebhookRequestBuilder(WalletTransactionConfirmedEvent walletTransactionConfirmedEvent) throws ApiException {
    // verify the required parameter 'walletTransactionConfirmedEvent' is set
    if (walletTransactionConfirmedEvent == null) {
      throw new ApiException(400, "Missing the required parameter 'walletTransactionConfirmedEvent' when calling walletTransactionConfirmedWebhook");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/walletTransactionConfirmed";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(walletTransactionConfirmedEvent);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Wallet transaction created
   * Triggered when the &#x60;wallet.transaction.created&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletTransactionCreatedEvent The &#x60;wallet.transaction.created&#x60; webhook event payload. (required)
   * @throws ApiException if fails to make API call
   */
  public void walletTransactionCreatedWebhook(WalletTransactionCreatedEvent walletTransactionCreatedEvent) throws ApiException {
    walletTransactionCreatedWebhookWithHttpInfo(walletTransactionCreatedEvent);
  }

  /**
   * Wallet transaction created
   * Triggered when the &#x60;wallet.transaction.created&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletTransactionCreatedEvent The &#x60;wallet.transaction.created&#x60; webhook event payload. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> walletTransactionCreatedWebhookWithHttpInfo(WalletTransactionCreatedEvent walletTransactionCreatedEvent) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = walletTransactionCreatedWebhookRequestBuilder(walletTransactionCreatedEvent);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("walletTransactionCreatedWebhook", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder walletTransactionCreatedWebhookRequestBuilder(WalletTransactionCreatedEvent walletTransactionCreatedEvent) throws ApiException {
    // verify the required parameter 'walletTransactionCreatedEvent' is set
    if (walletTransactionCreatedEvent == null) {
      throw new ApiException(400, "Missing the required parameter 'walletTransactionCreatedEvent' when calling walletTransactionCreatedWebhook");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/walletTransactionCreated";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(walletTransactionCreatedEvent);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Wallet transaction failed
   * Triggered when the &#x60;wallet.transaction.failed&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletTransactionFailedEvent The &#x60;wallet.transaction.failed&#x60; webhook event payload. (required)
   * @throws ApiException if fails to make API call
   */
  public void walletTransactionFailedWebhook(WalletTransactionFailedEvent walletTransactionFailedEvent) throws ApiException {
    walletTransactionFailedWebhookWithHttpInfo(walletTransactionFailedEvent);
  }

  /**
   * Wallet transaction failed
   * Triggered when the &#x60;wallet.transaction.failed&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletTransactionFailedEvent The &#x60;wallet.transaction.failed&#x60; webhook event payload. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> walletTransactionFailedWebhookWithHttpInfo(WalletTransactionFailedEvent walletTransactionFailedEvent) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = walletTransactionFailedWebhookRequestBuilder(walletTransactionFailedEvent);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("walletTransactionFailedWebhook", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder walletTransactionFailedWebhookRequestBuilder(WalletTransactionFailedEvent walletTransactionFailedEvent) throws ApiException {
    // verify the required parameter 'walletTransactionFailedEvent' is set
    if (walletTransactionFailedEvent == null) {
      throw new ApiException(400, "Missing the required parameter 'walletTransactionFailedEvent' when calling walletTransactionFailedWebhook");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/walletTransactionFailed";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(walletTransactionFailedEvent);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Wallet transaction pending
   * Triggered when the &#x60;wallet.transaction.pending&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletTransactionPendingEvent The &#x60;wallet.transaction.pending&#x60; webhook event payload. (required)
   * @throws ApiException if fails to make API call
   */
  public void walletTransactionPendingWebhook(WalletTransactionPendingEvent walletTransactionPendingEvent) throws ApiException {
    walletTransactionPendingWebhookWithHttpInfo(walletTransactionPendingEvent);
  }

  /**
   * Wallet transaction pending
   * Triggered when the &#x60;wallet.transaction.pending&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletTransactionPendingEvent The &#x60;wallet.transaction.pending&#x60; webhook event payload. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> walletTransactionPendingWebhookWithHttpInfo(WalletTransactionPendingEvent walletTransactionPendingEvent) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = walletTransactionPendingWebhookRequestBuilder(walletTransactionPendingEvent);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("walletTransactionPendingWebhook", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder walletTransactionPendingWebhookRequestBuilder(WalletTransactionPendingEvent walletTransactionPendingEvent) throws ApiException {
    // verify the required parameter 'walletTransactionPendingEvent' is set
    if (walletTransactionPendingEvent == null) {
      throw new ApiException(400, "Missing the required parameter 'walletTransactionPendingEvent' when calling walletTransactionPendingWebhook");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/walletTransactionPending";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(walletTransactionPendingEvent);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Wallet transaction replaced
   * Triggered when the &#x60;wallet.transaction.replaced&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletTransactionReplacedEvent The &#x60;wallet.transaction.replaced&#x60; webhook event payload. (required)
   * @throws ApiException if fails to make API call
   */
  public void walletTransactionReplacedWebhook(WalletTransactionReplacedEvent walletTransactionReplacedEvent) throws ApiException {
    walletTransactionReplacedWebhookWithHttpInfo(walletTransactionReplacedEvent);
  }

  /**
   * Wallet transaction replaced
   * Triggered when the &#x60;wallet.transaction.replaced&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletTransactionReplacedEvent The &#x60;wallet.transaction.replaced&#x60; webhook event payload. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> walletTransactionReplacedWebhookWithHttpInfo(WalletTransactionReplacedEvent walletTransactionReplacedEvent) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = walletTransactionReplacedWebhookRequestBuilder(walletTransactionReplacedEvent);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("walletTransactionReplacedWebhook", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder walletTransactionReplacedWebhookRequestBuilder(WalletTransactionReplacedEvent walletTransactionReplacedEvent) throws ApiException {
    // verify the required parameter 'walletTransactionReplacedEvent' is set
    if (walletTransactionReplacedEvent == null) {
      throw new ApiException(400, "Missing the required parameter 'walletTransactionReplacedEvent' when calling walletTransactionReplacedWebhook");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/walletTransactionReplaced";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(walletTransactionReplacedEvent);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Wallet transaction signed
   * Triggered when the &#x60;wallet.transaction.signed&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletTransactionSignedEvent The &#x60;wallet.transaction.signed&#x60; webhook event payload. (required)
   * @throws ApiException if fails to make API call
   */
  public void walletTransactionSignedWebhook(WalletTransactionSignedEvent walletTransactionSignedEvent) throws ApiException {
    walletTransactionSignedWebhookWithHttpInfo(walletTransactionSignedEvent);
  }

  /**
   * Wallet transaction signed
   * Triggered when the &#x60;wallet.transaction.signed&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletTransactionSignedEvent The &#x60;wallet.transaction.signed&#x60; webhook event payload. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> walletTransactionSignedWebhookWithHttpInfo(WalletTransactionSignedEvent walletTransactionSignedEvent) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = walletTransactionSignedWebhookRequestBuilder(walletTransactionSignedEvent);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("walletTransactionSignedWebhook", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder walletTransactionSignedWebhookRequestBuilder(WalletTransactionSignedEvent walletTransactionSignedEvent) throws ApiException {
    // verify the required parameter 'walletTransactionSignedEvent' is set
    if (walletTransactionSignedEvent == null) {
      throw new ApiException(400, "Missing the required parameter 'walletTransactionSignedEvent' when calling walletTransactionSignedWebhook");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/walletTransactionSigned";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(walletTransactionSignedEvent);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Wallet typed data signed
   * Triggered when the &#x60;wallet.typed_data.signed&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletTypedDataSignedEvent The &#x60;wallet.typed_data.signed&#x60; webhook event payload. (required)
   * @throws ApiException if fails to make API call
   */
  public void walletTypedDataSignedWebhook(WalletTypedDataSignedEvent walletTypedDataSignedEvent) throws ApiException {
    walletTypedDataSignedWebhookWithHttpInfo(walletTypedDataSignedEvent);
  }

  /**
   * Wallet typed data signed
   * Triggered when the &#x60;wallet.typed_data.signed&#x60; webhook event is emitted. Your API will receive a POST request at the webhook URL you configured.
   * @param walletTypedDataSignedEvent The &#x60;wallet.typed_data.signed&#x60; webhook event payload. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> walletTypedDataSignedWebhookWithHttpInfo(WalletTypedDataSignedEvent walletTypedDataSignedEvent) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = walletTypedDataSignedWebhookRequestBuilder(walletTypedDataSignedEvent);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("walletTypedDataSignedWebhook", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder walletTypedDataSignedWebhookRequestBuilder(WalletTypedDataSignedEvent walletTypedDataSignedEvent) throws ApiException {
    // verify the required parameter 'walletTypedDataSignedEvent' is set
    if (walletTypedDataSignedEvent == null) {
      throw new ApiException(400, "Missing the required parameter 'walletTypedDataSignedEvent' when calling walletTypedDataSignedWebhook");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/walletTypedDataSigned";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(walletTypedDataSignedEvent);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
