/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.coinbase.cdp.resources.policyengine.requests;

import com.coinbase.cdp.core.ObjectMappers;
import com.coinbase.cdp.resources.policyengine.types.ListPoliciesRequestScope;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListPoliciesRequest.Builder.class
)
public final class ListPoliciesRequest {
  private final Optional<Integer> pageSize;

  private final Optional<String> pageToken;

  private final Optional<ListPoliciesRequestScope> scope;

  private final Map<String, Object> additionalProperties;

  private ListPoliciesRequest(Optional<Integer> pageSize, Optional<String> pageToken,
      Optional<ListPoliciesRequestScope> scope, Map<String, Object> additionalProperties) {
    this.pageSize = pageSize;
    this.pageToken = pageToken;
    this.scope = scope;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The number of resources to return per page.
   */
  @JsonProperty("pageSize")
  public Optional<Integer> getPageSize() {
    return pageSize;
  }

  /**
   * @return The token for the next page of resources, if any.
   */
  @JsonProperty("pageToken")
  public Optional<String> getPageToken() {
    return pageToken;
  }

  /**
   * @return The scope of the policies to return. If <code>project</code>, the response will include exactly one policy, which is the project-level policy. If <code>account</code>, the response will include all account-level policies for the developer's CDP Project.
   */
  @JsonProperty("scope")
  public Optional<ListPoliciesRequestScope> getScope() {
    return scope;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListPoliciesRequest && equalTo((ListPoliciesRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListPoliciesRequest other) {
    return pageSize.equals(other.pageSize) && pageToken.equals(other.pageToken) && scope.equals(other.scope);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.pageSize, this.pageToken, this.scope);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Integer> pageSize = Optional.empty();

    private Optional<String> pageToken = Optional.empty();

    private Optional<ListPoliciesRequestScope> scope = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ListPoliciesRequest other) {
      pageSize(other.getPageSize());
      pageToken(other.getPageToken());
      scope(other.getScope());
      return this;
    }

    /**
     * <p>The number of resources to return per page.</p>
     */
    @JsonSetter(
        value = "pageSize",
        nulls = Nulls.SKIP
    )
    public Builder pageSize(Optional<Integer> pageSize) {
      this.pageSize = pageSize;
      return this;
    }

    public Builder pageSize(Integer pageSize) {
      this.pageSize = Optional.ofNullable(pageSize);
      return this;
    }

    /**
     * <p>The token for the next page of resources, if any.</p>
     */
    @JsonSetter(
        value = "pageToken",
        nulls = Nulls.SKIP
    )
    public Builder pageToken(Optional<String> pageToken) {
      this.pageToken = pageToken;
      return this;
    }

    public Builder pageToken(String pageToken) {
      this.pageToken = Optional.ofNullable(pageToken);
      return this;
    }

    /**
     * <p>The scope of the policies to return. If <code>project</code>, the response will include exactly one policy, which is the project-level policy. If <code>account</code>, the response will include all account-level policies for the developer's CDP Project.</p>
     */
    @JsonSetter(
        value = "scope",
        nulls = Nulls.SKIP
    )
    public Builder scope(Optional<ListPoliciesRequestScope> scope) {
      this.scope = scope;
      return this;
    }

    public Builder scope(ListPoliciesRequestScope scope) {
      this.scope = Optional.ofNullable(scope);
      return this;
    }

    public ListPoliciesRequest build() {
      return new ListPoliciesRequest(pageSize, pageToken, scope, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
