name: Deploy CDP SDK documentation to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      choice:
        description: "SDK language to deploy"
        required: true
        type: choice
        options:
          - typescript
          - python
          - go

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  deploy-typescript-docs:
    if: inputs.choice == 'typescript'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: "./typescript/pnpm-lock.yaml"

      - name: Install TypeScript dependencies
        run: |
          cd typescript
          pnpm install

      - name: Build TypeScript docs
        run: |
          cd typescript
          pnpm run docs

      - name: Upload TypeScript docs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: typescript-docs
          path: ./typescript/docs

      - name: Fetch Python docs
        uses: ./.github/actions/fetch-docs-artifact
        with:
          artifact-name: "python-docs"
          target-path: "./python/docs/_build/html"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Go docs
        uses: ./.github/actions/fetch-docs-artifact
        with:
          artifact-name: "go-docs"
          target-path: "./go/docs"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Combine built assets into one folder
        run: |
          mkdir -p combined/typescript
          mkdir -p combined/python
          mkdir -p combined/go

          cp -r typescript/docs/* combined/typescript/
          cp -r python/docs/_build/html/* combined/python/
          cp -r go/docs/* combined/go/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: "./combined"

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

  deploy-python-docs:
    if: inputs.choice == 'python'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python 3.10
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.5.0
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          cd python
          make setup
          make install
          cd ..

      - name: Build Sphinx Documentation for CDP SDK
        run: |
          pip install -U sphinx
          pip install myst_parser sphinx_autodoc_typehints pydantic eth_account aiohttp aiohttp_retry cryptography jwt web3 pytest
          pip install python-dateutil --upgrade
          cd python
          make docs
          cd docs
          make html
          cd ../..

      - name: Upload Python docs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: python-docs
          path: ./python/docs/_build/html

      - name: Fetch TypeScript docs
        uses: ./.github/actions/fetch-docs-artifact
        with:
          artifact-name: "typescript-docs"
          target-path: "./typescript/docs"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Go docs
        uses: ./.github/actions/fetch-docs-artifact
        with:
          artifact-name: "go-docs"
          target-path: "./go/docs"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Combine built assets into one folder
        run: |
          mkdir -p combined/typescript
          mkdir -p combined/python
          mkdir -p combined/go

          cp -r typescript/docs/* combined/typescript/
          cp -r python/docs/_build/html/* combined/python/
          cp -r go/docs/* combined/go/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: "./combined"

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

  deploy-go-docs:
    if: inputs.choice == 'go'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: "1.23"
          cache: true

      - name: Install golds
        run: |
          cd go
          go install go101.org/golds@v0.7.6
          cd ..

      - name: Build Go Documentation for CDP SDK
        run: |
          cd go
          make docs
          cd ..

      - name: Upload Go docs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: go-docs
          path: ./go/docs

      - name: Fetch TypeScript docs
        uses: ./.github/actions/fetch-docs-artifact
        with:
          artifact-name: "typescript-docs"
          target-path: "./typescript/docs"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Python docs
        uses: ./.github/actions/fetch-docs-artifact
        with:
          artifact-name: "python-docs"
          target-path: "./python/docs/_build/html"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Combine built assets into one folder
        run: |
          mkdir -p combined/typescript
          mkdir -p combined/python
          mkdir -p combined/go

          cp -r typescript/docs/* combined/typescript/
          cp -r python/docs/_build/html/* combined/python/
          cp -r go/docs/* combined/go/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: "./combined"

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
