name: Python Linting

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./python

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment
        run: uv venv

      - name: Install ruff
        run: |
          source .venv/bin/activate
          uv pip install ruff

      - name: Verify environment
        run: make verify-env

      - name: Install dependencies
        run: make install

      - name: Run linters
        run: make lint
