name: E2E Rust Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

defaults:
  run:
    working-directory: ./rust

jobs:
  e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: ["stable", "beta"]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Rust ${{ matrix.rust }}
        uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17
        with:
          toolchain: ${{ matrix.rust }}

      - name: Cache Cargo dependencies
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            rust/target/
          key: ${{ runner.os }}-cargo-e2e-${{ matrix.rust }}-${{ hashFiles('rust/Cargo.lock') }}

      - name: Build project
        run: cargo build --verbose

      - name: Run E2E Tests
        if: failure()
        env:
          CDP_API_KEY_ID: ${{ secrets.CDP_API_KEY_ID }}
          CDP_API_KEY_SECRET: ${{ secrets.CDP_API_KEY_SECRET }}
          CDP_WALLET_SECRET: ${{ secrets.CDP_WALLET_SECRET }}
          CDP_E2E_SMART_ACCOUNT_ADDRESS: ${{ vars.CDP_E2E_SMART_ACCOUNT_ADDRESS }}
          CDP_E2E_SOLANA_RPC_URL: ${{ secrets.CDP_E2E_SOLANA_RPC_URL }}
          CDP_E2E_SKIP_EVM_TOKEN_BALANCES: ${{ vars.CDP_E2E_SKIP_EVM_TOKEN_BALANCES }}
          E2E_LOGGING: true
          DISABLE_CDP_ERROR_REPORTING: true
          DISABLE_CDP_USAGE_TRACKING: true
        run: cargo test --test e2e --verbose -- --nocapture
