/*
 * Coinbase Developer Platform APIs
 *
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};

/// struct for passing parameters to the method [`list_data_token_balances`]
#[derive(Clone, Debug)]
pub struct ListDataTokenBalancesParams {
    /// The 0x-prefixed EVM address to get balances for. The address does not need to be checksummed.
    pub address: String,
    /// The human-readable network name to get the balances for.
    pub network: models::ListEvmTokenBalancesNetwork,
    /// The number of balances to return per page.
    pub page_size: Option<i32>,
    /// The token for the next page of balances. Will be empty if there are no more balances to fetch.
    pub page_token: Option<String>
}

/// struct for passing parameters to the method [`list_tokens_for_account`]
#[derive(Clone, Debug)]
pub struct ListTokensForAccountParams {
    /// The blockchain network to query.
    pub network: String,
    /// The account address to analyze for token interactions.
    pub address: String
}

/// struct for passing parameters to the method [`run_sql_query`]
#[derive(Clone, Debug)]
pub struct RunSqlQueryParams {
    pub onchain_data_query: models::OnchainDataQuery
}


/// struct for typed errors of method [`list_data_token_balances`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListDataTokenBalancesError {
    Status400(models::Error),
    Status404(models::Error),
    Status500(models::Error),
    Status502(models::Error),
    Status503(models::Error),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_tokens_for_account`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListTokensForAccountError {
    Status400(models::Error),
    Status401(models::Error),
    Status429(models::Error),
    Status500(models::Error),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`run_sql_query`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RunSqlQueryError {
    Status400(models::Error),
    Status401(models::Error),
    Status408(models::Error),
    Status429(models::Error),
    Status500(models::Error),
    Status504(models::Error),
    UnknownValue(serde_json::Value),
}


/// Lists the token balances of an EVM address on a given network. The balances include ERC-20 tokens and the native gas token (usually ETH). The response is paginated, and by default, returns 20 balances per page.  **Note:** This endpoint provides <1 second freshness from chain tip, <500ms response latency for wallets with reasonable token history, and 99.9% uptime for production use.
pub async fn list_data_token_balances(configuration: &configuration::Configuration, params: ListDataTokenBalancesParams) -> Result<models::ListEvmTokenBalances200Response, Error<ListDataTokenBalancesError>> {

    let uri_str = format!("{}/v2/data/evm/token-balances/{network}/{address}", configuration.base_path, address=crate::apis::urlencode(params.address), network=params.network.to_string());
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.page_size {
        req_builder = req_builder.query(&[("pageSize", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page_token {
        req_builder = req_builder.query(&[("pageToken", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        serde_json::from_str(&content).map_err(Error::from)
    } else {
        let content = resp.text().await?;
        let entity: Option<ListDataTokenBalancesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieve all ERC-20 token contract addresses that an account has ever received tokens from.  Analyzes transaction history to discover token interactions. 
pub async fn list_tokens_for_account(configuration: &configuration::Configuration, params: ListTokensForAccountParams) -> Result<models::AccountTokenAddressesResponse, Error<ListTokensForAccountError>> {

    let uri_str = format!("{}/v2/data/evm/token-ownership/{network}/{address}", configuration.base_path, network=crate::apis::urlencode(params.network), address=crate::apis::urlencode(params.address));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        serde_json::from_str(&content).map_err(Error::from)
    } else {
        let content = resp.text().await?;
        let entity: Option<ListTokensForAccountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Run a read-only SQL query against indexed blockchain data including transactions, events, and decoded logs.  This endpoint provides direct SQL access to comprehensive blockchain data across supported networks. Queries are executed against optimized data structures for high-performance analytics.  ### Allowed Queries    - Standard SQL syntax (ClickHouse dialect)   - Read-only queries (SELECT statements)   - No DDL or DML operations   - No cartesian products  ### Supported Tables    - `base.events` - Base mainnet decoded event logs with parameters, event signature, topics, and more.   - `base.transactions` - Base mainnet transaction data including hash, block number, gas usage.   - `base.blocks` - Base mainnet block information.   - `base.encoded_logs` - Encoded log data of event logs that aren't able to be decoded by our event decoder (ex: log0 opcode).   - `base.transfers` - All event logs with event signature `Transfer(address,address,uint256)`. ERC-20, ERC-721, and ERC-1155 transfers are all included.  ### Query Limits    - Maximum result set: 10,000 rows   - Query timeout: 30 seconds   - Maximum JOINs: 5 
pub async fn run_sql_query(configuration: &configuration::Configuration, params: RunSqlQueryParams) -> Result<models::OnchainDataResult, Error<RunSqlQueryError>> {

    let uri_str = format!("{}/v2/data/query/run", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.onchain_data_query);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        serde_json::from_str(&content).map_err(Error::from)
    } else {
        let content = resp.text().await?;
        let entity: Option<RunSqlQueryError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

